use super::*;
use flow_like::flow_like_storage::blake3;
use flow_like_model_provider::stablediffusion::{
    GenerationMode, GenerationRequest, PROVIDER_NAME, StableDiffusionConfig, generate,
};
use flow_like_types::json::{to_value, to_vec};

// Names accepted by stable-diffusion.cpp at the pinned server revision.
const SAMPLERS: &[&str] = &[
    "auto",
    "euler",
    "euler_a",
    "heun",
    "dpm2",
    "dpm++2s_a",
    "dpm++2m",
    "dpm++2mv2",
    "ipndm",
    "ipndm_v",
    "lcm",
    "ddim_trailing",
    "tcd",
    "res_multistep",
    "res_2s",
    "er_sde",
    "euler_cfg_pp",
    "euler_a_cfg_pp",
    "euler_ge",
    "dpm++2m_sde",
    "dpm++2m_sde_bt",
    "lms",
];
const SCHEDULERS: &[&str] = &[
    "auto",
    "discrete",
    "karras",
    "exponential",
    "ays",
    "gits",
    "sgm_uniform",
    "simple",
    "smoothstep",
    "kl_optimal",
    "lcm",
    "bong_tangent",
    "ltx2",
    "logit_normal",
    "flux2",
    "flux",
    "beta",
];

/// Sampling controls for an image generated by stable-diffusion.cpp.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, PartialEq)]
#[serde(default, deny_unknown_fields)]
pub struct StableDiffusionImageOptions {
    pub width: u32,
    pub height: u32,
    pub steps: u32,
    pub cfg_scale: f64,
    pub negative_prompt: Option<String>,
    /// Use -1 for a random seed; zero is a reproducible seed.
    pub seed: i64,
    /// Use auto to keep the model's sampling method.
    pub sampler: String,
    /// Use auto to keep the model's scheduler.
    pub scheduler: String,
}

impl Default for StableDiffusionImageOptions {
    fn default() -> Self {
        Self {
            width: 512,
            height: 512,
            steps: 20,
            cfg_scale: 7.0,
            negative_prompt: None,
            seed: -1,
            sampler: "auto".to_string(),
            scheduler: "auto".to_string(),
        }
    }
}

impl StableDiffusionImageOptions {
    fn validate(&self) -> flow_like_types::Result<()> {
        for (name, dimension) in [("width", self.width), ("height", self.height)] {
            if dimension == 0 || dimension > i32::MAX as u32 || !dimension.is_multiple_of(8) {
                bail!(
                    "stable-diffusion.cpp image {name} must be a positive multiple of 8 within the 32-bit integer range"
                );
            }
        }
        if !(1..=100).contains(&self.steps) {
            bail!("stable-diffusion.cpp image steps must be between 1 and 100");
        }
        if !self.cfg_scale.is_finite()
            || self.cfg_scale < 0.0
            || self.cfg_scale > f64::from(f32::MAX)
        {
            bail!(
                "stable-diffusion.cpp image CFG scale must be a finite non-negative 32-bit float"
            );
        }
        if self.seed < -1 {
            bail!("stable-diffusion.cpp image seed must be -1 or a non-negative integer");
        }
        if !SAMPLERS.contains(&self.sampler.as_str()) {
            bail!(
                "Unknown stable-diffusion.cpp image sampler: {}",
                self.sampler
            );
        }
        if !SCHEDULERS.contains(&self.scheduler.as_str()) {
            bail!(
                "Unknown stable-diffusion.cpp image scheduler: {}",
                self.scheduler
            );
        }
        Ok(())
    }
}

pub(super) fn with_model_defaults(
    provider: &ModelProvider,
    options: ImageGenerationProviderOptions,
) -> flow_like_types::Result<ImageGenerationProviderOptions> {
    if provider.provider_name != PROVIDER_NAME {
        return Ok(options);
    }
    match &options {
        ImageGenerationProviderOptions::Default => {}
        ImageGenerationProviderOptions::StableDiffusion(explicit) => {
            explicit.validate()?;
            return Ok(options);
        }
        _ => bail!("stable-diffusion.cpp requires its image options or Default provider options"),
    }
    let Some(defaults) = provider
        .params
        .as_ref()
        .and_then(|params| params.get("generation_defaults"))
    else {
        return Ok(options);
    };
    let mut defaults = defaults.clone();
    if let Some(format) = defaults
        .as_object_mut()
        .and_then(|params| params.remove("output_format"))
        && format != "png"
    {
        bail!("stable-diffusion.cpp image model defaults support PNG output");
    }
    let defaults: StableDiffusionImageOptions = from_value(defaults)
        .map_err(|error| anyhow!("Invalid stable-diffusion.cpp image model defaults: {error}"))?;
    defaults.validate()?;
    Ok(ImageGenerationProviderOptions::StableDiffusion(defaults))
}

fn request_params(
    prompt: &str,
    options: &ImageGenerationProviderOptions,
) -> flow_like_types::Result<Value> {
    let defaults = StableDiffusionImageOptions::default();
    let options = match options {
        ImageGenerationProviderOptions::Default => &defaults,
        ImageGenerationProviderOptions::StableDiffusion(options) => options,
        _ => bail!("stable-diffusion.cpp requires its image options or Default provider options"),
    };
    options.validate()?;
    let mut sample_params = json!({
        "sample_steps": options.steps,
        "guidance": {"txt_cfg": options.cfg_scale},
    });
    if options.sampler != "auto" {
        sample_params["sample_method"] = json!(options.sampler);
    }
    if options.scheduler != "auto" {
        sample_params["scheduler"] = json!(options.scheduler);
    }
    Ok(json!({
        "prompt": prompt,
        "negative_prompt": options.negative_prompt.as_deref().unwrap_or_default(),
        "width": options.width,
        "height": options.height,
        "seed": options.seed,
        "batch_count": 1,
        "output_format": "png",
        "sample_params": sample_params,
    }))
}

pub(super) async fn generate_image(
    provider: &ModelProvider,
    prompt: &str,
    options: &ImageGenerationProviderOptions,
) -> flow_like_types::Result<Vec<GeneratedImage>> {
    let params = request_params(prompt, options)?;
    let config = provider
        .params
        .as_ref()
        .and_then(|params| params.get("stablediffusion"))
        .ok_or_else(|| anyhow!("stable-diffusion.cpp provider is missing its configuration"))?;
    let config: StableDiffusionConfig = from_value(config.clone())?;
    let assets = generate(
        &config,
        &GenerationRequest {
            mode: GenerationMode::Image,
            params,
        },
    )
    .await?;
    Ok(assets
        .into_iter()
        .map(|asset| GeneratedImage {
            bytes: asset.bytes,
            mime_type: Some(asset.mime_type),
            provider_metadata: asset.metadata,
        })
        .collect())
}

fn build_provider_bit(config: StableDiffusionConfig) -> flow_like_types::Result<Bit> {
    config.validate()?;
    let config = to_value(config)?;
    let mut identity = blake3::Hasher::new();
    identity.update(PROVIDER_NAME.as_bytes());
    identity.update(&to_vec(&config)?);
    let model_id = ["model_path", "diffusion_model_path", "endpoint"]
        .iter()
        .find_map(|key| config.get(*key).and_then(Value::as_str))
        .unwrap_or("stable-diffusion.cpp")
        .to_string();
    let provider = ModelProvider {
        provider_name: PROVIDER_NAME.to_string(),
        model_id: Some(model_id),
        version: None,
        api_surface: None,
        params: Some(HashMap::from([("stablediffusion".to_string(), config)])),
    };
    Ok(Bit {
        id: identity.finalize().to_hex().to_string(),
        bit_type: BitTypes::ImageGeneration,
        parameters: to_value(ImageGenerationModelProvider { provider })?,
        ..Default::default()
    })
}

#[crate::register_node]
#[derive(Default)]
pub struct BuildStableDiffusionImageNode {}

impl BuildStableDiffusionImageNode {
    pub fn new() -> Self {
        Self {}
    }
}

#[async_trait]
impl NodeLogic for BuildStableDiffusionImageNode {
    fn get_node(&self) -> Node {
        let mut node = Node::new(
            "ai_image_build_stablediffusion",
            "stable-diffusion.cpp Image Model",
            "Prepares an image provider for local model files or an existing stable-diffusion.cpp server.",
            "AI/Generative/Provider",
        );
        node.set_flowscript_name("ai.provider", "stablediffusion_image");
        node.add_icon("/flow/icons/find_model.svg");
        node.set_version(1);
        node.set_scores(option_node_scores());
        node.add_input_pin(
            "exec_in",
            "Input",
            "Prepare the provider",
            VariableType::Execution,
        );
        node.add_input_pin(
            "config",
            "Configuration",
            "Set a server endpoint, or a local model path with any required VAE and text encoders. Local paths refer to the machine executing the flow.",
            VariableType::Struct,
        )
        .set_schema::<StableDiffusionConfig>()
        .set_options(PinOptions::new().set_enforce_schema(true).build())
        .set_default_value(Some(json!(StableDiffusionConfig::default())));
        node.add_output_pin(
            "exec_out",
            "Output",
            "Provider is ready",
            VariableType::Execution,
        );
        node.add_output_pin(
            "model",
            "Model",
            "Image generation provider Bit",
            VariableType::Struct,
        )
        .set_schema::<Bit>();
        node
    }

    async fn run(&self, context: &mut ExecutionContext) -> flow_like_types::Result<()> {
        context.deactivate_exec_pin("exec_out").await?;
        let config: StableDiffusionConfig = context.evaluate_pin("config").await?;
        let bit = build_provider_bit(config)?;
        context.set_pin_value("model", json!(bit)).await?;
        context.activate_exec_pin("exec_out").await?;
        Ok(())
    }

    async fn on_update(&self, _node: &mut Node, _board: &Board) {}
}

#[crate::register_node]
#[derive(Default)]
pub struct MakeStableDiffusionImageOptionsNode {}

impl MakeStableDiffusionImageOptionsNode {
    pub fn new() -> Self {
        Self {}
    }
}

#[async_trait]
impl NodeLogic for MakeStableDiffusionImageOptionsNode {
    fn get_node(&self) -> Node {
        let mut node = Node::new(
            "ai_image_options_stablediffusion",
            "stable-diffusion.cpp Image Options",
            "Sets image dimensions, sampling controls, and seed for PNG generation.",
            "AI/Generative/Image/Options",
        );
        node.set_flowscript_name("ai.image.options", "stablediffusion");
        node.add_icon("/flow/icons/struct.svg");
        node.set_version(1);
        node.set_scores(option_node_scores());
        for (name, label, description, default) in [
            (
                "width",
                "Width",
                "Image width in pixels, a positive multiple of 8",
                512,
            ),
            (
                "height",
                "Height",
                "Image height in pixels, a positive multiple of 8",
                512,
            ),
            (
                "steps",
                "Steps",
                "Number of sampling steps, between 1 and 100",
                20,
            ),
            (
                "seed",
                "Seed",
                "Use -1 for randomness, or zero and above for a reproducible seed",
                -1,
            ),
        ] {
            node.add_input_pin(name, label, description, VariableType::Integer)
                .set_default_value(Some(json!(default)));
        }
        node.add_input_pin(
            "cfg_scale",
            "CFG Scale",
            "Text guidance strength, a finite non-negative 32-bit float",
            VariableType::Float,
        )
        .set_default_value(Some(json!(7.0)));
        node.add_input_pin(
            "negative_prompt",
            "Negative Prompt",
            "Content to discourage in the generated image",
            VariableType::String,
        )
        .set_default_value(Some(json!("")));
        add_select_pin(
            &mut node,
            "sampler",
            "Sampler",
            "Sampling method; auto uses the model default",
            SAMPLERS,
            "auto",
        );
        add_select_pin(
            &mut node,
            "scheduler",
            "Scheduler",
            "Noise schedule; auto uses the model default",
            SCHEDULERS,
            "auto",
        );
        add_options_output(&mut node);
        node
    }

    async fn run(&self, context: &mut ExecutionContext) -> flow_like_types::Result<()> {
        let negative_prompt: String = context.evaluate_pin("negative_prompt").await?;
        let options = StableDiffusionImageOptions {
            width: context.evaluate_pin("width").await?,
            height: context.evaluate_pin("height").await?,
            steps: context.evaluate_pin("steps").await?,
            cfg_scale: context.evaluate_pin("cfg_scale").await?,
            negative_prompt: (!negative_prompt.trim().is_empty()).then_some(negative_prompt),
            seed: context.evaluate_pin("seed").await?,
            sampler: context.evaluate_pin("sampler").await?,
            scheduler: context.evaluate_pin("scheduler").await?,
        };
        options.validate()?;
        context
            .set_pin_value(
                "options",
                json!(ImageGenerationProviderOptions::StableDiffusion(options)),
            )
            .await?;
        Ok(())
    }

    async fn on_update(&self, _node: &mut Node, _board: &Board) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_defaults_apply_only_to_default_local_options() {
        let mut provider = ModelProvider {
            provider_name: PROVIDER_NAME.into(),
            model_id: None,
            version: None,
            api_surface: None,
            params: Some(HashMap::from([(
                "generation_defaults".into(),
                json!({"width":1024,"height":768,"steps":4,
                    "cfg_scale":1.0,"sampler":"euler","scheduler":"simple","output_format":"png"}),
            )])),
        };
        let options =
            with_model_defaults(&provider, ImageGenerationProviderOptions::Default).unwrap();
        let params = request_params("A landscape", &options).unwrap();
        assert_eq!(params["width"], 1024);
        assert_eq!(params["height"], 768);
        assert_eq!(params["sample_params"]["sample_steps"], 4);
        assert_eq!(params["sample_params"]["guidance"]["txt_cfg"], 1.0);
        assert_eq!(params["sample_params"]["sample_method"], "euler");
        assert_eq!(params["seed"], -1);
        let explicit =
            ImageGenerationProviderOptions::StableDiffusion(StableDiffusionImageOptions::default());
        let options = with_model_defaults(&provider, explicit).unwrap();
        assert_eq!(
            request_params("A landscape", &options).unwrap()["width"],
            512
        );
        provider.provider_name = PROVIDER_OPENAI.into();
        assert!(matches!(
            with_model_defaults(&provider, ImageGenerationProviderOptions::Default).unwrap(),
            ImageGenerationProviderOptions::Default
        ));
    }

    #[test]
    fn invalid_model_defaults_fail_before_generation() {
        for defaults in [
            json!({"width":513}),
            json!({"steps":101}),
            json!({"video_frames":33}),
            json!({"output_format":"webp"}),
            json!(null),
        ] {
            let provider = ModelProvider {
                provider_name: PROVIDER_NAME.into(),
                model_id: None,
                version: None,
                api_surface: None,
                params: Some(HashMap::from([("generation_defaults".into(), defaults)])),
            };
            assert!(
                with_model_defaults(&provider, ImageGenerationProviderOptions::Default).is_err()
            );
        }
    }

    #[test]
    fn invalid_explicit_options_fail_before_weight_resolution() {
        let provider = ModelProvider {
            provider_name: PROVIDER_NAME.into(),
            model_id: None,
            version: None,
            api_surface: None,
            params: None,
        };
        let invalid =
            ImageGenerationProviderOptions::StableDiffusion(StableDiffusionImageOptions {
                width: 513,
                ..Default::default()
            });
        assert!(with_model_defaults(&provider, invalid).is_err());
        let foreign = ImageGenerationProviderOptions::OpenAi(OpenAiImageOptions::default());
        assert!(with_model_defaults(&provider, foreign.clone()).is_err());
        let cloud_provider = ModelProvider {
            provider_name: PROVIDER_OPENAI.into(),
            ..provider
        };
        assert!(matches!(
            with_model_defaults(&cloud_provider, foreign).unwrap(),
            ImageGenerationProviderOptions::OpenAi(_)
        ));
    }

    #[test]
    fn sampling_boundaries_match_native_server_limits() {
        for steps in [1, 100] {
            StableDiffusionImageOptions {
                steps,
                ..Default::default()
            }
            .validate()
            .unwrap();
        }
        for steps in [0, 101, u32::MAX] {
            assert!(
                StableDiffusionImageOptions {
                    steps,
                    ..Default::default()
                }
                .validate()
                .is_err()
            );
        }
        for cfg_scale in [0.0, f64::from(f32::MAX)] {
            StableDiffusionImageOptions {
                cfg_scale,
                ..Default::default()
            }
            .validate()
            .unwrap();
        }
        for cfg_scale in [
            f64::from(f32::MAX) * 2.0,
            f64::MAX,
            f64::INFINITY,
            f64::NAN,
            -1.0,
        ] {
            assert!(
                StableDiffusionImageOptions {
                    cfg_scale,
                    ..Default::default()
                }
                .validate()
                .is_err()
            );
        }
    }

    #[test]
    fn request_uses_native_sampling_fields_and_preserves_seed_zero() {
        let options = StableDiffusionImageOptions {
            width: 768,
            height: 1024,
            steps: 30,
            cfg_scale: 4.5,
            negative_prompt: Some("blur".to_string()),
            seed: 0,
            sampler: "dpm++2m".to_string(),
            scheduler: "karras".to_string(),
        };
        let params = request_params(
            "a bird",
            &ImageGenerationProviderOptions::StableDiffusion(options),
        )
        .unwrap();
        assert_eq!(
            params,
            json!({
                "prompt": "a bird", "negative_prompt": "blur", "width": 768, "height": 1024,
                "seed": 0, "batch_count": 1, "output_format": "png",
                "sample_params": {"sample_steps": 30, "sample_method": "dpm++2m", "scheduler": "karras", "guidance": {"txt_cfg": 4.5}},
            })
        );
    }

    #[test]
    fn default_options_keep_model_sampler_and_scheduler() {
        let params = request_params("a bird", &ImageGenerationProviderOptions::Default).unwrap();
        assert_eq!(params["seed"], -1);
        assert!(params["sample_params"].get("sample_method").is_none());
        assert!(params["sample_params"].get("scheduler").is_none());
        assert_eq!(params["output_format"], "png");
    }

    #[test]
    fn invalid_options_and_foreign_provider_options_are_rejected() {
        let invalid = [
            StableDiffusionImageOptions {
                width: 0,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                height: 511,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                width: u32::MAX - 7,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                steps: 0,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                steps: u32::MAX,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                cfg_scale: f64::NAN,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                cfg_scale: -1.0,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                seed: -2,
                ..Default::default()
            },
            StableDiffusionImageOptions {
                sampler: "unknown".into(),
                ..Default::default()
            },
            StableDiffusionImageOptions {
                scheduler: "unknown".into(),
                ..Default::default()
            },
        ];
        for options in invalid {
            assert!(
                request_params(
                    "a bird",
                    &ImageGenerationProviderOptions::StableDiffusion(options)
                )
                .is_err()
            );
        }
        assert!(
            request_params(
                "a bird",
                &ImageGenerationProviderOptions::OpenAi(Default::default())
            )
            .is_err()
        );
        assert!(
            from_value::<ImageGenerationProviderOptions>(
                json!({"provider": "stable_diffusion", "options": {"steps": "invalid"}})
            )
            .is_err()
        );
    }

    #[test]
    fn options_roundtrip_and_schema_include_local_provider() {
        let options = ImageGenerationProviderOptions::StableDiffusion(Default::default());
        let value = to_value(&options).unwrap();
        assert_eq!(value["provider"], "stable_diffusion");
        assert_eq!(
            from_value::<ImageGenerationProviderOptions>(value).unwrap(),
            options
        );
        let schema = to_value(schemars::schema_for!(ImageGenerationProviderOptions)).unwrap();
        assert!(schema.to_string().contains("StableDiffusionImageOptions"));
    }

    #[test]
    fn provider_bit_has_stable_identity_and_generation_type() {
        let config: StableDiffusionConfig =
            from_value(json!({"endpoint": "http://127.0.0.1:1234"})).unwrap();
        let first = build_provider_bit(config.clone()).unwrap();
        let second = build_provider_bit(config).unwrap();
        assert_eq!(first.id, second.id);
        assert_eq!(first.bit_type, BitTypes::ImageGeneration);
        let provider = provider_from_bit(&first).unwrap();
        assert_eq!(provider.provider_name, PROVIDER_NAME);
        assert_eq!(provider.model_id.as_deref(), Some("http://127.0.0.1:1234"));
        assert_eq!(
            provider.params.unwrap()["stablediffusion"]["endpoint"],
            "http://127.0.0.1:1234"
        );
        let other =
            build_provider_bit(from_value(json!({"endpoint": "http://127.0.0.1:1235"})).unwrap())
                .unwrap();
        assert_ne!(first.id, other.id);
    }
}
