#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

rand() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$((n/2))"
  else
    python3 - <<PY
import secrets
print(secrets.token_hex(${n}//2))
PY
  fi
}

ensure_kv() {
  local key="$1"
  local value="$2"

  if [[ -f "$ENV_FILE" ]] && grep -qE "^${key}=" "$ENV_FILE"; then
    return 0
  fi

  echo "${key}=${value}" >> "$ENV_FILE"
}

mkdir -p "$ROOT_DIR"

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<'EOF'
# Generated by scripts/dev-bootstrap.sh
EOF
fi

# Postgres defaults (generate password if missing)
ensure_kv "POSTGRES_USER" "flowlike"
ensure_kv "POSTGRES_DB" "flowlike"
ensure_kv "POSTGRES_PASSWORD" "$(rand 32)"
ensure_kv "POSTGRES_HOST" "localhost"
ensure_kv "POSTGRES_PORT" "5432"

# Derived URLs
# (safe to overwrite each run)
POSTGRES_USER="$(grep -E '^POSTGRES_USER=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
POSTGRES_PASSWORD="$(grep -E '^POSTGRES_PASSWORD=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
POSTGRES_DB="$(grep -E '^POSTGRES_DB=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
POSTGRES_HOST="$(grep -E '^POSTGRES_HOST=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
POSTGRES_PORT="$(grep -E '^POSTGRES_PORT=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"

# remove any existing DATABASE_URL line(s)
perl -0777 -i -pe 's/^DATABASE_URL=.*\n//mg' "$ENV_FILE" || true

echo "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" >> "$ENV_FILE"

echo "✅ Wrote/updated $ENV_FILE"
echo "Next: docker compose up -d"
