version = 1

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["apps/backend/docker/api/Dockerfile"]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "rustfmt"