version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "browser"]
  plugins = ["react"]
  dependency_file_paths = [
    "apps/desktop/",
    "apps/docs/",
    "packages/ui"
  ]
  dialect = "typescript"

[[analyzers]]
name = "rust"
enabled = true

[[excludes]]
paths = ["**/node_modules/", "dist/", "build/", "**/*.min.js"]