-- Aurora DSQL migration "file_accounting_retention_index"
-- Generated by packages/api/scripts/dsql-migration.ts (--from-schema prisma/migrations-dsql/schema.snapshot.prisma) and rewritten by dsql-lint 0.2.17.
-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,
-- waits for the async index/validation jobs and records the migration in _prisma_migrations.
-- tables=0 indexes=1 foreign_keys=0 validations=0 statements=1
CREATE INDEX ASYNC "FileAccountingObject_size_updatedAt_idx" ON "FileAccountingObject"("size", "updatedAt");
