[package]
name = "aws-executor"
version = "0.1.0"
edition = "2024"
description = "Flow-Like AWS Lambda Executor with Streaming Support"

[dependencies]
flow-like-catalog = { workspace = true, default-features = false, features = ["server-local-ml"] }
flow-like-executor = { workspace = true, features = ["server-local-ml", "channel-aws"] }
flow-like-types.workspace = true
lambda_http.workspace = true
mimalloc.workspace = true
axum.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
