# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def get_node_id() -> str:
    raise NotImplementedError
def get_run_id() -> str:
    raise NotImplementedError
def time_now() -> int:
    raise NotImplementedError
def random() -> float:
    raise NotImplementedError
def is_streaming() -> bool:
    raise NotImplementedError
def get_log_level() -> int:
    raise NotImplementedError
