# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def get_input(name: str) -> Optional[str]:
    raise NotImplementedError
def set_output(name: str, value: str) -> None:
    raise NotImplementedError
def activate_exec(name: str) -> None:
    raise NotImplementedError
