import type { HomeWidgetPreset, IHomeLayout, IHomeWidget } from "./types";

const preset = (
	id: string,
	name: string,
	description: string,
	category: HomeWidgetPreset["category"],
	icon: string,
	type: string,
	config: Record<string, unknown> = {},
	columns = 6,
	rows = 3,
	variant = "card",
	accent = "neutral",
): HomeWidgetPreset => ({
	id,
	name,
	description,
	category,
	icon,
	type,
	config: {
		...config,
		...(type === "app-collection"
			? {
					rendering: ["list", "icons", "editorial", "carousel"].includes(
						variant,
					)
						? variant
						: "standard",
				}
			: type === "models"
				? { rendering: "standard" }
				: {}),
	},
	columns,
	rows,
	variant:
		type === "app-collection" &&
		!["card", "borderless", "tinted"].includes(variant)
			? "card"
			: variant,
	accent,
});
const data = (
	id: string,
	name: string,
	description: string,
	icon: string,
	visualization: string,
	mode = "aggregate",
	columns = 6,
	rows = 4,
) =>
	preset(
		id,
		name,
		description,
		"data",
		icon,
		"data",
		{ visualization, mode },
		columns,
		rows,
	);

export const HOME_WIDGET_PRESETS: HomeWidgetPreset[] = [
	preset(
		"workspace-strip",
		"Workspace summary",
		"Keep your profile and account activity within reach in a compact summary.",
		"activity",
		"activity",
		"workspace-pulse",
		{ mode: "strip", days: 7, showAttention: true },
		12,
		1,
		"borderless",
		"violet",
	),
	preset(
		"section-heading",
		"Section heading",
		"Give a group of widgets a clear introduction and a useful destination.",
		"content",
		"panel",
		"section-heading",
		{ href: "", linkLabel: "" },
		12,
		1,
		"borderless",
	),
	preset(
		"workspace-attention",
		"Needs attention",
		"Review flagged execution records with links back to your apps.",
		"activity",
		"activity",
		"workspace-pulse",
		{ mode: "attention", days: 7, showAttention: true },
		4,
		3,
	),
	preset(
		"app-spotlight",
		"App spotlight",
		"Give one app a bold feature with artwork, details, and a clear way in.",
		"apps",
		"sparkles",
		"app-spotlight",
		{ source: "new", eyebrow: "IN THE SPOTLIGHT" },
		12,
		4,
		"tinted",
		"violet",
	),
	preset(
		"app-ranking",
		"Community favorites",
		"A compact numbered list of apps ranked by community ratings.",
		"apps",
		"trending",
		"app-ranking",
		{ source: "popular", limit: 6 },
		4,
		5,
	),
	preset(
		"app-collection-feature",
		"A collection worth exploring",
		"Put a curated group of apps in a bold, colorful feature.",
		"apps",
		"layers",
		"app-collection-feature",
		{
			source: "new",
			category: "Productivity",
			limit: 3,
			eyebrow: "THE EVERYDAY, UPGRADED",
			headline: "Less busywork. More possibility.",
		},
		4,
		3,
		"solid",
		"orange",
	),
	preset(
		"model-spotlight",
		"Model spotlight",
		"Put a capable model in focus, with its real details and profile controls.",
		"apps",
		"brain",
		"model-spotlight",
		{ source: "explore", eyebrow: "MEET YOUR NEXT MODEL" },
		4,
		3,
	),
	preset(
		"workspace-pulse",
		"Your workspace at a glance",
		"See your apps, recent activity, and what needs a closer look.",
		"activity",
		"activity",
		"workspace-pulse",
		{ days: 7, showAttention: true },
		4,
		4,
		"card",
		"violet",
	),
	preset(
		"flowpilot-bar",
		"Ask FlowPilot",
		"A prompt bar for ideas, questions, and getting work done.",
		"assistant",
		"sparkles",
		"flowpilot",
		{ mode: "bar" },
		12,
		1,
		"borderless",
		"violet",
	),
	preset(
		"flowpilot-hero",
		"FlowPilot hero",
		"Give your assistant room to welcome you.",
		"assistant",
		"sparkles",
		"flowpilot",
		{ mode: "hero" },
		12,
		4,
		"borderless",
	),
	preset(
		"flowpilot-card",
		"FlowPilot composer",
		"A focused space to describe your next task.",
		"assistant",
		"message",
		"flowpilot",
		{ mode: "card" },
		6,
		3,
		"tinted",
		"violet",
	),
	preset(
		"flowpilot-orb",
		"FlowPilot orb",
		"A small, familiar entry point to your assistant.",
		"assistant",
		"sparkles",
		"flowpilot",
		{ mode: "orb" },
		3,
		2,
		"borderless",
		"violet",
	),
	preset(
		"app-embed",
		"Embed an app",
		"Use an app's landing page, a specific page, or a chat right here.",
		"apps",
		"app",
		"app-embed",
		{ target: "landing", appId: "", route: "/", query: "" },
		8,
		6,
	),
	preset(
		"app-chat",
		"App chat",
		"Keep a conversation with an app on your home.",
		"apps",
		"message",
		"app-embed",
		{ target: "event", appId: "", eventId: "", query: "" },
		6,
		6,
	),
	preset(
		"app-page",
		"App page",
		"Pin a page with its own route and query parameters.",
		"apps",
		"panel",
		"app-embed",
		{ target: "route", appId: "", route: "/", query: "" },
		8,
		6,
	),
	preset(
		"my-apps",
		"Your apps",
		"Your library, arranged just how you like it.",
		"apps",
		"grid",
		"app-collection",
		{ source: "library", limit: 6 },
		12,
		3,
		"grid",
	),
	preset(
		"recent-apps",
		"Recently updated",
		"Pick up apps that have changed recently.",
		"apps",
		"clock",
		"app-collection",
		{ source: "recent", limit: 6 },
		12,
		2,
		"grid",
	),
	preset(
		"favorite-apps",
		"Favorite apps",
		"The apps you have marked as favorites in this profile.",
		"apps",
		"star",
		"app-collection",
		{ source: "favorites", limit: 8 },
		6,
		3,
		"icons",
	),
	preset(
		"app-collection",
		"App collection",
		"Bring a handpicked set of apps together around a task.",
		"apps",
		"layers",
		"app-collection",
		{ source: "manual", appIds: [], limit: 8 },
		6,
		4,
		"grid",
	),
	preset(
		"app-directory",
		"App directory",
		"An informative, compact list of apps and their purpose.",
		"apps",
		"list",
		"app-collection",
		{ source: "library", limit: 12 },
		6,
		4,
		"list",
	),
	preset(
		"featured-collection",
		"Featured collection",
		"An editorial presentation for a collection worth exploring.",
		"apps",
		"panel",
		"app-collection",
		{ source: "manual", appIds: [], limit: 4 },
		8,
		4,
		"editorial",
		"orange",
	),
	preset(
		"app-shelf",
		"App shelf",
		"Browse a collection in a horizontal carousel.",
		"apps",
		"layers",
		"app-collection",
		{ source: "new", limit: 8 },
		12,
		3,
		"carousel",
	),
	preset(
		"new-apps",
		"New apps",
		"Discover the latest additions to the community.",
		"apps",
		"compass",
		"app-collection",
		{ source: "new", limit: 6 },
		8,
		4,
		"grid",
	),
	preset(
		"popular-apps",
		"Popular apps",
		"Explore popular apps, optionally filtered by topic.",
		"apps",
		"trending",
		"app-collection",
		{ source: "popular", limit: 6 },
		4,
		4,
		"list",
	),
	preset(
		"categories",
		"Explore categories",
		"Find apps by the kind of work you want to do.",
		"apps",
		"compass",
		"categories",
		{},
		12,
		2,
		"borderless",
	),
	preset(
		"packages",
		"Explore packages",
		"Find packages and nodes to extend your apps.",
		"apps",
		"package",
		"packages",
		{ query: "", limit: 6, rendering: "standard" },
		4,
		4,
	),
	preset(
		"models",
		"Model collection",
		"Bring useful models into view.",
		"apps",
		"brain",
		"models",
		{ query: "", limit: 4 },
		6,
		4,
	),
	preset(
		"greeting",
		"Welcome",
		"A personal greeting and today's date.",
		"content",
		"sun",
		"greeting",
		{},
		12,
		1,
		"borderless",
	),
	preset(
		"quick-actions",
		"Quick actions",
		"Create an app, import a flow, or explore your library.",
		"content",
		"zap",
		"quick-actions",
		{ actions: ["create", "import", "library", "packages"] },
		12,
		2,
		"borderless",
	),
	preset(
		"quick-links",
		"Links and destinations",
		"Useful pages, app destinations, and external resources.",
		"content",
		"link",
		"quick-links",
		{
			links: [
				{
					title: "Explore apps",
					description: "Find your next useful app",
					href: "/store/explore/apps",
				},
			],
		},
		4,
		3,
	),
	preset(
		"info",
		"Information panel",
		"Make space for context, instructions, or a helpful explanation.",
		"content",
		"info",
		"information",
		{
			mode: "markdown",
			body: "Make this space your own. Add context, useful links, or a guide for your team.",
		},
		6,
		3,
	),
	preset(
		"notes",
		"Notes",
		"Keep a thought, plan, or reference close at hand.",
		"content",
		"file",
		"information",
		{ mode: "markdown", body: "" },
		4,
		3,
		"tinted",
		"amber",
	),
	preset(
		"banner",
		"Feature banner",
		"Highlight a message with a prominent visual treatment.",
		"content",
		"panel",
		"information",
		{ mode: "banner", body: "A space for what matters next." },
		8,
		3,
		"tinted",
		"orange",
	),
	preset(
		"announcement",
		"Announcement",
		"Share an update, release, or important destination.",
		"content",
		"megaphone",
		"information",
		{ mode: "announcement", body: "Add your announcement here." },
		6,
		2,
		"tinted",
		"blue",
	),
	preset(
		"faq",
		"Questions and answers",
		"Make common questions easy to answer.",
		"content",
		"help",
		"information",
		{
			mode: "faq",
			items: [
				{
					title: "Where should I start?",
					body: "Add guidance and useful links for this profile.",
				},
			],
		},
		6,
		3,
	),
	preset(
		"checklist",
		"Checklist",
		"Keep a plan or getting-started guide in view.",
		"content",
		"check",
		"information",
		{
			mode: "checklist",
			items: [{ title: "Add your first step", checked: false }],
		},
		4,
		3,
	),
	preset(
		"countdown",
		"Milestone",
		"An upcoming date, deadline, or moment to look forward to.",
		"content",
		"calendar",
		"information",
		{ mode: "countdown", date: "" },
		4,
		2,
		"tinted",
		"violet",
	),
	preset(
		"notifications",
		"Your inbox",
		"Your personal notifications and links to relevant work.",
		"activity",
		"bell",
		"notifications",
		{},
		6,
		4,
	),
	preset(
		"needs-attention",
		"Needs your attention",
		"Unread workflow notifications and recent executions with error severity.",
		"activity",
		"attention",
		"needs-attention",
		{},
		6,
		5,
		"card",
		"orange",
	),
	preset(
		"run-stats",
		"Your run statistics",
		"A summary of execution and AI usage for your account.",
		"activity",
		"activity",
		"run-stats",
		{},
		6,
		2,
	),
	preset(
		"run-activity",
		"Your run activity",
		"Review recorded execution activity by day, with error severity highlighted.",
		"activity",
		"bar",
		"run-activity",
		{ days: 7 },
		8,
		4,
	),
	preset(
		"executions-by-app",
		"Executions by app",
		"See which apps appear most often in your recent execution records.",
		"activity",
		"activity",
		"executions-by-app",
		{ days: 7, limit: 8 },
		4,
		4,
	),
	preset(
		"ai-usage",
		"Your AI usage",
		"Recorded AI and embedding requests with their reported costs.",
		"activity",
		"brain",
		"ai-usage",
		{},
		6,
		3,
	),

	preset(
		"recent-runs",
		"Your recent runs",
		"Recent execution outcomes with links to their apps.",
		"activity",
		"activity",
		"recent-runs",
		{ limit: 8 },
		6,
		4,
	),
	preset(
		"schedules",
		"Scheduled next",
		"Upcoming scheduled events in your apps.",
		"activity",
		"calendar",
		"schedules",
		{ limit: 8 },
		6,
		4,
	),
	preset(
		"resource-directory",
		"Resource directory",
		"A curated hub of guides, app pages, and useful destinations.",
		"content",
		"link",
		"information",
		{ mode: "resources", items: [] },
		8,
		4,
	),
	preset(
		"guided-steps",
		"Guided steps",
		"Explain a process with numbered steps and links to the tools for each one.",
		"content",
		"check",
		"information",
		{ mode: "steps", items: [] },
		6,
		4,
	),
	preset(
		"updates-feed",
		"Updates and changelog",
		"Publish a series of updates with dates, labels, and useful links.",
		"content",
		"megaphone",
		"information",
		{ mode: "feed", items: [] },
		6,
		4,
	),
	preset(
		"editorial-story",
		"Editorial story",
		"Tell a story with an image, rich text, and a call to action.",
		"content",
		"file",
		"information",
		{ mode: "story", body: "", imageUrl: "", imageAlt: "", actionHref: "" },
		8,
		4,
		"tinted",
		"violet",
	),
	preset(
		"image-card",
		"Image and caption",
		"Bring a diagram, illustration, or visual reference onto your home.",
		"content",
		"panel",
		"information",
		{ mode: "image", body: "", imageUrl: "", imageAlt: "" },
		6,
		4,
	),
	preset(
		"quote-card",
		"Quote",
		"Keep a useful quotation and its attribution in view.",
		"content",
		"message",
		"information",
		{ mode: "quote", body: "", attribution: "" },
		4,
		3,
		"tinted",
		"blue",
	),
	preset(
		"facts-card",
		"Facts and highlights",
		"Give key facts, definitions, and context their own cards.",
		"content",
		"info",
		"information",
		{ mode: "facts", items: [] },
		8,
		3,
	),
	preset(
		"app-toolkit",
		"App toolkit",
		"Hand-pick a compact group of apps for a particular task or team.",
		"apps",
		"layers",
		"app-collection",
		{ source: "manual", appIds: [], limit: 12 },
		6,
		3,
		"icons",
	),
	preset(
		"topic-apps",
		"Apps by topic",
		"Build a living collection filtered by category or tag.",
		"apps",
		"compass",
		"app-collection",
		{ source: "new", category: "", tag: "", limit: 8 },
		8,
		4,
		"grid",
	),
	preset(
		"app-destinations",
		"App page directory",
		"Link directly to app pages, chats, or bookmarked query views.",
		"apps",
		"link",
		"quick-links",
		{ links: [] },
		6,
		3,
		"grid",
	),
	data(
		"target-progress",
		"Progress to target",
		"Track an aggregate against a target you set.",
		"trending",
		"progress",
		"aggregate",
		4,
		2,
	),
	data(
		"target-gauge",
		"Target gauge",
		"Read progress toward a target at a glance.",
		"pie",
		"gauge",
		"aggregate",
		4,
		3,
	),
	data(
		"target-bullet",
		"Bullet chart",
		"Compare a measure with a target on a compact scale.",
		"bar",
		"bullet",
		"aggregate",
		6,
		2,
	),
	data(
		"percent-stacked",
		"100% stacked chart",
		"Compare the composition of groups as percentages.",
		"bar",
		"percentstacked",
	),
	data(
		"box-plot",
		"Box plot",
		"Compare ranges, medians, and approximate quartiles.",
		"bar",
		"boxplot",
	),
	data(
		"funnel",
		"Funnel",
		"Compare volumes across ordered stages.",
		"trending",
		"funnel",
	),
	data(
		"waterfall",
		"Waterfall",
		"Show how positive and negative changes build a total.",
		"bar",
		"waterfall",
	),
	data(
		"sankey",
		"Sankey",
		"See weighted connections between two sets of categories.",
		"network",
		"sankey",
		"aggregate",
		8,
		5,
	),
	data(
		"pivot-table",
		"Pivot table",
		"Compare an aggregate across row and column groups.",
		"table",
		"pivot",
		"aggregate",
		8,
		4,
	),
	data(
		"record-timeline",
		"Record timeline",
		"Place dated records in chronological order.",
		"clock",
		"timeline",
		"records",
	),
	data(
		"record-calendar",
		"Record calendar",
		"See dated records in a monthly calendar.",
		"calendar",
		"recordcalendar",
		"records",
		8,
		5,
	),
	data(
		"object-comparison",
		"Record comparison",
		"Compare the fields of up to ten records side by side.",
		"layers",
		"comparison",
		"records",
		8,
		4,
	),

	data(
		"metric",
		"Metric",
		"A count, total, average, or other measure from your data.",
		"hash",
		"stat",
		"aggregate",
		3,
		2,
	),
	data(
		"metric-strip",
		"Metric strip",
		"Several related measures in one view.",
		"hash",
		"metricstrip",
		"aggregate",
		12,
		2,
	),
	data(
		"bar-chart",
		"Bar chart",
		"Compare categories, teams, or periods.",
		"bar",
		"bar",
	),
	data(
		"ranked-bars",
		"Ranked bars",
		"Rank categories with horizontal bars and readable labels.",
		"bar",
		"horizontal",
	),
	data(
		"stacked-chart",
		"Stacked chart",
		"See how categories contribute to a total.",
		"bar",
		"stacked",
	),
	data(
		"line-chart",
		"Line chart",
		"Follow a measure over time.",
		"line",
		"line",
	),
	data(
		"area-chart",
		"Area chart",
		"Understand changes in volume over time.",
		"line",
		"area",
	),
	data(
		"donut-chart",
		"Donut chart",
		"Compare each category's share of a total.",
		"pie",
		"donut",
		"aggregate",
		4,
		4,
	),
	data(
		"pie-chart",
		"Pie chart",
		"A compact breakdown of a few categories.",
		"pie",
		"pie",
		"aggregate",
		4,
		4,
	),
	data(
		"scatter-chart",
		"Scatter plot",
		"Explore the relationship between numeric measures.",
		"scatter",
		"scatter",
		"records",
	),
	data(
		"histogram",
		"Histogram",
		"Inspect the distribution of numeric values.",
		"bar",
		"histogram",
		"aggregate",
	),
	data(
		"heatmap",
		"Heatmap",
		"Spot patterns across two dimensions.",
		"grid",
		"heatmap",
	),
	data(
		"calendar-heatmap",
		"Activity calendar",
		"See daily activity across a date range.",
		"calendar",
		"calendar",
	),
	data(
		"treemap",
		"Treemap",
		"Show how categories contribute to a whole.",
		"grid",
		"treemap",
	),
	data(
		"data-table",
		"Data table",
		"Choose columns, filter records, and explore the results.",
		"table",
		"table",
		"records",
		8,
		5,
	),
	data(
		"record-list",
		"Record list",
		"A compact list from a table or ontology.",
		"list",
		"list",
		"records",
	),
	data(
		"record-gallery",
		"Record gallery",
		"Present records as a collection of cards.",
		"grid",
		"cards",
		"records",
		8,
		4,
	),
	data(
		"kanban",
		"Status board",
		"Group records by a status or category.",
		"panel",
		"kanban",
		"records",
		12,
		5,
	),
	data(
		"object-card",
		"Object details",
		"Keep an important record and its properties in view.",
		"file",
		"record",
		"records",
		4,
		3,
	),
	data(
		"relationship-graph",
		"Relationship graph",
		"Explore connections from source and target fields.",
		"network",
		"graph",
		"records",
		8,
		5,
	),
];

export function createHomeWidget(presetId: string): IHomeWidget {
	const item =
		HOME_WIDGET_PRESETS.find((entry) => entry.id === presetId) ??
		HOME_WIDGET_PRESETS[0];
	return {
		id: crypto.randomUUID(),
		type: item.type,
		title: item.name,
		description: "",
		size: { columns: item.columns, rows: item.rows },
		appearance: {
			variant: item.variant ?? "card",
			accent: item.accent ?? "neutral",
		},
		config: structuredClone(item.config),
	};
}

export function createDefaultHomeLayout(): IHomeLayout {
	const defaults: {
		preset: string;
		id?: string;
		title?: string;
		description?: string;
		config?: Record<string, unknown>;
		columns?: number;
		variant?: string;
	}[] = [
		{ preset: "greeting", config: { mode: "masthead" } },
		{
			preset: "flowpilot-bar",
			config: {
				suggestions: true,
				emphasis: true,
				placeholder:
					"Ask FlowPilot to build an app, find a node, or work through an idea…",
			},
		},
		{
			preset: "quick-actions",
			config: {
				actions: ["create", "import", "library", "packages"],
				layout: "toolbar",
			},
		},
		{
			preset: "recent-apps",
			title: "Your apps",
			description: "Recently updated in this profile.",
			config: {
				rendering: "compact",
				limit: 6,
				showUpdated: true,
				maxColumns: 2,
			},
			columns: 8,
		},
		{
			preset: "workspace-pulse",
			title: "Workspace overview",
			config: { days: 7, showAttention: true },
			columns: 4,
		},
		{
			preset: "section-heading",
			id: "discover-heading",
			title: "Explore and build",
			description: "Apps and building blocks from your connected catalog.",
			config: { href: "/store/explore/apps", linkLabel: "Explore apps" },
		},
		{ preset: "app-spotlight", columns: 8, config: { mode: "compact" } },
		{
			preset: "resource-directory",
			title: "Make this home yours",
			columns: 4,
			config: {
				layout: "list",
				items: [
					{
						id: "embed",
						title: "Keep an app open here",
						body: "In Customize, add Embed an app. Choose a page or chat, then add query parameters if needed.",
					},
					{
						id: "data",
						title: "Turn data into a daily view",
						body: "In Customize, add a data widget. Choose a table or ontology, then set your chart, measures, and filters.",
					},
					{
						id: "learn",
						title: "Build your first flow",
						body: "Follow a course from your first node to a working app.",
						href: "/learn",
					},
				],
			},
		},
		{
			preset: "packages",
			title: "Extend your flows",
			description: "Packages add nodes, tools, and integrations.",
			config: { limit: 2, rendering: "compact" },
			columns: 8,
		},
		{
			preset: "model-spotlight",
			config: {
				source: "manual",
				modelId: "s14lujkm2gut2mwg0zo3imxv",
				modelHub: "api.flow-like.com",
			},
		},
		{
			preset: "categories",
			title: "Browse apps by category",
			config: {
				categories: [
					"Productivity",
					"Business",
					"Utilities",
					"Communication",
					"Education",
					"Entertainment",
					"Games",
				],
				rendering: "chips",
			},
		},
	];
	return {
		version: 1,
		title: "Your workspace, with room for inspiration.",
		widgets: defaults.map(
			({ preset, id, title, description, config, columns, variant }) => {
				const widget = createHomeWidget(preset);
				return {
					...widget,
					id: `default-${id ?? preset}`,
					title: title ?? widget.title,
					description: description ?? widget.description,
					appearance: {
						...widget.appearance,
						variant: variant ?? widget.appearance.variant,
					},
					config: { ...widget.config, ...config },
					size: {
						...widget.size,
						columns: columns ?? widget.size.columns,
						heightMode: "auto",
					},
				};
			},
		),
	};
}

export function getHomeWidgetPreset(widget: IHomeWidget) {
	const candidates = HOME_WIDGET_PRESETS.filter(
		(item) => item.type === widget.type,
	);
	const key =
		widget.type === "data"
			? "visualization"
			: widget.type === "app-embed"
				? "target"
				: widget.type === "app-collection"
					? "source"
					: "mode";
	const matching = candidates.filter(
		(item) => item.config[key] === widget.config[key],
	);
	return (
		matching.find((item) => item.variant === widget.appearance.variant) ??
		matching[0] ??
		candidates[0]
	);
}
