import {
	Activity,
	AlertCircle,
	Bell,
	Brain,
	CalendarDays,
	ChartColumn,
	ChartLine,
	ChartNoAxesCombined,
	ChartPie,
	ChartScatter,
	CheckSquare,
	Clock,
	Compass,
	FileText,
	Grid2X2,
	Hash,
	HelpCircle,
	Info,
	Layers,
	Link,
	List,
	Megaphone,
	MessageSquare,
	Network,
	Package,
	PanelsTopLeft,
	Sparkles,
	Star,
	Sun,
	Table2,
	Zap,
} from "lucide-react";

const icons = {
	activity: Activity,
	attention: AlertCircle,
	bell: Bell,
	brain: Brain,
	calendar: CalendarDays,
	bar: ChartColumn,
	line: ChartLine,
	pie: ChartPie,
	scatter: ChartScatter,
	check: CheckSquare,
	clock: Clock,
	compass: Compass,
	file: FileText,
	grid: Grid2X2,
	hash: Hash,
	help: HelpCircle,
	info: Info,
	layers: Layers,
	link: Link,
	list: List,
	megaphone: Megaphone,
	message: MessageSquare,
	network: Network,
	package: Package,
	panel: PanelsTopLeft,
	app: PanelsTopLeft,
	sparkles: Sparkles,
	star: Star,
	sun: Sun,
	table: Table2,
	trending: ChartNoAxesCombined,
	zap: Zap,
};

export function HomeWidgetIcon({
	name,
	className,
}: { name?: string; className?: string }) {
	const Icon = icons[name as keyof typeof icons] ?? PanelsTopLeft;
	return <Icon className={className} aria-hidden="true" />;
}
