use flow_like::flow::node::NodeLogic;
use std::sync::Arc;

pub mod abs;
pub mod add;
pub mod ceil;
pub mod clamp;
pub mod divide;
pub mod equal;
pub mod floor;
pub mod gt;
pub mod gte;
pub mod lt;
pub mod lte;
pub mod max;
pub mod min;
pub mod multiply;
pub mod pow;
pub mod random_range;
pub mod root;
pub mod round;
pub mod subtract;
pub mod unequal;
