[package]
name = "flow-like-bits"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-like-types = { path = "../types" }
flow-like-storage = { path = "../storage" }
schemars.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }