-- Aurora DSQL migration "sourcemap_claim_check"
-- Generated by packages/api/scripts/dsql-migration.ts (--from-schema prisma/migrations-dsql/schema.snapshot.prisma) and rewritten by dsql-lint 0.2.17.
-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,
-- waits for the async index/validation jobs and records the migration in _prisma_migrations.
-- tables=0 indexes=0 foreign_keys=0 validations=0 statements=1
ALTER TABLE "TelemetrySourceMap" ADD COLUMN     "mapRef" TEXT,
ALTER COLUMN "map" DROP NOT NULL;
