-- Aurora DSQL migration "database_consistency"
-- Generated by packages/api/scripts/dsql-migration.ts (--from-schema prisma/migrations-dsql/schema.snapshot.prisma) and rewritten by dsql-lint 0.2.17.
-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,
-- waits for the async index/validation jobs and records the migration in _prisma_migrations.
-- tables=1 indexes=19 foreign_keys=0 validations=0 statements=20
CREATE TABLE "FileAccountingObject" (
    "id" TEXT NOT NULL,
    "bucket" TEXT NOT NULL,
    "objectKey" TEXT NOT NULL,
    "appId" TEXT NOT NULL,
    "userId" TEXT,
    "size" BIGINT NOT NULL,
    "sequencer" TEXT NOT NULL,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FileAccountingObject_pkey" PRIMARY KEY ("id")
);

CREATE INDEX ASYNC "FileAccountingObject_appId_idx" ON "FileAccountingObject"("appId");

CREATE INDEX ASYNC "FileAccountingObject_userId_idx" ON "FileAccountingObject"("userId");

CREATE INDEX ASYNC "Invitation_appId_idx" ON "Invitation"("appId");

CREATE INDEX ASYNC "Invitation_byMemberId_idx" ON "Invitation"("byMemberId");

CREATE INDEX ASYNC "AppConnection_roleId_idx" ON "AppConnection"("roleId");

CREATE INDEX ASYNC "Membership_roleId_idx" ON "Membership"("roleId");

CREATE INDEX ASYNC "Role_appId_idx" ON "Role"("appId");

CREATE INDEX ASYNC "TechnicalUser_roleId_idx" ON "TechnicalUser"("roleId");

CREATE INDEX ASYNC "Feedback_templateId_idx" ON "Feedback"("templateId");

CREATE INDEX ASYNC "Comment_templateId_idx" ON "Comment"("templateId");

CREATE INDEX ASYNC "EventRemoteAuth_eventId_idx" ON "EventRemoteAuth"("eventId");

CREATE INDEX ASYNC "EventRemoteRegistration_eventId_idx" ON "EventRemoteRegistration"("eventId");

CREATE INDEX ASYNC "EventRemoteRegistration_authId_idx" ON "EventRemoteRegistration"("authId");

CREATE INDEX ASYNC "AppPurchase_discountId_idx" ON "AppPurchase"("discountId");

CREATE INDEX ASYNC "PublicationLog_authorId_idx" ON "PublicationLog"("authorId");

CREATE INDEX ASYNC "BitCache_bitId_idx" ON "BitCache"("bitId");

CREATE INDEX ASYNC "Certificate_courseId_idx" ON "Certificate"("courseId");

CREATE INDEX ASYNC "ExecutionRun_technicalUserId_idx" ON "ExecutionRun"("technicalUserId");

CREATE INDEX ASYNC "WasmPackageInvitation_invitedById_idx" ON "WasmPackageInvitation"("invitedById");
