#!/usr/bin/env bun
// Generate a committed Aurora DSQL migration from the Prisma schema of record.
//
//   bun run db:dsql:diff -- <name> [--from-empty | --from-snapshot | --from-url]
//
// Pipeline: make-prisma-mirror.sh --target dsql → prisma migrate diff --script →
// dsql-lint --fix → append ALTER TABLE ASYNC … VALIDATE CONSTRAINT for every
// NOT VALID foreign key the fixer produced → prisma/migrations-dsql/<ts>_<name>/.
//
// The diff base:
//   --from-empty     the initial migration (default when no migration exists yet)
//   --from-snapshot  the merged schema snapshot written by the previous run
//                    (prisma/migrations-dsql/schema.snapshot.prisma); default otherwise
//                    and the supported base. A plain-PostgreSQL shadow database cannot
//                    replay the committed files (CREATE INDEX ASYNC / ALTER TABLE ASYNC
//                    are DSQL-only), so Prisma's --from-migrations path is not usable.
//   --from-url       EXPERIMENTAL: the live cluster. The URL (admin token as password)
//                    is read from DSQL_DIFF_URL or stdin, never from argv, and is
//                    redacted from every message. DSQL introspection renders each index
//                    as `USING btree_index … INCLUDE (…)`, which Prisma cannot map back,
//                    so the diff carries spurious index churn that must be pruned by hand.
//
// Run from packages/api. Prisma needs node_modules; the compose tooling removes
// them again, so `bun install` before and clean up after if that matters to you.

import { spawnSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";

// Pinned once: this script refuses any other dsql-lint, and
// .github/workflows/clippy.yml reads this line to lint the committed files with
// the same version's npm build (@aws/dsql-lint). Bump both by editing here.
export const DSQL_LINT_VERSION = "0.2.17";
export const DIFF_URL_ENV = "DSQL_DIFF_URL";

const API_ROOT = resolve(import.meta.dir, "..");
const MIRROR_ROOT = join(API_ROOT, "prisma-dsql-mirror");
const MIRROR_SCHEMA = join(MIRROR_ROOT, "schema");
const MIGRATIONS_DIR = join(API_ROOT, "prisma", "migrations-dsql");
const SNAPSHOT_FILE = join(MIGRATIONS_DIR, "schema.snapshot.prisma");
const LOCK_FILE = join(MIGRATIONS_DIR, "migration_lock.toml");
const LOCK_CONTENT =
	'# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n';
const EMPTY_MIGRATION_MARKER = "-- This is an empty migration.";
const MIGRATION_NAME = /^[a-z0-9][a-z0-9_-]{0,63}$/;

export const FK_NOT_VALID =
	/^ALTER TABLE\s+("(?:[^"]|"")+"|[\w.]+)\s+ADD CONSTRAINT\s+("(?:[^"]|"")+"|[\w.]+)\s+FOREIGN KEY[\s\S]*?\sNOT VALID\s*;\s*$/gm;

type Base =
	| { kind: "empty" }
	| { kind: "snapshot"; path: string }
	| { kind: "url"; url: string };

interface Options {
	readonly name: string;
	readonly base: Base | null;
}

export type Environment = Record<string, string | undefined>;

class UsageError extends Error {
	override readonly name = "UsageError";
}

// Secrets registered here (the cluster URL and its password) never reach a
// message; the pattern additionally covers any user:password@ in echoed text.
const SECRETS: string[] = [];

export function redact(
	text: string,
	secrets: readonly string[] = SECRETS,
): string {
	let out = text;
	for (const secret of secrets) {
		if (secret !== "") out = out.split(secret).join("***");
	}
	return out.replace(/(:\/\/[^:@\s/]*):[^@\s]*@/g, "$1:***@");
}

function registerSecret(url: string): void {
	SECRETS.push(url);
	try {
		const password = new URL(url).password;
		if (password !== "") {
			SECRETS.push(password);
			SECRETS.push(decodeURIComponent(password));
		}
	} catch {
		// Not a parseable URL: the literal alone is redacted.
	}
}

function log(message: string): void {
	console.log(`[dsql-migration] ${redact(message)}`);
}

function fail(message: string): never {
	console.error(`[dsql-migration] ${redact(message)}`);
	process.exit(1);
}

function stdinText(): string {
	if (process.stdin.isTTY) return "";
	try {
		return readFileSync(0, "utf8");
	} catch {
		return "";
	}
}

// The cluster URL comes from the environment or stdin so that it never shows
// up in `ps`, shell history or this process's argv.
export function diffUrl(env: Environment, readStdin: () => string): string {
	const fromEnv = env[DIFF_URL_ENV]?.trim() ?? "";
	const url = fromEnv !== "" ? fromEnv : readStdin().trim();
	if (url === "") {
		throw new UsageError(
			`--from-url reads the cluster URL from ${DIFF_URL_ENV} or stdin; neither was given`,
		);
	}
	if (!/^postgres(?:ql)?:\/\//i.test(url)) {
		throw new UsageError(`${DIFF_URL_ENV} must be a postgresql:// URL`);
	}
	return url;
}

export function parseArgs(
	argv: readonly string[],
	env: Environment = process.env,
	readStdin: () => string = stdinText,
): Options {
	let name: string | undefined;
	let base: Base | null = null;
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i] as string;
		switch (arg) {
			case "--from-empty":
				base = { kind: "empty" };
				break;
			case "--from-snapshot":
				base = { kind: "snapshot", path: SNAPSHOT_FILE };
				break;
			case "--from-url": {
				const next = argv[i + 1];
				if (next?.includes("://")) {
					throw new UsageError(
						`--from-url takes no argument: a URL in argv is visible in ps and shell history; export ${DIFF_URL_ENV} or pipe the URL on stdin`,
					);
				}
				base = { kind: "url", url: diffUrl(env, readStdin) };
				break;
			}
			default:
				if (arg.includes("://")) {
					throw new UsageError(
						`refusing a URL in argv; export ${DIFF_URL_ENV} or pipe it on stdin and pass --from-url`,
					);
				}
				if (arg.startsWith("--")) throw new UsageError(`unknown flag ${arg}`);
				if (name !== undefined)
					throw new UsageError("only one name is allowed");
				name = arg;
		}
	}
	if (!name) throw new UsageError("missing migration name");
	if (!MIGRATION_NAME.test(name)) {
		throw new UsageError(
			"the name must be lowercase letters, digits, '_' or '-', at most 64 characters",
		);
	}
	return { name, base };
}

export function timestamp(date = new Date()): string {
	return date.toISOString().replace(/[-:T]/g, "").slice(0, 14);
}

export function existingMigrations(dir: string): string[] {
	if (!existsSync(dir)) return [];
	return readdirSync(dir, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort((a, b) => a.localeCompare(b));
}

export function validateConstraintStatements(fixedSql: string): string[] {
	const statements: string[] = [];
	for (const match of fixedSql.matchAll(FK_NOT_VALID)) {
		statements.push(
			`ALTER TABLE ASYNC ${match[1]} VALIDATE CONSTRAINT ${match[2]};`,
		);
	}
	return statements;
}

export interface Counts {
	readonly tables: number;
	readonly indexes: number;
	readonly foreignKeys: number;
	readonly validations: number;
	readonly statements: number;
}

export function countStatements(sql: string): Counts {
	const count = (pattern: RegExp) => (sql.match(pattern) ?? []).length;
	return {
		tables: count(/^CREATE TABLE\b/gm),
		indexes: count(/^CREATE (?:UNIQUE )?INDEX\b/gm),
		foreignKeys: count(
			/^ALTER TABLE\s+\S+\s+ADD CONSTRAINT\s+\S+\s+FOREIGN KEY\b/gm,
		),
		validations: count(/^ALTER TABLE ASYNC\b/gm),
		statements: count(/;\s*$/gm),
	};
}

export function mergeSchemaFiles(dir: string): string {
	const files = readdirSync(dir)
		.filter((file) => file.endsWith(".prisma"))
		.sort((a, b) => a.localeCompare(b));
	const parts = files.map(
		(file) =>
			`// ---- ${file}\n${readFileSync(join(dir, file), "utf8").trimEnd()}\n`,
	);
	return `// Merged DSQL mirror schema snapshot; regenerated by scripts/dsql-migration.ts.\n// Base for the next \`bun run db:dsql:diff\`. Do not edit.\n\n${parts.join("\n")}`;
}

function run(
	command: string[],
	options: { cwd?: string; input?: string; allow?: number[] } = {},
): { code: number; stdout: string; stderr: string } {
	const result = spawnSync(command[0] as string, command.slice(1), {
		cwd: options.cwd ?? API_ROOT,
		input: options.input,
		encoding: "utf8",
		env: {
			...process.env,
			PRISMA_HIDE_UPDATE_MESSAGE: "1",
			CHECKPOINT_DISABLE: "1",
		},
		maxBuffer: 64 * 1024 * 1024,
	});
	if (result.error) fail(`${command.join(" ")}: ${result.error.message}`);
	const code = result.status ?? 1;
	if (!(options.allow ?? [0]).includes(code)) {
		process.stderr.write(redact(result.stderr));
		fail(`${command.join(" ")} exited with code ${code}`);
	}
	return { code, stdout: result.stdout, stderr: result.stderr };
}

function dsqlLintBinary(): string[] {
	const fromEnv = process.env.DSQL_LINT?.trim();
	if (fromEnv) return fromEnv.split(/\s+/);
	const probe = spawnSync("dsql-lint", ["--version"], { encoding: "utf8" });
	if (!probe.error && probe.status === 0) return ["dsql-lint"];
	fail(
		`dsql-lint not found: \`cargo install dsql-lint --version ${DSQL_LINT_VERSION}\`, or set DSQL_LINT to a command such as "npx --yes --package=@aws/dsql-lint@${DSQL_LINT_VERSION} dsql-lint"`,
	);
}

export function lintVersionOf(versionOutput: string): string | null {
	return versionOutput.match(/\b(\d+\.\d+\.\d+)\b/)?.[1] ?? null;
}

function pinnedDsqlLint(): string[] {
	const lint = dsqlLintBinary();
	const found = lintVersionOf(run([...lint, "--version"]).stdout);
	if (found !== DSQL_LINT_VERSION) {
		fail(
			`dsql-lint ${found ?? "(unknown version)"} found, but this repository pins ${DSQL_LINT_VERSION} (DSQL_LINT_VERSION in scripts/dsql-migration.ts, also the CI pin). Install it with \`cargo install dsql-lint --version ${DSQL_LINT_VERSION}\` or set DSQL_LINT="npx --yes --package=@aws/dsql-lint@${DSQL_LINT_VERSION} dsql-lint"`,
		);
	}
	return lint;
}

function header(options: Options, base: Base, counts: Counts): string {
	const from =
		base.kind === "empty"
			? "--from-empty"
			: base.kind === "snapshot"
				? "--from-schema prisma/migrations-dsql/schema.snapshot.prisma"
				: "--from-url <cluster>";
	return [
		`-- Aurora DSQL migration "${options.name}"`,
		`-- Generated by packages/api/scripts/dsql-migration.ts (${from}) and rewritten by dsql-lint ${DSQL_LINT_VERSION}.`,
		"-- Every statement runs in its own transaction; apps/backend/aws/migration applies them one by one,",
		"-- waits for the async index/validation jobs and records the migration in _prisma_migrations.",
		`-- tables=${counts.tables} indexes=${counts.indexes} foreign_keys=${counts.foreignKeys} validations=${counts.validations} statements=${counts.statements}`,
		"",
	].join("\n");
}

function main(): void {
	let options: Options;
	try {
		options = parseArgs(process.argv.slice(2));
	} catch (error) {
		if (error instanceof UsageError) {
			console.error(`[dsql-migration] ${error.message}`);
			console.error(
				`usage: bun run db:dsql:diff -- <name> [--from-empty | --from-snapshot | --from-url]   (--from-url reads ${DIFF_URL_ENV} or stdin)`,
			);
			process.exit(2);
		}
		throw error;
	}
	if (options.base?.kind === "url") registerSecret(options.base.url);

	const previous = existingMigrations(MIGRATIONS_DIR);
	const base: Base =
		options.base ??
		(previous.length === 0
			? { kind: "empty" }
			: { kind: "snapshot", path: SNAPSHOT_FILE });
	if (base.kind === "snapshot" && !existsSync(base.path)) {
		fail(
			`${base.path} is missing; restore it from git (it is committed with every migration) or pass --from-empty explicitly for a fresh cluster`,
		);
	}
	if (base.kind === "empty" && previous.length > 0) {
		log(
			`warning: ${previous.length} migration(s) exist; an --from-empty diff only makes sense for a fresh cluster`,
		);
	}
	if (base.kind === "url") {
		log(
			"warning: --from-url is experimental; DSQL introspection renders indexes as btree_index … INCLUDE, expect spurious index changes to prune by hand",
		);
	}

	const lint = pinnedDsqlLint();

	log("deriving the DSQL mirror schema");
	run([
		"bash",
		join(API_ROOT, "scripts", "make-prisma-mirror.sh"),
		"--target",
		"dsql",
	]);
	if (!statSync(MIRROR_SCHEMA).isDirectory())
		fail("mirror schema was not created");

	const fromArgs =
		base.kind === "empty"
			? ["--from-empty"]
			: base.kind === "snapshot"
				? ["--from-schema", base.path]
				: ["--from-url", base.url];
	log(`diffing ${fromArgs[0]} → ${MIRROR_SCHEMA}`);
	const diff = run([
		"bunx",
		"prisma",
		"migrate",
		"diff",
		...fromArgs,
		"--to-schema",
		MIRROR_SCHEMA,
		"--script",
	]);
	const rawSql = diff.stdout;
	if (rawSql.trim() === "" || rawSql.includes(EMPTY_MIGRATION_MARKER)) {
		rmSync(MIRROR_ROOT, { recursive: true, force: true });
		log("no schema changes against the base; nothing written");
		return;
	}

	log("rewriting for DSQL with dsql-lint --fix");
	const fix = run([...lint, "--fix", "-"], { input: rawSql, allow: [0, 3] });
	const fixedSql = fix.stdout.trimEnd();
	if (fixedSql === "") fail("dsql-lint --fix produced no SQL");
	const warnings = fix.stderr
		.split("\n")
		.filter((line) => line.includes("WARNING"))
		.map((line) => line.replace(/^<stdin>:\d+:\s*/, ""));
	const distinct = new Map<string, number>();
	for (const warning of warnings) {
		distinct.set(warning, (distinct.get(warning) ?? 0) + 1);
	}
	for (const [warning, n] of distinct) log(`fixer: ${n}× ${warning}`);

	const validations = validateConstraintStatements(fixedSql);
	const body =
		validations.length === 0
			? `${fixedSql}\n`
			: `${fixedSql}\n\n-- ValidateForeignKeys (each returns a sys.jobs id; the runner waits for them)\n${validations.join("\n")}\n`;
	const counts = countStatements(body);
	const migrationSql = header(options, base, counts) + body;

	const check = run([...lint, "-"], { input: migrationSql, allow: [0, 1] });
	if (check.code !== 0) {
		process.stderr.write(redact(check.stdout));
		process.stderr.write(redact(check.stderr));
		fail("the final migration still has DSQL lint errors; see above");
	}

	const dirName = `${timestamp()}_${options.name}`;
	const migrationDir = join(MIGRATIONS_DIR, dirName);
	mkdirSync(migrationDir, { recursive: true });
	writeFileSync(join(migrationDir, "migration.sql"), migrationSql);
	if (!existsSync(LOCK_FILE)) writeFileSync(LOCK_FILE, LOCK_CONTENT);
	writeFileSync(SNAPSHOT_FILE, mergeSchemaFiles(MIRROR_SCHEMA));
	run(["bunx", "prisma", "validate", "--schema", SNAPSHOT_FILE]);
	rmSync(MIRROR_ROOT, { recursive: true, force: true });

	log(`wrote prisma/migrations-dsql/${dirName}/migration.sql`);
	log(
		`tables=${counts.tables} indexes=${counts.indexes} foreign_keys=${counts.foreignKeys} validations=${counts.validations} statements=${counts.statements}`,
	);
	log(
		"review the file, then commit prisma/migrations-dsql/ (including schema.snapshot.prisma)",
	);
}

if (import.meta.main) main();
