import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { driftIn, parseTypemap, retypeSource, run } from "./retype-entities";

const FIXTURE = `//! \`SeaORM\` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "App")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_name = "primaryCategory", column_type = "Text", nullable)]
    pub primary_category: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub bits: Option<Json>,
    #[sea_orm(column_name = "forkPolicy", column_type = "JsonBinary", nullable)]
    pub fork_policy: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
}
`;

const MAP = `# entity_file\tfield\ttype
app\tstatus\tcrate::sea_orm_active_enums::Status
app\tprimary_category\tcrate::sea_orm_active_enums::Category
app\ttype\tcrate::sea_orm_active_enums::BitType
app\tbits\tcrate::json_types::StringList
`;

describe("parseTypemap", () => {
	test("skips comments and blank lines", () => {
		expect(parseTypemap(MAP)).toEqual([
			{
				entity: "app",
				field: "status",
				type: "crate::sea_orm_active_enums::Status",
			},
			{
				entity: "app",
				field: "primary_category",
				type: "crate::sea_orm_active_enums::Category",
			},
			{
				entity: "app",
				field: "type",
				type: "crate::sea_orm_active_enums::BitType",
			},
			{ entity: "app", field: "bits", type: "crate::json_types::StringList" },
		]);
	});

	test("rejects malformed rows", () => {
		expect(() => parseTypemap("app\tstatus")).toThrow(/line 1/);
	});
});

describe("retypeSource", () => {
	const entries = parseTypemap(MAP);

	test("rewrites enum, optional enum, raw-identifier and json list fields", () => {
		const result = retypeSource(FIXTURE, entries);
		expect(result.missing).toEqual([]);
		expect(result.rewritten).toEqual([
			"status",
			"primary_category",
			"type",
			"bits",
		]);
		expect(result.source).toContain(
			"    pub status: crate::sea_orm_active_enums::Status,",
		);
		expect(result.source).toContain(
			"    pub primary_category: Option<crate::sea_orm_active_enums::Category>,",
		);
		expect(result.source).toContain(
			"    pub r#type: crate::sea_orm_active_enums::BitType,",
		);
		expect(result.source).toContain(
			"    pub bits: Option<crate::json_types::StringList>,",
		);
		expect(result.source).toContain(
			'    #[sea_orm(column_type = "JsonBinary", nullable)]\n    pub bits:',
		);
		expect(result.source).toContain("    pub fork_policy: Option<Json>,");
		expect(result.source).toContain("    pub changelog: Option<String>,");
	});

	test("is idempotent", () => {
		const first = retypeSource(FIXTURE, entries);
		const second = retypeSource(first.source, entries);
		expect(second.source).toBe(first.source);
		expect(second.rewritten).toEqual([]);
		expect(second.unchanged).toEqual([
			"status",
			"primary_category",
			"type",
			"bits",
		]);
	});

	test("reports fields the codegen did not produce", () => {
		const result = retypeSource(FIXTURE, [
			...entries,
			{
				entity: "app",
				field: "visibility",
				type: "crate::sea_orm_active_enums::Visibility",
			},
		]);
		expect(result.missing).toEqual(["visibility"]);
	});
});

describe("retypeSource on unformatted codegen output", () => {
	const TOKEN_STREAM =
		'# [sea_orm :: model] # [derive (Clone , Debug)] pub struct Model { # [sea_orm (primary_key , auto_increment = false , column_type = "Text")] pub id : String , # [sea_orm (column_type = "Text")] pub status : String , # [sea_orm (column_name = "primaryCategory" , column_type = "Text" , nullable)] pub primary_category : Option < String > , # [sea_orm (column_type = "Text")] pub r#type : String , # [sea_orm (column_type = "JsonBinary" , nullable)] pub bits : Option < Json > , # [sea_orm (column_type = "Text" , nullable)] pub changelog : Option < String > , }';

	test("rewrites the single-line token stream and stays idempotent", () => {
		const entries = parseTypemap(MAP);
		const first = retypeSource(TOKEN_STREAM, entries);
		expect(first.missing).toEqual([]);
		expect(first.rewritten).toEqual([
			"status",
			"primary_category",
			"type",
			"bits",
		]);
		expect(first.source).toContain(
			"pub status : crate::sea_orm_active_enums::Status,",
		);
		expect(first.source).toContain(
			"pub primary_category : Option<crate::sea_orm_active_enums::Category>,",
		);
		expect(first.source).toContain(
			"pub r#type : crate::sea_orm_active_enums::BitType,",
		);
		expect(first.source).toContain(
			"pub bits : Option<crate::json_types::StringList>,",
		);
		expect(first.source).toContain("pub changelog : Option < String > ,");
		const second = retypeSource(first.source, entries);
		expect(second.source).toBe(first.source);
		expect(second.unchanged).toHaveLength(4);
	});

	test("detects drift in the token stream", () => {
		expect(driftIn("pub tags : Option < Vec < String > > ,")).toHaveLength(1);
		expect(
			driftIn("use super :: sea_orm_active_enums :: Status ;"),
		).toHaveLength(1);
	});
});

describe("driftIn", () => {
	test("flags enum imports and array fields", () => {
		expect(driftIn(FIXTURE)).toEqual([]);
		expect(
			driftIn(
				"use super::sea_orm_active_enums::Status;\n    pub tags: Option<Vec<String>>,\n",
			),
		).toHaveLength(2);
	});
});

describe("run", () => {
	function fixtureDir(): { entities: string; map: string } {
		const root = mkdtempSync(join(tmpdir(), "retype-"));
		const entities = join(root, "entity");
		require("node:fs").mkdirSync(entities);
		writeFileSync(
			join(entities, "mod.rs"),
			"pub mod prelude;\n\npub mod app;\n",
		);
		writeFileSync(join(entities, "app.rs"), FIXTURE);
		writeFileSync(join(entities, "sea_orm_active_enums.rs"), "// stale\n");
		const map = join(root, "map.tsv");
		writeFileSync(map, MAP);
		return { entities, map };
	}

	test("rewrites files in place, removes the stale enum file and is idempotent", () => {
		const { entities, map } = fixtureDir();
		expect(run(entities, map)).toBe(0);
		const once = readFileSync(join(entities, "app.rs"), "utf8");
		expect(once).toContain("crate::json_types::StringList");
		expect(
			require("node:fs").existsSync(join(entities, "sea_orm_active_enums.rs")),
		).toBe(false);
		expect(run(entities, map)).toBe(0);
		expect(readFileSync(join(entities, "app.rs"), "utf8")).toBe(once);
	});

	test("fails when the codegen still emits enums or a mapped entity is missing", () => {
		const { entities, map } = fixtureDir();
		writeFileSync(
			join(entities, "mod.rs"),
			"pub mod app;\npub mod sea_orm_active_enums;\n",
		);
		writeFileSync(
			map,
			`${MAP}missing\tfield\tcrate::sea_orm_active_enums::Status\n`,
		);
		expect(run(entities, map)).toBe(1);
	});
});
