[package]
name = "k8s-executor"
version = "0.1.0"
edition = "2024"
description = "Flow-Like Kubernetes Workflow Executor"

[features]
default = []
local-ml-cuda = ["flow-like-runtime/local-ml-cuda", "flow-like-catalog/local-ml-cuda", "flow-like-executor/local-ml-cuda"]
local-ml-tensorrt = ["local-ml-cuda", "flow-like-runtime/local-ml-tensorrt", "flow-like-catalog/local-ml-tensorrt", "flow-like-executor/local-ml-tensorrt"]

[dependencies]
flow-like-runtime = { workspace = true, features = ["flow-metadata", "flow-runtime", "model"] }
flow-like-types.workspace = true
flow-like-storage.workspace = true
flow-like-catalog = { workspace = true, default-features = false, features = ["executor-local-ml"] }
flow-like-executor = { workspace = true, features = ["executor-local-ml"] }
mimalloc.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
tracing-opentelemetry.workspace = true

tokio = { version = "1", features = ["full"] }
reqwest.workspace = true
url = "2"
base64 = "0.22"
axum.workspace = true
futures-util = "0.3"
