[package]
name = "flow-like"
description = "Flow-Like, Automation done with the press of a Button. Core Library for Flow Execution and Management"
version = "0.1.0"
edition = "2024"
authors = ["TM9657 GmbH"]
repository = "https://github.com/TM9657/flow-like/"
categories = ["GenAI", "AI", "Productivity"]
license-file = "LICENSE"
readme = "README.md"

[lib]
name = "flow_like"
crate-type = ["lib", "cdylib", "staticlib"]
bench = false

[dependencies]
flow-like-types = { path = "../types" }
flow-like-bits = { path = "../bits" }
flow-like-model-provider = { path = "../model-provider" }
flow-like-storage = { path = "../storage" }
wasmer = "5.0.3"
rayon = "1.9.0"
http-cache-reqwest = {version="0.15.0", features = [] }
reqwest-middleware = {version="0.4.0", features = [] }
reqwest-retry = {version="0.7.0", features = [] }
reqwest-tracing = {version="0.5.5", features = [] }
portpicker = "0.1.1"
dirs-next = "2.0.0"
sysinfo = "0.33.0"
zip = "2.5.0"
ignore = "0.4.23"
sentry = {version="0.36.0", features = ["anyhow"] }
gguf = "0.1.2"
wgpu = "22.1.0"
fs_extra = "1.3.0"
mime_guess = "2.0.5"
kamadak-exif = "0.6.1"
lopdf = "0.35.0"
pdf = "0.9.0"
id3 = "1.16.0"
mp4ameta = "0.11.0"
ring = "0.17.13"
scraper = "0.22.0"
image = "0.25.5"
num_cpus = "1.16.0"
ahash = "0.8.11"
strsim = "0.11.1"
base64 = "0.22.1"
tempfile = "3.15.0"
lz4_flex = "0.11.3"
url = {version = "2.5.4", features = ["serde"]}
json5 = "0.4.1"
schemars.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "flow_bench"
harness = false

[features]
schema-gen = []
flow-runtime = []
flow = ["flow-runtime"]
hub = []
bit = ["hub"]
model = ["bit"]
app = ["bit", "model", "hub"]
full = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]
default = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true
opt-level = "z"

[profile.dev]
opt-level = 1
