[package]
name = "flow-like"
description = "Flow-Like, Automation done with the press of a Button. Core Library for Flow Execution and Management"
version = "0.1.0"
edition = "2021"
authors = ["TM9657 GmbH"]
repository = "https://github.com/TM9657/flow-like/"
categories = ["GenAI", "AI", "Productivity"]
license-file = "LICENSE"
readme = "README.md"

[lib]
name = "flow_like"
crate-type = ["lib", "cdylib", "staticlib"]
bench = false

[dependencies]
serde_json = "1.0.133"
serde = { version = "1.0.216", features = ["derive", "rc"] }
cuid2 = "0.1.3"
wasmer = "5.0.3"
rayon = "1.9.0"
regex = "1.11.1"
window-vibrancy = "0.6.0"
async-trait = "0.1.83"
reqwest = { version = "0.12.9", features = ["stream", "json", "gzip", "brotli", "socks", "http2"] }
futures = "0.3.31"
tantivy = "0.22.0"
http-cache-reqwest = {version="0.15.0", features = [] }
reqwest-middleware = {version="0.4.0", features = [] }
reqwest-retry = {version="0.7.0", features = [] }
reqwest-tracing = {version="0.5.5", features = [] }
anyhow = "1.0.94"
portpicker = "0.1.1"
tokio = {version="1.42.0", features = ["full"] }
fastembed = {version="4.3.0", default-features = false, features = ["ort-download-binaries"] }
dirs-next = "2.0.0"
arrow-array = "54.1"
sysinfo = "0.33.0"
flate2 = "1.0.35"
arrow-schema = {version="54.1", features = ["serde"] }
arrow = "54.1"
lancedb = {version="0.18.1" }
walkdir = "2.5.0"
junction = "1.2.0"
zip = "2.5.0"
ignore = "0.4.23"
text-splitter = { version = "0.23.0", features = ["markdown", "tokenizers"] }
tokenizers = "0.21.0"
sha2 = "0.10.8"
sentry = {version="0.36.0", features = ["anyhow"] }
object_store = {version="0.11.1", features = ["gcp", "aws", "azure", "serde", "serde_json", "cloud"] }
gguf = "0.1.2"
wgpu = "22.1.0"
fs_extra = "1.3.0"
mime_guess = "2.0.5"
kamadak-exif = "0.6.1"
lopdf = "0.35.0"
pdf = "0.9.0"
id3 = "1.16.0"
mp4ameta = "0.11.0"
ring = "0.17.13"
serde_arrow = { version = "0.13.1", features = ["arrow-54"] }
scraper = "0.22.0"
image = "0.25.5"
once_cell = "1.20.2"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = {version ="2.0.90", features = ["full"] }
ctor = "0.2.9"
erased-serde = "0.4.5"
num_cpus = "1.16.0"
ahash = "0.8.11"
strsim = "0.11.1"
dashmap = { version="6.1.0", features = ["serde", "rayon", "inline"] }
blake3 = {version = "1.5.5", features = ["rayon"]}
base64 = "0.22.1"
schemars = "0.8.21"
tempfile = "3.15.0"
lz4_flex = "0.11.3"
url = {version = "2.5.4", features = ["serde"]}
bytes = "1.10.0"
nalgebra = "0.33.2"
rand = "0.9.0"
fasteval = "0.2.4"
chrono = "0.4.39"
json5 = "0.4.1"
deno_core = "0.341.0"
prost = "0.13.5"
prost-types = "0.13.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "hashing_bench"
harness = false

[[bench]]
name = "flow_bench"
harness = false

[features]
schema-gen = []
flow-runtime = []
flow = ["flow-runtime"]
hub = []
bit = ["hub"]
model = ["bit"]
app = ["bit", "model", "hub"]
full = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]
default = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true
opt-level = "z"

[profile.dev]
opt-level = 1

[build-dependencies]
prost-build = "0.13.5"
