//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AiActAssessment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AiActAssessment_appId_version_key"
    )]
    pub app_id: String,
    #[sea_orm(unique_key = "AiActAssessment_appId_version_key")]
    pub version: i32,
    #[sea_orm(column_name = "conformityScore")]
    pub conformity_score: Option<i32>,
    #[sea_orm(column_name = "conformityBand", column_type = "Text", nullable)]
    pub conformity_band: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub answers: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub signals: Option<Json>,
    #[sea_orm(
        column_name = "transparencyObligations",
        column_type = "JsonBinary",
        nullable
    )]
    pub transparency_obligations: Option<Json>,
    #[sea_orm(column_name = "responsibleUserId", column_type = "Text", nullable)]
    pub responsible_user_id: Option<String>,
    #[sea_orm(column_name = "responsibleName", column_type = "Text", nullable)]
    pub responsible_name: Option<String>,
    #[sea_orm(column_name = "responsibleEmail", column_type = "Text", nullable)]
    pub responsible_email: Option<String>,
    #[sea_orm(column_name = "submittedAt")]
    pub submitted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "reviewedById", column_type = "Text", nullable)]
    pub reviewed_by_id: Option<String>,
    #[sea_orm(column_name = "reviewedAt")]
    pub reviewed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "reviewNote", column_type = "Text", nullable)]
    pub review_note: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::AiActAssessmentStatus,
    #[sea_orm(column_name = "riskCategory", column_type = "Text")]
    pub risk_category: crate::sea_orm_active_enums::AiRiskCategory,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
