//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AiActModelRegistry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "AiActModelRegistry_provider_modelId_key"
    )]
    pub provider: String,
    #[sea_orm(
        column_name = "modelId",
        column_type = "Text",
        unique_key = "AiActModelRegistry_provider_modelId_key"
    )]
    pub model_id: String,
    pub hosted: bool,
    #[sea_orm(column_name = "openLicence")]
    pub open_licence: bool,
    #[sea_orm(column_name = "systemicRisk")]
    pub systemic_risk: bool,
    pub vetted: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub posture: crate::sea_orm_active_enums::AiGpaiPosture,
}

impl ActiveModelBehavior for ActiveModel {}
