//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AiActModelObservation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AiActModelObservation_appId_modelId_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "modelId",
        column_type = "Text",
        unique_key = "AiActModelObservation_appId_modelId_key"
    )]
    pub model_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    pub hosted: bool,
    #[sea_orm(column_name = "openLicence")]
    pub open_licence: bool,
    #[sea_orm(column_name = "systemicRisk")]
    pub systemic_risk: bool,
    pub vetted: bool,
    #[sea_orm(column_name = "dynamicSelector")]
    pub dynamic_selector: bool,
    #[sea_orm(column_name = "driftFlagged")]
    pub drift_flagged: bool,
    #[sea_orm(column_name = "firstSeenAt")]
    pub first_seen_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "lastSeenAt")]
    pub last_seen_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub source: crate::sea_orm_active_enums::AiModelSource,
    #[sea_orm(column_type = "Text")]
    pub posture: crate::sea_orm_active_enums::AiGpaiPosture,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
