//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "App")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    #[sea_orm(column_name = "defaultRoleId", column_type = "Text", nullable, unique)]
    pub default_role_id: Option<String>,
    #[sea_orm(column_name = "ownerRoleId", column_type = "Text", nullable, unique)]
    pub owner_role_id: Option<String>,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i64,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i64,
    #[sea_orm(column_name = "downloadCount")]
    pub download_count: i64,
    #[sea_orm(column_name = "interactionsCount")]
    pub interactions_count: i64,
    #[sea_orm(column_name = "avgRating", column_type = "Double", nullable)]
    pub avg_rating: Option<f64>,
    #[sea_orm(column_name = "relevanceScore", column_type = "Double", nullable)]
    pub relevance_score: Option<f64>,
    #[sea_orm(column_name = "totalSize")]
    pub total_size: i64,
    pub price: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "allowForking")]
    pub allow_forking: bool,
    #[sea_orm(column_name = "forkedAt")]
    pub forked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "forkedFrom", column_type = "Text", nullable)]
    pub forked_from: Option<String>,
    #[sea_orm(column_name = "forkPolicy", column_type = "JsonBinary", nullable)]
    pub fork_policy: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::Status,
    #[sea_orm(column_type = "Text")]
    pub visibility: crate::sea_orm_active_enums::Visibility,
    #[sea_orm(column_name = "primaryCategory", column_type = "Text", nullable)]
    pub primary_category: Option<crate::sea_orm_active_enums::Category>,
    #[sea_orm(column_name = "secondaryCategory", column_type = "Text", nullable)]
    pub secondary_category: Option<crate::sea_orm_active_enums::Category>,
    #[sea_orm(column_name = "executionMode", column_type = "Text")]
    pub execution_mode: crate::sea_orm_active_enums::ExecutionMode,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub bits: Option<crate::json_types::StringList>,
    #[sea_orm(column_name = "appType", column_type = "Text", nullable)]
    pub app_type: Option<crate::sea_orm_active_enums::AppType>,
    #[sea_orm(has_many)]
    pub ai_act_assessments: HasMany<super::ai_act_assessment::Entity>,
    #[sea_orm(has_many)]
    pub ai_act_model_observations: HasMany<super::ai_act_model_observation::Entity>,
    #[sea_orm(has_many)]
    pub app_analytics_dailies: HasMany<super::app_analytics_daily::Entity>,
    #[sea_orm(has_many)]
    pub app_board_scores: HasMany<super::app_board_score::Entity>,
    #[sea_orm(has_many)]
    pub app_discounts: HasMany<super::app_discount::Entity>,
    #[sea_orm(has_many)]
    pub app_groups: HasMany<super::app_group::Entity>,
    #[sea_orm(has_many)]
    pub app_group_members: HasMany<super::app_group_member::Entity>,
    #[sea_orm(has_many)]
    pub app_packages: HasMany<super::app_package::Entity>,
    #[sea_orm(has_many)]
    pub app_process_notes: HasMany<super::app_process_note::Entity>,
    #[sea_orm(has_many)]
    pub app_purchases: HasMany<super::app_purchase::Entity>,
    #[sea_orm(has_many)]
    pub app_sales_dailies: HasMany<super::app_sales_daily::Entity>,
    #[sea_orm(has_many)]
    pub app_usage_limits: HasMany<super::app_usage_limit::Entity>,
    #[sea_orm(has_many)]
    pub board_syncs: HasMany<super::board_sync::Entity>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(has_many)]
    pub course_app_links: HasMany<super::course_app_link::Entity>,
    #[sea_orm(has_many)]
    pub embedding_usage_trackings: HasMany<super::embedding_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub events: HasMany<super::event::Entity>,
    #[sea_orm(has_many)]
    pub event_aliases: HasMany<super::event_alias::Entity>,
    #[sea_orm(has_many)]
    pub event_remote_auths: HasMany<super::event_remote_auth::Entity>,
    #[sea_orm(has_many)]
    pub event_remote_registrations: HasMany<super::event_remote_registration::Entity>,
    #[sea_orm(has_many)]
    pub event_setups: HasMany<super::event_setup::Entity>,
    #[sea_orm(has_many)]
    pub event_sinks: HasMany<super::event_sink::Entity>,
    #[sea_orm(has_many)]
    pub execution_runs: HasMany<super::execution_run::Entity>,
    #[sea_orm(has_many)]
    pub execution_usage_trackings: HasMany<super::execution_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub feedbacks: HasMany<super::feedback::Entity>,
    #[sea_orm(has_many)]
    pub invitations: HasMany<super::invitation::Entity>,
    #[sea_orm(has_many)]
    pub invite_links: HasMany<super::invite_link::Entity>,
    #[sea_orm(has_many)]
    pub join_queues: HasMany<super::join_queue::Entity>,
    #[sea_orm(has_many)]
    pub llm_usage_trackings: HasMany<super::llm_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub memberships: HasMany<super::membership::Entity>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
    #[sea_orm(has_many)]
    pub notifications: HasMany<super::notification::Entity>,
    #[sea_orm(has_many)]
    pub pages: HasMany<super::page::Entity>,
    #[sea_orm(has_many)]
    pub publication_requests: HasMany<super::publication_request::Entity>,
    #[sea_orm(has_many)]
    pub regression_suites: HasMany<super::regression_suite::Entity>,
    #[sea_orm(has_many)]
    pub regression_suite_runs: HasMany<super::regression_suite_run::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Role2",
        from = "default_role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub role_2: BelongsTo<Option<super::role::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Role1",
        from = "owner_role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub role_1: BelongsTo<Option<super::role::Entity>>,
    #[sea_orm(has_many)]
    pub technical_users: HasMany<super::technical_user::Entity>,
    #[sea_orm(has_many)]
    pub templates: HasMany<super::template::Entity>,
    #[sea_orm(has_many)]
    pub widgets: HasMany<super::widget::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
