//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppDiscount")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppDiscount_appId_code_key"
    )]
    pub app_id: String,
    #[sea_orm(column_type = "Text", unique_key = "AppDiscount_appId_code_key")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "discountValue")]
    pub discount_value: i64,
    #[sea_orm(column_name = "maxUses")]
    pub max_uses: Option<i64>,
    #[sea_orm(column_name = "usedCount")]
    pub used_count: i64,
    #[sea_orm(column_name = "minPurchaseAmount")]
    pub min_purchase_amount: Option<i64>,
    #[sea_orm(column_name = "startsAt")]
    pub starts_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "discountType", column_type = "Text")]
    pub discount_type: crate::sea_orm_active_enums::DiscountType,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub app_purchases: HasMany<super::app_purchase::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
