//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppPurchase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "pricePaid")]
    pub price_paid: i64,
    #[sea_orm(column_name = "originalPrice")]
    pub original_price: i64,
    #[sea_orm(column_name = "discountAmount")]
    pub discount_amount: i64,
    #[sea_orm(column_name = "discountId", column_type = "Text", nullable)]
    pub discount_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_name = "stripeSessionId", column_type = "Text")]
    pub stripe_session_id: String,
    #[sea_orm(column_name = "stripePaymentIntentId", column_type = "Text", nullable)]
    pub stripe_payment_intent_id: Option<String>,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "refundedAt")]
    pub refunded_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "refundReason", column_type = "Text", nullable)]
    pub refund_reason: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::PurchaseStatus,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "discount_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub app_discount: BelongsTo<Option<super::app_discount::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
