//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppGroup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "ownerAppId", column_type = "Text")]
    pub owner_app_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::Status,
    #[sea_orm(column_type = "Text")]
    pub visibility: crate::sea_orm_active_enums::Visibility,
    #[sea_orm(
        belongs_to,
        from = "owner_app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub app_group_members: HasMany<super::app_group_member::Entity>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
    #[sea_orm(has_many)]
    pub publication_requests: HasMany<super::publication_request::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
