//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppBoardScore")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppBoardScore_appId_boardId_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "boardId",
        column_type = "Text",
        unique_key = "AppBoardScore_appId_boardId_key"
    )]
    pub board_id: String,
    pub security: i32,
    pub privacy: i32,
    pub performance: i32,
    pub governance: i32,
    pub reliability: i32,
    pub cost: i32,
    #[sea_orm(column_name = "worstScore")]
    pub worst_score: i32,
    #[sea_orm(column_name = "nodeCount")]
    pub node_count: i32,
    #[sea_orm(column_name = "scoredNodeCount")]
    pub scored_node_count: i32,
    #[sea_orm(column_name = "connectionCount")]
    pub connection_count: i32,
    #[sea_orm(column_name = "flaggedPatterns", column_type = "JsonBinary", nullable)]
    pub flagged_patterns: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub summary: Option<Json>,
    #[sea_orm(column_name = "computedAt")]
    pub computed_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
