//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppCacheEntry")]
pub struct Model {
    #[sea_orm(
        column_name = "appId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "userId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub key: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub value: Json,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub namespace: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub scope: crate::sea_orm_active_enums::CacheScope,
}

impl ActiveModelBehavior for ActiveModel {}
