//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppAnalyticsDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppAnalyticsDaily_appId_date_key"
    )]
    pub app_id: String,
    #[sea_orm(unique_key = "AppAnalyticsDaily_appId_date_key")]
    pub date: Date,
    #[sea_orm(column_name = "totalExecutions")]
    pub total_executions: i64,
    #[sea_orm(column_name = "successfulExecutions")]
    pub successful_executions: i64,
    #[sea_orm(column_name = "failedExecutions")]
    pub failed_executions: i64,
    #[sea_orm(column_name = "uniqueUsers")]
    pub unique_users: i64,
    #[sea_orm(column_name = "feedbackCount")]
    pub feedback_count: i64,
    #[sea_orm(column_name = "avgFeedbackRating", column_type = "Double", nullable)]
    pub avg_feedback_rating: Option<f64>,
    #[sea_orm(column_name = "positiveFeedback")]
    pub positive_feedback: i64,
    #[sea_orm(column_name = "negativeFeedback")]
    pub negative_feedback: i64,
    #[sea_orm(column_name = "totalLlmCalls")]
    pub total_llm_calls: i64,
    #[sea_orm(column_name = "totalLlmTokensIn")]
    pub total_llm_tokens_in: i64,
    #[sea_orm(column_name = "totalLlmTokensOut")]
    pub total_llm_tokens_out: i64,
    #[sea_orm(column_name = "totalLlmCost")]
    pub total_llm_cost: i64,
    #[sea_orm(column_name = "avgLatencyMs", column_type = "Double", nullable)]
    pub avg_latency_ms: Option<f64>,
    #[sea_orm(column_name = "p95LatencyMs", column_type = "Double", nullable)]
    pub p95_latency_ms: Option<f64>,
    #[sea_orm(column_name = "totalEmbeddingCalls")]
    pub total_embedding_calls: i64,
    #[sea_orm(column_name = "totalEmbeddingTokens")]
    pub total_embedding_tokens: i64,
    #[sea_orm(column_name = "totalEmbeddingCost")]
    pub total_embedding_cost: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
