//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppConnection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "sourceAppId",
        column_type = "Text",
        unique_key = "AppConnection_sourceAppId_targetAppId_key"
    )]
    pub source_app_id: String,
    #[sea_orm(
        column_name = "targetAppId",
        column_type = "Text",
        unique_key = "AppConnection_sourceAppId_targetAppId_key"
    )]
    pub target_app_id: String,
    #[sea_orm(column_name = "roleId", column_type = "Text", nullable)]
    pub role_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    #[sea_orm(column_name = "requestedByUserId", column_type = "Text", nullable)]
    pub requested_by_user_id: Option<String>,
    #[sea_orm(column_name = "approvedByUserId", column_type = "Text", nullable)]
    pub approved_by_user_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::AppConnectionStatus,
    #[sea_orm(
        belongs_to,
        relation_enum = "App2",
        from = "source_app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app_2: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "App1",
        from = "target_app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app_1: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub role: BelongsTo<Option<super::role::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
