//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppGroupMember")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "groupId",
        column_type = "Text",
        unique_key = "AppGroupMember_groupId_appId_key"
    )]
    pub group_id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppGroupMember_groupId_appId_key"
    )]
    pub app_id: String,
    pub position: i32,
    #[sea_orm(column_name = "addedByUserId", column_type = "Text", nullable)]
    pub added_by_user_id: Option<String>,
    #[sea_orm(column_name = "approvedByUserId", column_type = "Text", nullable)]
    pub approved_by_user_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub kind: crate::sea_orm_active_enums::AppGroupMemberKind,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::AppGroupMemberStatus,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app_group: BelongsTo<super::app_group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
