//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppUsageLimit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppUsageLimit_appId_userId_period_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "AppUsageLimit_appId_userId_period_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "AppUsageLimit_appId_userId_period_key"
    )]
    pub period: String,
    #[sea_orm(column_name = "costMicroDollars")]
    pub cost_micro_dollars: Option<i64>,
    #[sea_orm(column_name = "tokenLimit")]
    pub token_limit: Option<i64>,
    pub enabled: bool,
    pub hard: bool,
    #[sea_orm(column_name = "warningThresholdPercent")]
    pub warning_threshold_percent: Option<i32>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
