//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppSalesDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppSalesDaily_appId_date_key"
    )]
    pub app_id: String,
    #[sea_orm(unique_key = "AppSalesDaily_appId_date_key")]
    pub date: Date,
    #[sea_orm(column_name = "totalRevenue")]
    pub total_revenue: i64,
    #[sea_orm(column_name = "grossRevenue")]
    pub gross_revenue: i64,
    #[sea_orm(column_name = "totalDiscounts")]
    pub total_discounts: i64,
    #[sea_orm(column_name = "purchaseCount")]
    pub purchase_count: i64,
    #[sea_orm(column_name = "refundCount")]
    pub refund_count: i64,
    #[sea_orm(column_name = "refundAmount")]
    pub refund_amount: i64,
    #[sea_orm(column_name = "uniqueBuyers")]
    pub unique_buyers: i64,
    #[sea_orm(column_name = "avgOrderValue")]
    pub avg_order_value: i64,
    #[sea_orm(column_name = "discountCodesUsed")]
    pub discount_codes_used: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
