//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppPackage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "AppPackage_appId_packageId_key"
    )]
    pub app_id: String,
    #[sea_orm(column_name = "membershipId", column_type = "Text", nullable)]
    pub membership_id: Option<String>,
    #[sea_orm(
        column_name = "packageId",
        column_type = "Text",
        unique_key = "AppPackage_appId_packageId_key"
    )]
    pub package_id: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    #[sea_orm(column_name = "addedAt")]
    pub added_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "autoUpdate")]
    pub auto_update: bool,
    pub stale: bool,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "membership_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub membership: BelongsTo<Option<super::membership::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
