//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AuditEntry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "AuditEntry_chainId_sequence_key")]
    pub sequence: i64,
    pub timestamp: DateTimeWithTimeZone,
    #[sea_orm(column_name = "actorId", column_type = "Text")]
    pub actor_id: String,
    #[sea_orm(column_name = "actorIp", column_type = "Text", nullable)]
    pub actor_ip: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_name = "resourceType", column_type = "Text")]
    pub resource_type: String,
    #[sea_orm(column_name = "resourceId", column_type = "Text")]
    pub resource_id: String,
    #[sea_orm(
        column_name = "chainId",
        column_type = "Text",
        nullable,
        unique_key = "AuditEntry_chainId_sequence_key"
    )]
    pub chain_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    #[sea_orm(column_name = "entryHash", column_type = "Text")]
    pub entry_hash: String,
    #[sea_orm(column_name = "prevHash", column_type = "Text")]
    pub prev_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub signature: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub kid: Option<String>,
    #[sea_orm(column_name = "actorType", column_type = "Text")]
    pub actor_type: crate::sea_orm_active_enums::AuditActorType,
}

impl ActiveModelBehavior for ActiveModel {}
