//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "BitTreeCache")]
pub struct Model {
    #[sea_orm(
        column_name = "dependencyTreeHash",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub dependency_tree_hash: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "dependency_tree_hash",
        to = "dependency_tree_hash",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bit: BelongsTo<super::bit::Entity>,
    #[sea_orm(has_many)]
    pub bit_caches: HasMany<super::bit_cache::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
