//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "BoardSync")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "BoardSync_appId_boardId_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "boardId",
        column_type = "Text",
        unique_key = "BoardSync_appId_boardId_key"
    )]
    pub board_id: String,
    #[sea_orm(column_name = "lastSyncedAt")]
    pub last_synced_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "syncEncryptionKey", column_type = "Text")]
    pub sync_encryption_key: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
