//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Certificate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "Certificate_userId_courseId_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_name = "courseId",
        column_type = "Text",
        unique_key = "Certificate_userId_courseId_key"
    )]
    pub course_id: String,
    #[sea_orm(column_name = "issuedAt")]
    pub issued_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub hash: String,
    #[sea_orm(column_name = "pdfUrl", column_type = "Text", nullable)]
    pub pdf_url: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "course_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course: BelongsTo<super::course::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
