//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Challenge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "lessonId", column_type = "Text")]
    pub lesson_id: String,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub prompt: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub explanation: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub points: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub kind: crate::sea_orm_active_enums::ChallengeKind,
    #[sea_orm(
        belongs_to,
        from = "lesson_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub lesson: BelongsTo<super::lesson::Entity>,
    #[sea_orm(has_many)]
    pub user_challenge_attempts: HasMany<super::user_challenge_attempt::Entity>,
    #[sea_orm(has_many)]
    pub weekly_challenges: HasMany<super::weekly_challenge::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
