//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "channelId", column_type = "Text")]
    pub channel_id: String,
    #[sea_orm(column_type = "Text")]
    pub sub: String,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub kind: crate::sea_orm_active_enums::ChannelMessageKind,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::ChannelMessageStatus,
}

impl ActiveModelBehavior for ActiveModel {}
