//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Comment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub rating: i64,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "Comment_userId_packageId_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        nullable,
        unique_key = "Comment_userId_appId_key"
    )]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "templateId", column_type = "Text", nullable)]
    pub template_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        column_name = "packageId",
        column_type = "Text",
        nullable,
        unique_key = "Comment_userId_packageId_key"
    )]
    pub package_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "template_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub template: BelongsTo<Option<super::template::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        from = "package_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub wasm_package: BelongsTo<Option<super::wasm_package::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
