//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Course")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "authorId", column_type = "Text", nullable)]
    pub author_id: Option<String>,
    #[sea_orm(column_name = "bannerUrl", column_type = "Text", nullable)]
    pub banner_url: Option<String>,
    #[sea_orm(column_name = "estimatedMinutes")]
    pub estimated_minutes: i32,
    #[sea_orm(column_name = "iconUrl", column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    #[sea_orm(column_name = "isPublished")]
    pub is_published: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug: Option<String>,
    pub position: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub category: crate::sea_orm_active_enums::CourseCategory,
    #[sea_orm(column_type = "Text")]
    pub difficulty: crate::sea_orm_active_enums::CourseDifficulty,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<crate::json_types::StringList>,
    #[sea_orm(has_many)]
    pub certificates: HasMany<super::certificate::Entity>,
    #[sea_orm(has_many)]
    pub course_app_links: HasMany<super::course_app_link::Entity>,
    #[sea_orm(has_many)]
    pub course_assets: HasMany<super::course_asset::Entity>,
    #[sea_orm(has_many)]
    pub course_modules: HasMany<super::course_module::Entity>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
    #[sea_orm(has_many)]
    pub user_course_enrollments: HasMany<super::user_course_enrollment::Entity>,
    #[sea_orm(has_many, via = "learning_path_course")]
    pub learning_paths: HasMany<super::learning_path::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
