//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "CourseAsset")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "courseId",
        column_type = "Text",
        unique_key = "CourseAsset_courseId_name_key"
    )]
    pub course_id: String,
    #[sea_orm(column_type = "Text", unique_key = "CourseAsset_courseId_name_key")]
    pub name: String,
    #[sea_orm(column_name = "storageKey", column_type = "Text")]
    pub storage_key: String,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    #[sea_orm(column_name = "mimeType", column_type = "Text")]
    pub mime_type: String,
    pub size: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub kind: crate::sea_orm_active_enums::AssetKind,
    #[sea_orm(
        belongs_to,
        from = "course_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course: BelongsTo<super::course::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
