//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "CourseAppLink")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "courseId",
        column_type = "Text",
        unique_key = "CourseAppLink_courseId_appId_key"
    )]
    pub course_id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "CourseAppLink_courseId_appId_key"
    )]
    pub app_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub alias: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub purpose: crate::sea_orm_active_enums::CourseAppPurpose,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "course_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course: BelongsTo<super::course::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
