//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "DeletionJob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "rootKind",
        column_type = "Text",
        unique_key = "DeletionJob_rootKind_rootId_key"
    )]
    pub root_kind: String,
    #[sea_orm(
        column_name = "rootId",
        column_type = "Text",
        unique_key = "DeletionJob_rootKind_rootId_key"
    )]
    pub root_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub phase: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cursor: Option<Json>,
    pub attempts: i32,
    #[sea_orm(column_name = "leaseUntil")]
    pub lease_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastError", column_type = "Text", nullable)]
    pub last_error: Option<String>,
    #[sea_orm(column_name = "requestedBy", column_type = "Text", nullable)]
    pub requested_by: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
