//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "EventSetup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(
        column_name = "eventId",
        column_type = "Text",
        unique_key = "EventSetup_eventId_variant_key"
    )]
    pub event_id: String,
    #[sea_orm(column_type = "Text", unique_key = "EventSetup_eventId_variant_key")]
    pub variant: String,
    #[sea_orm(column_name = "eventVersion", column_type = "Text")]
    pub event_version: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(column_name = "boardVersion", column_type = "Text", nullable)]
    pub board_version: Option<String>,
    #[sea_orm(column_name = "setupStatus", column_type = "Text", nullable)]
    pub setup_status: Option<String>,
    #[sea_orm(column_name = "lastSetupAt")]
    pub last_setup_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastSetupError", column_type = "Text", nullable)]
    pub last_setup_error: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: BelongsTo<super::event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
