//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "Event_appId_route_key"
    )]
    pub app_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "eventType", column_type = "Text")]
    pub event_type: String,
    pub active: bool,
    pub priority: i32,
    #[sea_orm(column_name = "boardId", column_type = "Text", nullable)]
    pub board_id: Option<String>,
    #[sea_orm(column_name = "boardVersion", column_type = "Text", nullable)]
    pub board_version: Option<String>,
    #[sea_orm(column_name = "nodeId", column_type = "Text", nullable)]
    pub node_id: Option<String>,
    #[sea_orm(column_name = "pageId", column_type = "Text", nullable)]
    pub page_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique_key = "Event_appId_route_key")]
    pub route: Option<String>,
    #[sea_orm(column_name = "isDefault")]
    pub is_default: bool,
    #[sea_orm(column_name = "eventVersion", column_type = "Text")]
    pub event_version: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub variables: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub inputs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub notes: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub canary: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "executionMode", column_type = "Text")]
    pub execution_mode: String,
    #[sea_orm(column_name = "lastSetupAt")]
    pub last_setup_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastSetupError", column_type = "Text", nullable)]
    pub last_setup_error: Option<String>,
    #[sea_orm(column_name = "lastSetupVersion", column_type = "Text", nullable)]
    pub last_setup_version: Option<String>,
    #[sea_orm(column_name = "setupStatus", column_type = "Text", nullable)]
    pub setup_status: Option<String>,
    #[sea_orm(
        column_name = "correlationMappings",
        column_type = "JsonBinary",
        nullable
    )]
    pub correlation_mappings: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub exposure: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub variants: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub event_aliases: HasMany<super::event_alias::Entity>,
    #[sea_orm(has_many)]
    pub event_remote_auths: HasMany<super::event_remote_auth::Entity>,
    #[sea_orm(has_many)]
    pub event_remote_registrations: HasMany<super::event_remote_registration::Entity>,
    #[sea_orm(has_many)]
    pub event_setups: HasMany<super::event_setup::Entity>,
    #[sea_orm(has_one)]
    pub event_sink: HasOne<super::event_sink::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
