//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "EventSink")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "eventId", column_type = "Text", unique)]
    pub event_id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "EventSink_appId_path_method_key"
    )]
    pub app_id: String,
    #[sea_orm(column_name = "sinkType", column_type = "Text")]
    pub sink_type: String,
    pub active: bool,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "EventSink_appId_path_method_key"
    )]
    pub path: Option<String>,
    #[sea_orm(column_name = "authToken", column_type = "Text", nullable)]
    pub auth_token: Option<String>,
    #[sea_orm(column_name = "webhookSecret", column_type = "Text", nullable)]
    pub webhook_secret: Option<String>,
    #[sea_orm(column_name = "cronExpression", column_type = "Text", nullable)]
    pub cron_expression: Option<String>,
    #[sea_orm(column_name = "cronTimezone", column_type = "Text", nullable)]
    pub cron_timezone: Option<String>,
    #[sea_orm(column_name = "patEncrypted", column_type = "Text", nullable)]
    pub pat_encrypted: Option<String>,
    #[sea_orm(column_name = "oauthTokensEncrypted", column_type = "Text", nullable)]
    pub oauth_tokens_encrypted: Option<String>,
    #[sea_orm(column_name = "profileJson", column_type = "JsonBinary", nullable)]
    pub profile_json: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "EventSink_appId_path_method_key"
    )]
    pub method: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: BelongsTo<super::event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
