//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "EventRemoteRegistration")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "eventId", column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_name = "eventVersion", column_type = "Text")]
    pub event_version: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub method: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_name = "nodeId", column_type = "Text", nullable)]
    pub node_id: Option<String>,
    #[sea_orm(column_name = "schemaJson", column_type = "JsonBinary", nullable)]
    pub schema_json: Option<Json>,
    #[sea_orm(column_name = "extrasJson", column_type = "JsonBinary", nullable)]
    pub extras_json: Option<Json>,
    #[sea_orm(column_name = "authId", column_type = "Text", nullable)]
    pub auth_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub variant: String,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: BelongsTo<super::event::Entity>,
    #[sea_orm(
        belongs_to,
        from = "auth_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub event_remote_auth: BelongsTo<Option<super::event_remote_auth::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
