//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "EventAlias")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub slug: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "EventAlias_appId_eventId_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_name = "eventId",
        column_type = "Text",
        unique_key = "EventAlias_appId_eventId_key"
    )]
    pub event_id: String,
    #[sea_orm(column_name = "createdBy", column_type = "Text", nullable)]
    pub created_by: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: BelongsTo<super::event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
