//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "ExecutionUsageTracking")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub instance: Option<String>,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(column_name = "nodeId", column_type = "Text")]
    pub node_id: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    pub microseconds: i64,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "technicalUserId", column_type = "Text", nullable)]
    pub technical_user_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::ExecutionStatus,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "technical_user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub technical_user: BelongsTo<Option<super::technical_user::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
