//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "ExecutionRunCallerApp")]
pub struct Model {
    #[sea_orm(
        column_name = "runId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub run_id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i32,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub execution_run: BelongsTo<super::execution_run::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
