//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "ExecutionRun")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_name = "eventId", column_type = "Text", nullable)]
    pub event_id: Option<String>,
    #[sea_orm(column_name = "nodeId", column_type = "Text", nullable)]
    pub node_id: Option<String>,
    #[sea_orm(column_name = "logLevel")]
    pub log_level: i32,
    #[sea_orm(column_name = "inputPayloadLen")]
    pub input_payload_len: i64,
    #[sea_orm(column_name = "inputPayloadKey", column_type = "Text", nullable)]
    pub input_payload_key: Option<String>,
    #[sea_orm(column_name = "outputPayloadLen")]
    pub output_payload_len: i64,
    #[sea_orm(column_name = "errorMessage", column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub progress: i32,
    #[sea_orm(column_name = "currentStep", column_type = "Text", nullable)]
    pub current_step: Option<String>,
    #[sea_orm(column_name = "startedAt")]
    pub started_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "technicalUserId", column_type = "Text", nullable)]
    pub technical_user_id: Option<String>,
    #[sea_orm(column_name = "correlationKeys", column_type = "JsonBinary", nullable)]
    pub correlation_keys: Option<Json>,
    #[sea_orm(column_name = "parentRunId", column_type = "Text", nullable)]
    pub parent_run_id: Option<String>,
    #[sea_orm(column_name = "traceId", column_type = "Text", nullable)]
    pub trace_id: Option<String>,
    #[sea_orm(column_name = "regressionRunId", column_type = "Text", nullable)]
    pub regression_run_id: Option<String>,
    #[sea_orm(column_name = "shadowOfRunId", column_type = "Text", nullable)]
    pub shadow_of_run_id: Option<String>,
    #[sea_orm(column_name = "variantName", column_type = "Text", nullable)]
    pub variant_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::RunStatus,
    #[sea_orm(column_type = "Text")]
    pub mode: crate::sea_orm_active_enums::RunMode,
    #[sea_orm(column_name = "callerAppChain", column_type = "JsonBinary", nullable)]
    pub caller_app_chain: Option<crate::json_types::StringList>,
    #[sea_orm(column_name = "runVariant", column_type = "Text")]
    pub run_variant: crate::sea_orm_active_enums::RunVariant,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub execution_events: HasMany<super::execution_event::Entity>,
    #[sea_orm(has_many)]
    pub execution_run_caller_apps: HasMany<super::execution_run_caller_app::Entity>,
    #[sea_orm(
        belongs_to,
        from = "technical_user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub technical_user: BelongsTo<Option<super::technical_user::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
