//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "ExecutionEvent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "runId", column_type = "Text")]
    pub run_id: String,
    pub sequence: i32,
    #[sea_orm(column_name = "eventType", column_type = "Text")]
    pub event_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub delivered: bool,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "payloadRef", column_type = "Text", nullable)]
    pub payload_ref: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub execution_run: BelongsTo<super::execution_run::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
