//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Feedback")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "templateId", column_type = "Text", nullable)]
    pub template_id: Option<String>,
    #[sea_orm(column_name = "eventId", column_type = "Text", nullable)]
    pub event_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub context: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
    pub rating: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "template_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub template: BelongsTo<Option<super::template::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
