//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "FlowScriptApplyFailure")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(column_name = "layerId", column_type = "Text", nullable)]
    pub layer_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub origin: String,
    #[sea_orm(column_type = "Text")]
    pub outcome: String,
    #[sea_orm(column_type = "Text")]
    pub cause: String,
    #[sea_orm(column_name = "errorMessage", column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub diagnostics: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub corrections: Option<Json>,
    #[sea_orm(column_name = "commandCount")]
    pub command_count: i32,
    #[sea_orm(column_name = "allowDeletions")]
    pub allow_deletions: bool,
    #[sea_orm(column_type = "Text")]
    pub flowscript: String,
    #[sea_orm(column_name = "flowscriptChars")]
    pub flowscript_chars: i32,
    #[sea_orm(column_name = "droppedValues")]
    pub dropped_values: i32,
    #[sea_orm(column_name = "redactedLiterals")]
    pub redacted_literals: i32,
    pub truncated: bool,
    #[sea_orm(column_name = "appVersion", column_type = "Text", nullable)]
    pub app_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform: Option<String>,
    #[sea_orm(column_name = "traceId", column_type = "Text", nullable)]
    pub trace_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
