//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "ForkJob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "sourceAppId", column_type = "Text")]
    pub source_app_id: String,
    #[sea_orm(column_name = "destAppId", column_type = "Text")]
    pub dest_app_id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub step: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cursor: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub policy: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub report: Option<Json>,
    #[sea_orm(column_name = "lastError", column_type = "Text", nullable)]
    pub last_error: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
