//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LeaderboardOptIn")]
pub struct Model {
    #[sea_orm(
        column_name = "userId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub user_id: String,
    #[sea_orm(column_name = "displayName", column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_name = "isOptedIn")]
    pub is_opted_in: bool,
    #[sea_orm(column_name = "totalPoints")]
    pub total_points: i32,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
