//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LearningPathCourse")]
pub struct Model {
    #[sea_orm(
        column_name = "pathId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub path_id: String,
    #[sea_orm(
        column_name = "courseId",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub course_id: String,
    pub position: i32,
    #[sea_orm(
        belongs_to,
        from = "course_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course: BelongsTo<super::course::Entity>,
    #[sea_orm(
        belongs_to,
        from = "path_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub learning_path: BelongsTo<super::learning_path::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
