//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LessonAppRef")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "lessonId", column_type = "Text")]
    pub lesson_id: String,
    #[sea_orm(column_name = "appAlias", column_type = "Text", nullable)]
    pub app_alias: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub target: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub label: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub kind: crate::sea_orm_active_enums::LessonAppRefKind,
    #[sea_orm(
        belongs_to,
        from = "lesson_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub lesson: BelongsTo<super::lesson::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
