//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Lesson")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "moduleId", column_type = "Text")]
    pub module_id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_name = "videoUrl", column_type = "Text", nullable)]
    pub video_url: Option<String>,
    #[sea_orm(column_name = "estimatedMinutes")]
    pub estimated_minutes: i32,
    #[sea_orm(column_name = "isOptional")]
    pub is_optional: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub challenges: HasMany<super::challenge::Entity>,
    #[sea_orm(
        belongs_to,
        from = "module_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course_module: BelongsTo<super::course_module::Entity>,
    #[sea_orm(has_many)]
    pub lesson_app_refs: HasMany<super::lesson_app_ref::Entity>,
    #[sea_orm(has_many)]
    pub user_lesson_progresses: HasMany<super::user_lesson_progress::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
