//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "LLMUsageTracking")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "modelId", column_type = "Text")]
    pub model_id: String,
    #[sea_orm(column_name = "tokenIn")]
    pub token_in: i64,
    #[sea_orm(column_name = "tokenOut")]
    pub token_out: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub latency: Option<f64>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    pub price: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub endpoint: Option<String>,
    #[sea_orm(column_name = "invocationId", column_type = "Text", nullable)]
    pub invocation_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_name = "providerRequestId", column_type = "Text", nullable)]
    pub provider_request_id: Option<String>,
    #[sea_orm(column_name = "rawUsage", column_type = "JsonBinary", nullable)]
    pub raw_usage: Option<Json>,
    #[sea_orm(column_name = "technicalUserId", column_type = "Text", nullable)]
    pub technical_user_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "technical_user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub technical_user: BelongsTo<Option<super::technical_user::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
