//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Membership")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "Membership_userId_appId_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "Membership_userId_appId_key"
    )]
    pub app_id: String,
    #[sea_orm(column_name = "roleId", column_type = "Text")]
    pub role_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "joinedVia", column_type = "Text", nullable)]
    pub joined_via: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub app_packages: HasMany<super::app_package::Entity>,
    #[sea_orm(has_many)]
    pub invitations: HasMany<super::invitation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub role: BelongsTo<super::role::Entity>,
    #[sea_orm(has_many)]
    pub technical_users: HasMany<super::technical_user::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
