//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub lang: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "longDescription", column_type = "Text", nullable)]
    pub long_description: Option<String>,
    #[sea_orm(column_name = "releaseNotes", column_type = "Text", nullable)]
    pub release_notes: Option<String>,
    #[sea_orm(column_name = "useCase", column_type = "Text", nullable)]
    pub use_case: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail: Option<String>,
    #[sea_orm(column_name = "ageRating")]
    pub age_rating: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub website: Option<String>,
    #[sea_orm(column_name = "supportUrl", column_type = "Text", nullable)]
    pub support_url: Option<String>,
    #[sea_orm(column_name = "docsUrl", column_type = "Text", nullable)]
    pub docs_url: Option<String>,
    #[sea_orm(
        column_name = "organizationSpecificValues",
        column_type = "JsonBinary",
        nullable
    )]
    pub organization_specific_values: Option<Json>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "bitId", column_type = "Text", nullable)]
    pub bit_id: Option<String>,
    #[sea_orm(column_name = "courseId", column_type = "Text", nullable)]
    pub course_id: Option<String>,
    #[sea_orm(column_name = "templateId", column_type = "Text", nullable)]
    pub template_id: Option<String>,
    #[sea_orm(column_name = "widgetId", column_type = "Text", nullable)]
    pub widget_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "wasmPackageId", column_type = "Text", nullable)]
    pub wasm_package_id: Option<String>,
    #[sea_orm(column_name = "groupId", column_type = "Text", nullable)]
    pub group_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<crate::json_types::StringList>,
    #[sea_orm(column_name = "previewMedia", column_type = "JsonBinary", nullable)]
    pub preview_media: Option<crate::json_types::StringList>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app_group: BelongsTo<Option<super::app_group::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "bit_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bit: BelongsTo<Option<super::bit::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "course_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub course: BelongsTo<Option<super::course::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "template_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub template: BelongsTo<Option<super::template::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "wasm_package_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub wasm_package: BelongsTo<Option<super::wasm_package::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "widget_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub widget: BelongsTo<Option<super::widget::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
