//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "PublicationLog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "requestId", column_type = "Text")]
    pub request_id: String,
    #[sea_orm(column_name = "authorId", column_type = "Text", nullable)]
    pub author_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub visibility: Option<crate::sea_orm_active_enums::Visibility>,
    #[sea_orm(
        belongs_to,
        from = "request_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub publication_request: BelongsTo<super::publication_request::Entity>,
    #[sea_orm(
        belongs_to,
        from = "author_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
