//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "PublicationRequest")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "approverId", column_type = "Text", nullable)]
    pub approver_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "aiActAssessmentId", column_type = "Text", nullable)]
    pub ai_act_assessment_id: Option<String>,
    #[sea_orm(column_name = "groupId", column_type = "Text", nullable)]
    pub group_id: Option<String>,
    #[sea_orm(column_name = "targetVisibility", column_type = "Text")]
    pub target_visibility: crate::sea_orm_active_enums::Visibility,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::PublicationRequestStatus,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<Option<super::app::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app_group: BelongsTo<Option<super::app_group::Entity>>,
    #[sea_orm(has_many)]
    pub publication_logs: HasMany<super::publication_log::Entity>,
    #[sea_orm(
        belongs_to,
        from = "approver_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
