//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "PushNotificationTarget")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "PushNotificationTarget_userId_deviceId_provider_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_name = "deviceId",
        column_type = "Text",
        unique_key = "PushNotificationTarget_userId_deviceId_provider_key"
    )]
    pub device_id: String,
    #[sea_orm(column_name = "tokenEncrypted", column_type = "Text")]
    pub token_encrypted: String,
    #[sea_orm(column_name = "endpointArn", column_type = "Text", nullable)]
    pub endpoint_arn: Option<String>,
    #[sea_orm(column_name = "installationId", column_type = "Text", nullable)]
    pub installation_id: Option<String>,
    #[sea_orm(column_name = "channelId", column_type = "Text", nullable)]
    pub channel_id: Option<String>,
    #[sea_orm(column_name = "deviceName", column_type = "Text", nullable)]
    pub device_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_name = "pushEnabled")]
    pub push_enabled: bool,
    #[sea_orm(column_name = "lastRegisteredAt")]
    pub last_registered_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "lastSeenAt")]
    pub last_seen_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "invalidatedAt")]
    pub invalidated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "invalidationReason", column_type = "Text", nullable)]
    pub invalidation_reason: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "failureCount")]
    pub failure_count: i32,
    #[sea_orm(column_type = "Text")]
    pub platform: crate::sea_orm_active_enums::PushNotificationTargetPlatform,
    #[sea_orm(
        column_type = "Text",
        unique_key = "PushNotificationTarget_userId_deviceId_provider_key"
    )]
    pub provider: crate::sea_orm_active_enums::PushNotificationTargetProvider,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
