//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "RegressionSuite")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "appId",
        column_type = "Text",
        unique_key = "RegressionSuite_appId_eventId_key"
    )]
    pub app_id: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(
        column_name = "eventId",
        column_type = "Text",
        nullable,
        unique_key = "RegressionSuite_appId_eventId_key"
    )]
    pub event_id: Option<String>,
    #[sea_orm(column_name = "nodeId", column_type = "Text")]
    pub node_id: String,
    #[sea_orm(column_name = "triggerOnPublish")]
    pub trigger_on_publish: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub schedule: Option<String>,
    #[sea_orm(column_name = "gateMode", column_type = "Text")]
    pub gate_mode: String,
    #[sea_orm(column_name = "allowLiveSideEffects")]
    pub allow_live_side_effects: bool,
    #[sea_orm(column_name = "nextRunAt")]
    pub next_run_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
