//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "RegressionSuiteRun")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "suiteId", column_type = "Text")]
    pub suite_id: String,
    #[sea_orm(column_name = "boardId", column_type = "Text")]
    pub board_id: String,
    #[sea_orm(column_name = "boardVersion", column_type = "Text")]
    pub board_version: String,
    #[sea_orm(column_type = "Text")]
    pub trigger: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub regressed: i32,
    pub fixed: i32,
    #[sea_orm(column_name = "stillFailing")]
    pub still_failing: i32,
    pub ok: i32,
    pub skipped: i32,
    #[sea_orm(column_name = "startedAt")]
    pub started_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub regression_case_results: HasMany<super::regression_case_result::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
