//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "SinkToken")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "sinkType", column_type = "Text")]
    pub sink_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub revoked: bool,
    #[sea_orm(column_name = "revokedAt")]
    pub revoked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "revokedBy", column_type = "Text", nullable)]
    pub revoked_by: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
