//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "SolutionLog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "solutionId", column_type = "Text")]
    pub solution_id: String,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "solution_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub solution_request: BelongsTo<super::solution_request::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
