//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "SolutionLog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "solutionId", column_type = "Text")]
    pub solution_id: String,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::solution_request::Entity",
        from = "Column::SolutionId",
        to = "super::solution_request::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SolutionRequest,
}

impl Related<super::solution_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolutionRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
