//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "StripeEvent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "eventType", column_type = "Text")]
    pub event_type: String,
    #[sea_orm(column_name = "processedAt")]
    pub processed_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
