//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TechnicalUser")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub key: String,
    #[sea_orm(column_name = "roleId", column_type = "Text", nullable)]
    pub role_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "validUntil")]
    pub valid_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "creatorMembershipId", column_type = "Text", nullable)]
    pub creator_membership_id: Option<String>,
    #[sea_orm(column_name = "creatorUserId", column_type = "Text", nullable)]
    pub creator_user_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub embedding_usage_trackings: HasMany<super::embedding_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub execution_runs: HasMany<super::execution_run::Entity>,
    #[sea_orm(has_many)]
    pub execution_usage_trackings: HasMany<super::execution_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub llm_usage_trackings: HasMany<super::llm_usage_tracking::Entity>,
    #[sea_orm(
        belongs_to,
        from = "creator_membership_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub membership: BelongsTo<Option<super::membership::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub role: BelongsTo<Option<super::role::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "creator_user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
