//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryPerfDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "TelemetryPerfDaily_day_metric_source_key")]
    pub day: DateTimeWithTimeZone,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryPerfDaily_day_metric_source_key"
    )]
    pub metric: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryPerfDaily_day_metric_source_key"
    )]
    pub source: String,
    pub count: i32,
    #[sea_orm(column_type = "Double")]
    pub p50: f64,
    #[sea_orm(column_type = "Double")]
    pub p75: f64,
    #[sea_orm(column_type = "Double")]
    pub p95: f64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
