//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryFlowpilotFailureDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "TelemetryFlowpilotFailureDaily_day_kind_tool_code_message_key")]
    pub day: DateTimeWithTimeZone,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryFlowpilotFailureDaily_day_kind_tool_code_message_key"
    )]
    pub kind: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryFlowpilotFailureDaily_day_kind_tool_code_message_key"
    )]
    pub tool: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryFlowpilotFailureDaily_day_kind_tool_code_message_key"
    )]
    pub code: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryFlowpilotFailureDaily_day_kind_tool_code_message_key"
    )]
    pub message: String,
    pub count: i64,
    pub installs: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
