//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryIssue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub fingerprint: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub culprit: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub level: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_name = "resolvedInRelease", column_type = "Text", nullable)]
    pub resolved_in_release: Option<String>,
    #[sea_orm(column_name = "firstSeen")]
    pub first_seen: DateTimeWithTimeZone,
    #[sea_orm(column_name = "lastSeen")]
    pub last_seen: DateTimeWithTimeZone,
    #[sea_orm(column_name = "eventCount")]
    pub event_count: i32,
    #[sea_orm(column_name = "installCount")]
    pub install_count: i32,
    #[sea_orm(column_name = "firstRelease", column_type = "Text", nullable)]
    pub first_release: Option<String>,
    #[sea_orm(column_name = "lastRelease", column_type = "Text", nullable)]
    pub last_release: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
