//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetrySpan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "traceId", column_type = "Text")]
    pub trace_id: String,
    #[sea_orm(column_name = "spanId", column_type = "Text")]
    pub span_id: String,
    #[sea_orm(column_name = "parentSpanId", column_type = "Text", nullable)]
    pub parent_span_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_name = "anonId", column_type = "Text", nullable)]
    pub anon_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub release: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform: Option<String>,
    #[sea_orm(column_name = "startedAt")]
    pub started_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "durationMs")]
    pub duration_ms: i32,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attributes: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
