//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryRelease")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryRelease_version_source_key"
    )]
    pub version: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryRelease_version_source_key"
    )]
    pub source: String,
    #[sea_orm(column_name = "commitSha", column_type = "Text", nullable)]
    pub commit_sha: Option<String>,
    #[sea_orm(column_name = "firstSeenAt")]
    pub first_seen_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
