//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryLlmCall")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "anonId", column_type = "Text", nullable)]
    pub anon_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub release: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub provider: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub operation: String,
    #[sea_orm(column_name = "durationMs")]
    pub duration_ms: i32,
    #[sea_orm(column_name = "promptTokens")]
    pub prompt_tokens: Option<i32>,
    #[sea_orm(column_name = "completionTokens")]
    pub completion_tokens: Option<i32>,
    #[sea_orm(column_name = "totalTokens")]
    pub total_tokens: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_name = "errorKind", column_type = "Text", nullable)]
    pub error_kind: Option<String>,
    #[sea_orm(column_name = "toolCalls")]
    pub tool_calls: i32,
    pub streamed: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
