//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetrySourceMap")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetrySourceMap_release_source_fileName_key"
    )]
    pub release: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetrySourceMap_release_source_fileName_key"
    )]
    pub source: String,
    #[sea_orm(
        column_name = "fileName",
        column_type = "Text",
        unique_key = "TelemetrySourceMap_release_source_fileName_key"
    )]
    pub file_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub map: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "mapRef", column_type = "Text", nullable)]
    pub map_ref: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
