//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryAlertEvent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "ruleId", column_type = "Text")]
    pub rule_id: String,
    #[sea_orm(column_name = "ruleName", column_type = "Text")]
    pub rule_name: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub threshold: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    #[sea_orm(column_name = "acknowledgedAt")]
    pub acknowledged_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
