//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetrySessionDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "TelemetrySessionDaily_day_release_source_key")]
    pub day: DateTimeWithTimeZone,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetrySessionDaily_day_release_source_key"
    )]
    pub release: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetrySessionDaily_day_release_source_key"
    )]
    pub source: String,
    pub sessions: i32,
    #[sea_orm(column_name = "crashedSessions")]
    pub crashed_sessions: i32,
    #[sea_orm(column_name = "erroredSessions")]
    pub errored_sessions: i32,
    pub installs: i32,
    #[sea_orm(column_name = "crashedInstalls")]
    pub crashed_installs: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
