//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryFlowpilotDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique)]
    pub day: DateTimeWithTimeZone,
    #[sea_orm(column_name = "runsStarted")]
    pub runs_started: i64,
    #[sea_orm(column_name = "runsSucceeded")]
    pub runs_succeeded: i64,
    #[sea_orm(column_name = "runsFailed")]
    pub runs_failed: i64,
    #[sea_orm(column_name = "runsCancelled")]
    pub runs_cancelled: i64,
    #[sea_orm(column_name = "plansAssessed")]
    pub plans_assessed: i64,
    #[sea_orm(column_name = "plansFeasible")]
    pub plans_feasible: i64,
    #[sea_orm(column_name = "plansInfeasible")]
    pub plans_infeasible: i64,
    #[sea_orm(column_name = "attemptsTotal")]
    pub attempts_total: i64,
    #[sea_orm(column_name = "attemptsParseValid")]
    pub attempts_parse_valid: i64,
    #[sea_orm(column_name = "attemptsTypedValid")]
    pub attempts_typed_valid: i64,
    #[sea_orm(column_name = "attemptsReconcileValid")]
    pub attempts_reconcile_valid: i64,
    #[sea_orm(column_name = "attemptsApplied")]
    pub attempts_applied: i64,
    #[sea_orm(column_name = "queuedReviews")]
    pub queued_reviews: i64,
    #[sea_orm(column_name = "applyDispositions")]
    pub apply_dispositions: i64,
    #[sea_orm(column_name = "dismissedDispositions")]
    pub dismissed_dispositions: i64,
    #[sea_orm(column_name = "staleDispositions")]
    pub stale_dispositions: i64,
    #[sea_orm(column_name = "errorDispositions")]
    pub error_dispositions: i64,
    #[sea_orm(column_name = "diagnosticOccurrences")]
    pub diagnostic_occurrences: i64,
    #[sea_orm(column_name = "repeatedDiagnosticOccurrences")]
    pub repeated_diagnostic_occurrences: i64,
    #[sea_orm(column_name = "validationRegressions")]
    pub validation_regressions: i64,
    #[sea_orm(column_name = "boardsInspected")]
    pub boards_inspected: i64,
    #[sea_orm(column_name = "emptyBoardsAfterRun")]
    pub empty_boards_after_run: i64,
    pub installs: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "dataApplyFailures")]
    pub data_apply_failures: i64,
    #[sea_orm(column_name = "failuresTotal")]
    pub failures_total: i64,
    #[sea_orm(column_name = "flowscriptApplyFailures")]
    pub flowscript_apply_failures: i64,
    #[sea_orm(column_name = "pageApplyFailures")]
    pub page_apply_failures: i64,
    #[sea_orm(column_name = "runFailures")]
    pub run_failures: i64,
    #[sea_orm(column_name = "subagentDispatchFailures")]
    pub subagent_dispatch_failures: i64,
    #[sea_orm(column_name = "toolFailures")]
    pub tool_failures: i64,
    #[sea_orm(column_name = "widgetApplyFailures")]
    pub widget_apply_failures: i64,
}

impl ActiveModelBehavior for ActiveModel {}
