//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryPerfMetric")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "anonId", column_type = "Text")]
    pub anon_id: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub release: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub metric: String,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: Option<String>,
    #[sea_orm(column_name = "clientTs")]
    pub client_ts: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
