//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryAlertRule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub metric: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub comparator: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub threshold: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub mode: String,
    #[sea_orm(column_name = "windowMinutes")]
    pub window_minutes: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub sensitivity: Option<f64>,
    #[sea_orm(column_name = "minSamples")]
    pub min_samples: i32,
    pub enabled: bool,
    #[sea_orm(column_name = "notifyEmail")]
    pub notify_email: bool,
    #[sea_orm(column_name = "notifyPush")]
    pub notify_push: bool,
    #[sea_orm(column_name = "lastEvaluatedAt")]
    pub last_evaluated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastTriggeredAt")]
    pub last_triggered_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastValue", column_type = "Double", nullable)]
    pub last_value: Option<f64>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
