//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "TelemetryLlmDaily")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "TelemetryLlmDaily_day_provider_model_source_key")]
    pub day: DateTimeWithTimeZone,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryLlmDaily_day_provider_model_source_key"
    )]
    pub provider: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryLlmDaily_day_provider_model_source_key"
    )]
    pub model: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "TelemetryLlmDaily_day_provider_model_source_key"
    )]
    pub source: String,
    pub calls: i32,
    pub errors: i32,
    #[sea_orm(column_name = "promptTokens")]
    pub prompt_tokens: i64,
    #[sea_orm(column_name = "completionTokens")]
    pub completion_tokens: i64,
    #[sea_orm(column_name = "totalTokens")]
    pub total_tokens: i64,
    #[sea_orm(column_name = "durationSumMs")]
    pub duration_sum_ms: i64,
    #[sea_orm(column_name = "durationMaxMs")]
    pub duration_max_ms: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
