//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "Template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i64,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i64,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "app_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub app: BelongsTo<super::app::Entity>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(has_many)]
    pub feedbacks: HasMany<super::feedback::Entity>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
