//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UsageInvocation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub endpoint: Option<String>,
    #[sea_orm(column_name = "modelId", column_type = "Text", nullable)]
    pub model_id: Option<String>,
    #[sea_orm(column_name = "providerRequestId", column_type = "Text", nullable)]
    pub provider_request_id: Option<String>,
    #[sea_orm(column_name = "estimatedTokens")]
    pub estimated_tokens: i64,
    #[sea_orm(column_name = "estimatedCostMicroDollars")]
    pub estimated_cost_micro_dollars: i64,
    #[sea_orm(column_name = "inputTokens")]
    pub input_tokens: i64,
    #[sea_orm(column_name = "outputTokens")]
    pub output_tokens: i64,
    #[sea_orm(column_name = "embeddingTokens")]
    pub embedding_tokens: i64,
    #[sea_orm(column_name = "costMicroDollars")]
    pub cost_micro_dollars: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub latency: Option<f64>,
    #[sea_orm(column_name = "rawUsage", column_type = "JsonBinary", nullable)]
    pub raw_usage: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_name = "startedAt")]
    pub started_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "technicalUserId", column_type = "Text", nullable)]
    pub technical_user_id: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
