//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UsageLimitAuditLog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "actorUserId", column_type = "Text", nullable)]
    pub actor_user_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub before: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub after: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
