//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UsageAlert")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub severity: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub period: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    #[sea_orm(column_name = "appId", column_type = "Text", nullable)]
    pub app_id: Option<String>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_name = "thresholdPercent")]
    pub threshold_percent: Option<i32>,
    #[sea_orm(column_name = "currentCostMicroDollars")]
    pub current_cost_micro_dollars: Option<i64>,
    #[sea_orm(column_name = "currentTokens")]
    pub current_tokens: Option<i64>,
    #[sea_orm(column_name = "acknowledgedAt")]
    pub acknowledged_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "acknowledgedByUserId", column_type = "Text", nullable)]
    pub acknowledged_by_user_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
