//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UserBit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub repository: Option<String>,
    #[sea_orm(column_name = "downloadLink", column_type = "Text", nullable)]
    pub download_link: Option<String>,
    #[sea_orm(column_name = "fileName", column_type = "Text", nullable)]
    pub file_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hash: Option<String>,
    pub size: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parameters: Option<Json>,
    #[sea_orm(column_name = "secretsEncrypted", column_type = "Text", nullable)]
    pub secrets_encrypted: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub meta: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub r#type: crate::sea_orm_active_enums::BitType,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
