//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "User")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "stripeId", column_type = "Text", nullable, unique)]
    pub stripe_id: Option<String>,
    #[sea_orm(column_name = "trackingId", column_type = "Text", nullable, unique)]
    pub tracking_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub username: Option<String>,
    #[sea_orm(
        column_name = "preferredUsername",
        column_type = "Text",
        nullable,
        unique
    )]
    pub preferred_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    #[sea_orm(
        column_name = "additionalInformation",
        column_type = "JsonBinary",
        nullable
    )]
    pub additional_information: Option<Json>,
    pub permission: i64,
    #[sea_orm(column_name = "acceptedTermsVersion", column_type = "Text", nullable)]
    pub accepted_terms_version: Option<String>,
    #[sea_orm(column_name = "tutorialCompleted")]
    pub tutorial_completed: bool,
    #[sea_orm(column_name = "totalSize")]
    pub total_size: i64,
    #[sea_orm(column_name = "totalLLMPrice")]
    pub total_llm_price: i64,
    #[sea_orm(column_name = "totalEmbeddingPrice")]
    pub total_embedding_price: i64,
    #[sea_orm(column_name = "llmPriceTrackingMonth", column_type = "Text", nullable)]
    pub llm_price_tracking_month: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "devMode")]
    pub dev_mode: bool,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::UserStatus,
    #[sea_orm(column_type = "Text")]
    pub tier: crate::sea_orm_active_enums::UserTier,
    #[sea_orm(has_many)]
    pub app_purchases: HasMany<super::app_purchase::Entity>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(has_many)]
    pub embedding_usage_trackings: HasMany<super::embedding_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub execution_runs: HasMany<super::execution_run::Entity>,
    #[sea_orm(has_many)]
    pub execution_usage_trackings: HasMany<super::execution_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub feedbacks: HasMany<super::feedback::Entity>,
    #[sea_orm(has_many)]
    pub flow_script_apply_failures: HasMany<super::flow_script_apply_failure::Entity>,
    #[sea_orm(has_many)]
    pub invitations: HasMany<super::invitation::Entity>,
    #[sea_orm(has_many)]
    pub join_queues: HasMany<super::join_queue::Entity>,
    #[sea_orm(has_many)]
    pub llm_usage_trackings: HasMany<super::llm_usage_tracking::Entity>,
    #[sea_orm(has_many)]
    pub memberships: HasMany<super::membership::Entity>,
    #[sea_orm(has_many)]
    pub notifications: HasMany<super::notification::Entity>,
    #[sea_orm(has_many)]
    pub pats: HasMany<super::pat::Entity>,
    #[sea_orm(has_many)]
    pub profiles: HasMany<super::profile::Entity>,
    #[sea_orm(has_many)]
    pub publication_logs: HasMany<super::publication_log::Entity>,
    #[sea_orm(has_many)]
    pub publication_requests: HasMany<super::publication_request::Entity>,
    #[sea_orm(has_many)]
    pub push_notification_targets: HasMany<super::push_notification_target::Entity>,
    #[sea_orm(has_many)]
    pub technical_users: HasMany<super::technical_user::Entity>,
    #[sea_orm(has_many)]
    pub transactions: HasMany<super::transaction::Entity>,
    #[sea_orm(has_many)]
    pub user_bits: HasMany<super::user_bit::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_authors: HasMany<super::wasm_package_author::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_join_queues: HasMany<super::wasm_package_join_queue::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_purchases: HasMany<super::wasm_package_purchase::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_reviews: HasMany<super::wasm_package_review::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_users: HasMany<super::wasm_package_user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
