//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UserChallengeAttempt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_name = "challengeId", column_type = "Text")]
    pub challenge_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub submission: Json,
    #[sea_orm(column_name = "isCorrect")]
    pub is_correct: bool,
    #[sea_orm(column_name = "pointsAwarded")]
    pub points_awarded: i32,
    #[sea_orm(column_name = "attemptedAt")]
    pub attempted_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "challenge_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub challenge: BelongsTo<super::challenge::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
