//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "UserLessonProgress")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "UserLessonProgress_userId_lessonId_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_name = "lessonId",
        column_type = "Text",
        unique_key = "UserLessonProgress_userId_lessonId_key"
    )]
    pub lesson_id: String,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::LessonStatus,
    #[sea_orm(
        belongs_to,
        from = "lesson_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub lesson: BelongsTo<super::lesson::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
