//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackageVersion")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "packageId",
        column_type = "Text",
        unique_key = "WasmPackageVersion_packageId_version_key"
    )]
    pub package_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "WasmPackageVersion_packageId_version_key"
    )]
    pub version: String,
    #[sea_orm(column_name = "wasmPath", column_type = "Text")]
    pub wasm_path: String,
    #[sea_orm(column_name = "wasmHash", column_type = "Text")]
    pub wasm_hash: String,
    #[sea_orm(column_name = "wasmSize")]
    pub wasm_size: i64,
    #[sea_orm(column_name = "releaseNotes", column_type = "Text", nullable)]
    pub release_notes: Option<String>,
    #[sea_orm(column_name = "minFlowLikeVersion", column_type = "Text", nullable)]
    pub min_flow_like_version: Option<String>,
    pub yanked: bool,
    #[sea_orm(column_name = "publishedAt")]
    pub published_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "approvedAt")]
    pub approved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "compilationError", column_type = "Text", nullable)]
    pub compilation_error: Option<String>,
    #[sea_orm(column_name = "duplicateFlagged")]
    pub duplicate_flagged: bool,
    #[sea_orm(column_name = "duplicateOfPackageId", column_type = "Text", nullable)]
    pub duplicate_of_package_id: Option<String>,
    #[sea_orm(column_name = "duplicateOfVersion", column_type = "Text", nullable)]
    pub duplicate_of_version: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub nodes: Json,
    #[sea_orm(column_name = "widgetBundleHash", column_type = "Text", nullable)]
    pub widget_bundle_hash: Option<String>,
    #[sea_orm(column_name = "widgetBundleSize")]
    pub widget_bundle_size: Option<i64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub widgets: Json,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::WasmPackageStatus,
    #[sea_orm(column_name = "compilationStatus", column_type = "Text")]
    pub compilation_status: crate::sea_orm_active_enums::WasmCompilationStatus,
    #[sea_orm(
        column_name = "compiledPlatforms",
        column_type = "JsonBinary",
        nullable
    )]
    pub compiled_platforms: Option<crate::json_types::StringList>,
    #[sea_orm(
        column_name = "supportedWasmtimeVersions",
        column_type = "JsonBinary",
        nullable
    )]
    pub supported_wasmtime_versions: Option<crate::json_types::StringList>,
    #[sea_orm(
        belongs_to,
        from = "package_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub wasm_package: BelongsTo<super::wasm_package::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
