//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackageReview")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "packageId", column_type = "Text")]
    pub package_id: String,
    #[sea_orm(column_name = "reviewerId", column_type = "Text")]
    pub reviewer_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    #[sea_orm(column_name = "internalNote", column_type = "Text", nullable)]
    pub internal_note: Option<String>,
    #[sea_orm(column_name = "securityScore")]
    pub security_score: Option<i32>,
    #[sea_orm(column_name = "codeQualityScore")]
    pub code_quality_score: Option<i32>,
    #[sea_orm(column_name = "documentationScore")]
    pub documentation_score: Option<i32>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub action: crate::sea_orm_active_enums::WasmReviewAction,
    #[sea_orm(
        belongs_to,
        from = "reviewer_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        from = "package_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub wasm_package: BelongsTo<super::wasm_package::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
