//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackageInvitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "packageId",
        column_type = "Text",
        unique_key = "WasmPackageInvitation_packageId_inviteeId_key"
    )]
    pub package_id: String,
    #[sea_orm(column_name = "invitedById", column_type = "Text")]
    pub invited_by_id: String,
    #[sea_orm(
        column_name = "inviteeId",
        column_type = "Text",
        unique_key = "WasmPackageInvitation_packageId_inviteeId_key"
    )]
    pub invitee_id: String,
    pub permission: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::InvitationStatus,
    #[sea_orm(
        belongs_to,
        relation_enum = "User2",
        from = "invited_by_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub user_2: BelongsTo<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User1",
        from = "invitee_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub user_1: BelongsTo<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        from = "package_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub wasm_package: BelongsTo<super::wasm_package::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
