//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackage")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "WasmPackage_id_version_key"
    )]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", unique_key = "WasmPackage_id_version_key")]
    pub version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub homepage: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub repository: Option<String>,
    pub verified: bool,
    #[sea_orm(column_name = "downloadCount")]
    pub download_count: i64,
    #[sea_orm(column_name = "wasmPath", column_type = "Text")]
    pub wasm_path: String,
    #[sea_orm(column_name = "wasmHash", column_type = "Text")]
    pub wasm_hash: String,
    #[sea_orm(column_name = "wasmSize")]
    pub wasm_size: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub nodes: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Json,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "publishedAt")]
    pub published_at: Option<DateTimeWithTimeZone>,
    pub price: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub readme: Option<String>,
    #[sea_orm(column_name = "avgRating", column_type = "Double", nullable)]
    pub avg_rating: Option<f64>,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i64,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i64,
    #[sea_orm(column_name = "widgetBundleHash", column_type = "Text", nullable)]
    pub widget_bundle_hash: Option<String>,
    #[sea_orm(column_name = "widgetBundleSize")]
    pub widget_bundle_size: Option<i64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub widgets: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub keywords: Option<crate::json_types::StringList>,
    #[sea_orm(column_type = "Text")]
    pub status: crate::sea_orm_active_enums::WasmPackageStatus,
    #[sea_orm(column_type = "Text")]
    pub visibility: crate::sea_orm_active_enums::WasmPackageVisibility,
    #[sea_orm(column_name = "primaryCategory", column_type = "Text", nullable)]
    pub primary_category: Option<crate::sea_orm_active_enums::WasmPackageCategory>,
    #[sea_orm(column_name = "secondaryCategory", column_type = "Text", nullable)]
    pub secondary_category: Option<crate::sea_orm_active_enums::WasmPackageCategory>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(has_many)]
    pub metas: HasMany<super::meta::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_authors: HasMany<super::wasm_package_author::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_invitations: HasMany<super::wasm_package_invitation::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_join_queues: HasMany<super::wasm_package_join_queue::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_purchases: HasMany<super::wasm_package_purchase::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_reviews: HasMany<super::wasm_package_review::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_users: HasMany<super::wasm_package_user::Entity>,
    #[sea_orm(has_many)]
    pub wasm_package_versions: HasMany<super::wasm_package_version::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
