//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WeeklyChallenge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "weekIso", column_type = "Text", unique)]
    pub week_iso: String,
    #[sea_orm(column_name = "challengeId", column_type = "Text")]
    pub challenge_id: String,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "challenge_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub challenge: BelongsTo<super::challenge::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
