[package]
name = "aws-compiler-lambda"
version = "0.1.0"
edition = "2021"
description = "Flow-Like AWS Lambda WASM Compiler (SQS consumer)"

[dependencies]
flow-like-compiler.workspace = true

aws_lambda_events = { version = "0.16.0", default-features = false, features = ["sqs"] }
lambda_runtime.workspace = true
mimalloc.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing-subscriber.workspace = true
tokio = { version = "1", features = ["full"] }
