WITH risks (
    rank,
    risk_id,
    control_area,
    priority,
    priority_score,
    confidence,
    effort,
    implementation_window,
    claim_kind,
    evidence_refs,
    finding,
    failure_mode,
    primary_change,
    proposed_acceptance_test
) AS (
    VALUES
        (1, 'FP-R01', 'Attachment retrieval', 'P0', 5, 'High', 'M', '0-2 weeks', 'observed',
         'packages/api/src/routes/ai/global_chat.rs:99-166,282-300',
         'The browser global-chat route fetches user-supplied HTTP(S) URLs with permissive redirects and buffers each response.',
         'An attachment can reach internal services or consume excessive memory.',
         'Accept owned object identifiers, revalidate every redirect, stream bytes, verify media, and enforce small aggregate limits.',
         'SSRF corpus, redirect rebinding tests, oversized and slow-body tests, and memory ceilings.'),
        (2, 'FP-R02', 'Destructive approval', 'P0', 5, 'High', 'S-M', '0-2 weeks', 'observed',
         'packages/ui/state/global-chat/global-chat-store.ts:317-320; packages/ui/components/global-chat/global-tool-bridge.tsx:1819-1859,1901-1909,4698-4710; packages/ui/components/flowpilot/FlowPilot.tsx:3766-3799',
         'Auto mode can waive destructive approval in some global and direct paths while product copy says deletion always asks.',
         'When a user enables Auto mode, a destructive action can execute under that standing choice without action-specific review, contrary to displayed policy.',
         'Centralize policy and require an exact, expiring approval for destructive and high-impact external effects.',
         'Cross-host conformance tests prove every delete path pauses on the same approval state.'),
        (3, 'FP-R03', 'Cancellation and deadlines', 'P0', 5, 'High', 'M-L', '0-2 weeks', 'observed',
         'packages/api/src/routes/ai/global_chat.rs:858-967; packages/core/editor/src/flow/copilot/platform.rs:763-796,1111-1229; apps/desktop/src-tauri/src/functions/ai/copilot.rs:4425-4443',
         'Browser streams can outlive clients, model and tool awaits lack a shared deadline, and cancellation is checked mainly between rounds.',
         'Disconnected work can consume model time and resources; some awaits have unbounded cancellation latency; already-dispatched descendants lack a demonstrated end-to-end fence.',
         'Treat explicit Stop as cancellation and disconnect as detach; propagate deadlines and atomically fence effects before dispatch.',
         'No effect begins after the stop fence, descendants halt within the proposed objective, and disconnected runs resume.'),
        (4, 'FP-R04', 'Tool contracts', 'P1', 4, 'High', 'M', '0-2 weeks', 'observed',
         'packages/core/editor/src/flow/copilot/tool_spec.rs:305-336; packages/core/editor/src/flow/copilot/session.rs:776-813,1697-1739; packages/ui/state/global-chat/global-chat-web-transport.ts:194-230',
         'Runtime validation checks only required top-level fields, and non-JSON result text defaults to success unless it starts with error.',
         'Malformed arguments or ambiguous failures can consume context-read reservations or advance workflow observations incorrectly.',
         'Validate bounded JSON Schema and require a versioned structured ToolResult envelope with status, code, retry class, receipt, and resource version.',
         'Schema mutation, dialect, reference, depth, and malformed-result tests fail closed before approval or dispatch.'),
        (5, 'FP-R05', 'Codex execution boundary', 'P0 gate', 5, 'Medium', 'M', '0-2 weeks', 'inference',
         'apps/desktop/src-tauri/src/functions/ai/copilot.rs:13796-13838,13864-13873,13922-13953,14531-14547',
         'The desktop Codex adapter uses a read-only sandbox and neutral temporary directory, but leaves inherited environment and built-in read or shell capability unproven.',
         'A delegated process may observe host files or credentials outside the intended task scope.',
         'Prefer an SDK or custom-tool-only adapter, scrub the environment, use an ephemeral home, and enforce an OS-level read allowlist.',
         'Adversarial canary tests attempt absolute-path reads, environment access, network access, and subprocess escape.'),
        (6, 'FP-R06', 'Effect idempotency', 'P1', 4, 'High', 'L', '2-6 weeks', 'observed',
         'packages/core/editor/src/flow/copilot/tool_spec.rs:1013-1039,1064-1088; packages/ui/components/global-chat/global-tool-bridge.tsx:2885-2997',
         'call_app_event exposes no idempotency key, create_app reads a key its schema does not advertise, and the create_app journal records after the effect.',
         'Retries, concurrent turns, or crash recovery can duplicate external effects.',
         'Mint and persist each operation ID before dispatch, bind it to a parameter digest, and use destination idempotency or reconcile Unknown outcomes.',
         'Concurrent duplicate and crash-after-effect tests produce one externally visible effect and one stable receipt.'),
        (7, 'FP-R07', 'Durable run state', 'P1', 4, 'High', 'L', '2-6 weeks', 'observed',
         'packages/ui/state/global-chat/global-chat-stream.ts:54-69,217-229,682-704,805-815; packages/api/src/state.rs:406-409,1029-1032',
         'Desktop global chat checkpoints runs, but browser runs, queues, approvals, and API drafts rely partly on process or page memory.',
         'A refresh, disconnect, restart, or replica change loses progress or strands approval state.',
         'Persist append-only RunEvent records, authorize opaque run IDs on every operation, and make streams resumable by sequence.',
         'Crash injection after every transition resumes to one terminal state without repeating effects.'),
        (8, 'FP-R08', 'Context and memory', 'P1', 4, 'High', 'M', '2-6 weeks', 'observed',
         'packages/ui/components/flowpilot/history-budget.ts:22-26,101-189; packages/ui/components/global-chat/global-chat-body.tsx:628-637; packages/core/editor/src/flow/copilot/memory.rs:251-317',
         'One surface clips history into lossy prose, another rejects long history, and durable memory entries lack per-entry provenance, trust, expiry, supersession, and approval status.',
         'The agent can forget constraints, become unusable after normal conversation growth, or preserve poisoned facts.',
         'Use a shared token-aware context assembler plus a structured task ledger and provenance-bearing, quarantined memory.',
         'Long-conversation, contradiction, stale-memory, tenant-isolation, and prompt-injection evaluations.'),
        (9, 'FP-R09', 'Catalog availability policy', 'P1', 4, 'High', 'S', '0-2 weeks',
         'A scoped WASM catalog failure logs a warning and falls back to built-ins; desktop paths can also fall back when the authoritative catalog is unavailable.',
         'The model can plan or mutate against an incomplete capability view.',
         'Fail closed for mutation or issue an explicit partial manifest that disables affected operations.',
         'Catalog fault tests prove mutation is unavailable until the authoritative manifest is restored.'),
        (10, 'FP-R10', 'Evaluation and observability', 'P1', 4, 'High', 'L', '6-12 weeks',
         'Current scorecards cover structural authoring quality but do not exercise safety, cancellation, duplicate effects, recovery, or provider variance.',
         'Regressions in the harness boundary can ship while graph-generation metrics remain green.',
         'Add hierarchical traces with payload capture off by default, outcome-first graders, safety checks, fault injection, provider canaries, and release gates.',
         'A versioned evaluation suite runs multiple trials and blocks releases on safety and reliability regressions.'),
        (11, 'FP-R11', 'Per-run UI isolation', 'P1', 4, 'High', 'M', '2-6 weeks',
         'The UI allows concurrent turns while several approval and workspace fields remain singleton state with owner identifiers.',
         'One run can overwrite or consume another run''s transient decision state.',
         'Nest every pending approval, workspace, queue, and stream cursor under run_id and enforce ownership on reducers.',
         'Four-run interleaving tests preserve independent prompts, approvals, cancellation, and terminal state.'),
        (12, 'FP-R12', 'Harness convergence', 'P2', 3, 'High', 'L', '6-12 weeks',
         'Direct and global harnesses duplicate lifecycle logic across large provider, host, and UI modules, with manual lane and resource switches.',
         'Policy and recovery behavior drift across surfaces and new tools require edits in several control planes.',
         'Extract one provider-neutral coordinator and generate scheduler metadata, protocol adapters, and conformance tests from the tool contract.',
         'All surfaces pass the same lifecycle, policy, protocol, and effect conformance suite.')
)
SELECT
    rank,
    risk_id,
    control_area,
    priority,
    priority_score,
    confidence,
    effort,
    implementation_window,
    claim_kind,
    evidence_refs,
    finding,
    failure_mode,
    primary_change,
    proposed_acceptance_test
FROM risks
ORDER BY rank;
