use utoipa::{
    Modify, OpenApi,
    openapi::security::{
        ApiKey, ApiKeyValue, AuthorizationCode, Flow, Http, HttpAuthScheme, OAuth2, Scopes,
        SecurityScheme,
    },
};

/// Security scheme modifier to add authentication methods
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);

        // Bearer token (OAuth2 JWT)
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );

        // API Key for technical users (X-API-Key header)
        components.add_security_scheme(
            "api_key",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-API-Key"))),
        );

        // Personal Access Token (Authorization: PAT <token>)
        components.add_security_scheme(
            "pat",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::with_description(
                "Authorization",
                "Personal Access Token. Format: 'PAT <token>'",
            ))),
        );

        // OAuth2 Authorization Code flow
        components.add_security_scheme(
            "oauth2",
            SecurityScheme::OAuth2(OAuth2::new([Flow::AuthorizationCode(
                AuthorizationCode::new(
                    "/api/v1/auth/authorize",
                    "/api/v1/auth/token",
                    Scopes::from_iter([
                        ("openid", "OpenID Connect scope"),
                        ("profile", "User profile information"),
                        ("email", "User email address"),
                    ]),
                ),
            )])),
        );

        // Channel responder JWT (clients answering a run through /channels/{id}/push)
        components.add_security_scheme(
            "channel_responder_jwt",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some(
                        "Channel responder token minted with the run's channel grant",
                    ))
                    .build(),
            ),
        );

        // Executor JWT (for backend execution services)
        components.add_security_scheme(
            "executor_jwt",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some("JWT token for execution services"))
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    modifiers(&SecurityAddon),
    info(
        title = "Flow-Like API",
        version = "1.0.0",
        description = "Flow-Like platform API for building and executing workflows.\n\n## Authentication\n\nThis API supports multiple authentication methods:\n\n- **Bearer Token (OAuth2)**: Standard JWT token from OAuth2 flow. Use `Authorization: Bearer <token>`\n- **API Key**: For technical/service users. Use `X-API-Key: <key>` header\n- **Personal Access Token (PAT)**: For programmatic access. Use `Authorization: PAT <token>`\n- **Executor JWT**: Internal JWT for execution services",
        license(name = "MIT")
    ),
    servers(
        (url = "/api/v1", description = "API v1")
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "auth", description = "Authentication and authorization"),
        (name = "oauth", description = "OAuth provider integration"),
        (name = "user", description = "User management and preferences"),
        (name = "profile", description = "User profiles"),
        (name = "apps", description = "Application management"),
        (name = "flowpilot-builds", description = "Durable FlowPilot app-build checkpoints"),
        (name = "boards", description = "Board/workflow management"),
        (name = "pages", description = "Page management"),
        (name = "routes", description = "Route mapping management"),
        (name = "execution", description = "Workflow execution"),
        (name = "channels", description = "Run ⇄ client reply channels"),
        (name = "events", description = "Event management"),
        (name = "widgets", description = "Widget management"),
        (name = "templates", description = "Template management"),
        (name = "meta", description = "Metadata management"),
        (name = "roles", description = "Role management"),
        (name = "packages", description = "App package management"),
        (name = "team", description = "Team management"),
        (name = "analytics", description = "Analytics and usage metrics"),
        (name = "sales", description = "Sales and pricing"),
        (name = "api-keys", description = "API key management"),
        (name = "comments", description = "App review comments"),
        (name = "notifications", description = "App notifications"),
        (name = "registry", description = "Package registry"),
        (name = "bit", description = "Bit (component) management"),
        (name = "sink", description = "Event sink management"),
        (name = "chat", description = "LLM chat completions and responses"),
        (name = "database", description = "Database operations"),
        (name = "graph", description = "Graph overlay and visualization operations"),
        (name = "data", description = "Data file access"),
        (name = "store", description = "Data store"),
        (name = "solution", description = "Solution requests"),
        (name = "admin", description = "Admin operations"),
        (name = "tmp", description = "Temporary file operations"),
        (name = "courses", description = "Flow-Like University: courses, lessons, challenges, leaderboard"),
        (name = "ai-act", description = "EU AI Act conformity assessment and model governance"),
        (name = "telemetry", description = "Anonymous, opt-in product telemetry")
    ),
    paths(
        // Health routes
        crate::routes::health::health,
        crate::routes::health::db_health,
        // OG metadata
        crate::routes::og::fetch_og_metadata,
        // Auth routes
        crate::routes::auth::openid_config,
        crate::routes::auth::discovery,
        crate::routes::auth::jwks,
        // OAuth routes
        crate::routes::oauth::token_exchange,
        crate::routes::oauth::token_refresh,
        // User routes
        crate::routes::user::info::user_info,
        crate::routes::user::upsert_info::upsert_info,
        crate::routes::user::pricing::get_pricing,
        crate::routes::user::subscribe::create_subscription_checkout,
        crate::routes::user::lookup::user_lookup,
        crate::routes::user::lookup::user_batch_lookup,
        crate::routes::user::lookup::user_search,
        crate::routes::user::contacts::user_contacts,
        crate::routes::user::billing::get_billing_session,
        crate::routes::user::notifications::get_notifications,
        crate::routes::user::notifications::list_notifications,
        crate::routes::user::notifications::mark_notification_read,
        crate::routes::user::notifications::mark_all_read,
        crate::routes::user::notifications::delete_notification,
        crate::routes::user::schedules::get_schedules,
        crate::routes::user::bits::list_user_bits,
        crate::routes::user::bits::upsert_user_bit,
        crate::routes::user::bits::delete_user_bit,
        crate::routes::user::push_targets::register_push_target,
        crate::routes::user::push_targets::get_push_target_status,
        crate::routes::user::push_targets::update_push_target_status,
        crate::routes::user::push_targets::unregister_push_target,
        crate::routes::user::get_invites::get_invites,
        crate::routes::user::manage_invite::accept_invite,
        crate::routes::user::manage_invite::reject_invite,
        crate::routes::user::templates::get_templates,
        crate::routes::user::widgets::get_widgets,
        crate::routes::user::pat::get_pats::get_pats,
        crate::routes::user::pat::create_pat::create_pat,
        crate::routes::user::pat::delete_pat::delete_pat,
        // Profile routes
        crate::routes::profile::get_profiles::get_profiles,
        crate::routes::profile::upsert_profile::upsert_profile,
        crate::routes::profile::delete_profile::delete_profile,
        crate::routes::profile::sync_profiles::sync_profiles,
        crate::routes::profile::get_profile_bits::get_profile_bits,
        // App routes
        crate::routes::app::internal::get_app::get_app,
        crate::routes::app::internal::get_apps::get_apps,
        crate::routes::app::internal::search_apps::search_apps,
        crate::routes::app::internal::upsert_app::upsert_app,
        crate::routes::app::internal::delete_app::delete_app,
        crate::routes::app::internal::change_visibility::change_visibility,
        crate::routes::app::internal::change_appearance::change_appearance,
        crate::routes::app::internal::change_appearance::get_appearance,
        crate::routes::app::internal::change_forking::change_forking,
        crate::routes::app::internal::change_forking::get_forking,
        crate::routes::app::flowpilot_builds::read_app_build,
        crate::routes::app::flowpilot_builds::write_app_build,
        crate::routes::app::fork::preview::get_fork_preview,
        crate::routes::app::fork::begin_offline::begin_offline_fork,
        crate::routes::app::fork::begin_online::begin_online_fork,
        crate::routes::app::fork::finalize_online::finalize_online_fork,
        crate::routes::app::fork::online_fork::online_fork,
        crate::routes::app::fork::jobs::get_fork_job,
        crate::routes::admin::forks::list_orphan_forks,
        crate::routes::admin::forks::delete_orphan_fork,
        crate::routes::admin::deletions::list_deletion_jobs,
        crate::routes::admin::deletions::get_deletion_job,
        crate::routes::admin::deletions::retry_deletion_job,
        crate::routes::admin::deletions::run_deletion_queue,
        crate::routes::admin::governance::list_scores::list_scores,
        crate::routes::admin::governance::get_scores_summary::get_scores_summary,
        crate::routes::admin::governance::get_app_scores::get_app_scores,
        crate::routes::admin::governance::list_patterns::list_patterns,
        crate::routes::admin::governance::recompute::recompute_scores,
        crate::routes::app::publication::get_publication::get_publication_requests,
        crate::routes::app::publication::upsert_publication::request_publication,
        crate::routes::admin::publication::get_requests::get_requests,
        crate::routes::admin::publication::upsert_requests::upsert_request,
        crate::routes::admin::publication::get_app_content::get_app_content,
        crate::routes::admin::publication::get_board::get_board,
        crate::routes::admin::publication::get_page::get_page,
        // EU AI Act routes
        crate::routes::app::ai_act::get_questionnaire,
        crate::routes::app::ai_act::classify_preview,
        crate::routes::app::ai_act::get_assessment,
        crate::routes::app::ai_act::put_assessment,
        crate::routes::app::ai_act::suggest_assessment,
        crate::routes::admin::ai_act::list_inventory,
        crate::routes::admin::ai_act::get_inventory_detail,
        crate::routes::admin::ai_act::put_inventory_assessment,
        crate::routes::admin::ai_act::reconcile_models,
        crate::routes::admin::ai_act::acknowledge_model,
        crate::routes::admin::ai_act::list_models,
        crate::routes::admin::ai_act::upsert_model,
        crate::routes::admin::ai_act::assist,
        crate::routes::admin::ai_act::export_inventory,
        crate::routes::app::internal::get_nodes::get_nodes,
        // Board routes
        crate::routes::app::board::get_board::get_board,
        crate::routes::app::board::sync_board::sync_board,
        crate::routes::app::board::get_boards::get_boards,
        crate::routes::app::board::summaries::board_summaries,
        crate::routes::app::board::get_board_variables::get_board_variables,
        crate::routes::app::board::get_board_versions::get_board_versions,
        crate::routes::app::board::upsert_board::upsert_board,
        crate::routes::app::board::delete_board::delete_board,
        crate::routes::app::board::version_board::version_board,
        crate::routes::app::board::execute_commands::execute_commands,
        crate::routes::app::board::undo_redo_board::undo_board,
        crate::routes::app::board::undo_redo_board::redo_board,
        crate::routes::app::board::invoke_board::invoke_board,
        crate::routes::app::board::invoke_board_async::invoke_board_async,
        crate::routes::app::board::prerun_board::prerun_board,
        crate::routes::app::board::query_logs::query_logs,
        crate::routes::app::board::get_runs::get_runs,
        crate::routes::app::board::get_execution_elements::get_execution_elements,
        crate::routes::app::board::element_demand::get_element_demand,
        crate::routes::app::board::flow_ir_commit::flow_ir_commit_disposition,
        crate::routes::app::board::flow_ir_commit::apply_flow_ir_commit,
        // Page routes
		crate::routes::app::page::bootstrap::bootstrap,
        crate::routes::app::page::get_page::get_page,
        crate::routes::app::page::get_pages::get_pages,
        crate::routes::app::page::get_page_by_route::get_page_by_route,
        crate::routes::app::page::upsert_page::upsert_page,
        crate::routes::app::page::delete_page::delete_page,
        // Route mapping routes
        crate::routes::app::route::get_routes::get_routes,
        crate::routes::app::route::get_route_by_path::get_route_by_path,
        crate::routes::app::route::get_default_route::get_default_route,
        crate::routes::app::route::upsert_route::create_route,
        crate::routes::app::route::upsert_route::update_route,
        crate::routes::app::route::delete_route::delete_route,
        // Widget routes
        crate::routes::app::widget::get_widgets::get_widgets,
        crate::routes::app::widget::get_widget::get_widget,
        crate::routes::app::widget::upsert_widget::upsert_widget,
        crate::routes::app::widget::delete_widget::delete_widget,
        crate::routes::app::widget::get_widget_versions::get_widget_versions,
        crate::routes::app::widget::create_widget_version::create_widget_version,
        // Template routes
        crate::routes::app::template::get_templates::get_templates,
        crate::routes::app::template::get_template::get_template,
        crate::routes::app::template::get_template_preview::get_template_preview,
        crate::routes::app::internal::search_templates::search_templates,
        crate::routes::app::template::upsert_template::upsert_template,
        crate::routes::app::template::delete_template::delete_template,
        // Meta routes
        crate::routes::app::meta::get_meta::get_meta,
        crate::routes::app::meta::upsert_meta::upsert_meta,
        crate::routes::app::meta::push_media::push_media,
        crate::routes::app::meta::remove_media::remove_media,
        // Role routes
        crate::routes::app::roles::get_roles::get_roles,
        crate::routes::app::roles::get_own_role::get_own_role,
        crate::routes::app::roles::upsert_role::upsert_role,
        crate::routes::app::roles::delete_role::delete_role,
        crate::routes::app::roles::make_role_default::make_role_default,
        crate::routes::app::roles::assign_role::assign_role,
        // Team routes
        crate::routes::app::team::get_team::get_team,
        crate::routes::app::team::create_invite_link::create_invite_link,
        crate::routes::app::team::get_invite_links::get_invite_links,
        crate::routes::app::team::remove_invite_link::remove_invite_link,
        crate::routes::app::team::join_invite_link::join_invite_link,
        crate::routes::app::team::get_join_requests::get_join_requests,
        crate::routes::app::team::request_join::request_join,
        crate::routes::app::team::manage_join_request::accept_join_request,
        crate::routes::app::team::manage_join_request::reject_join_request,
        crate::routes::app::team::invite_user::invite_user,
        crate::routes::app::team::invites::list_app_invites,
        crate::routes::app::team::invites::revoke_invite,
        crate::routes::app::team::purchase::purchase,
        crate::routes::app::team::remove_user::remove_user,
        // App connection routes (app-to-app access)
        crate::routes::app::connection::get_connections::get_connections,
        crate::routes::app::connection::add_connection::add_connection,
        crate::routes::app::connection::request_connection::request_connection,
        crate::routes::app::connection::manage_connection::accept_connection_request,
        crate::routes::app::connection::manage_connection::reject_connection_request,
        crate::routes::app::connection::update_connection::update_connection,
        crate::routes::app::connection::remove_connection::remove_connection,
        crate::routes::app::connection::get_accessible::get_accessible_apps,
        crate::routes::app::connection::remote_tables::get_remote_tables,
        crate::routes::app::connection::remote_ontologies::get_remote_ontologies,
        crate::routes::app::connection::remote_ontologies::install_remote_ontology,
        crate::routes::app::connection::remote_ontologies::uninstall_remote_ontology,
        crate::routes::app::connection::remote_events::get_remote_events,
        crate::routes::app::connection::remote_events::get_remote_event_detail,
        crate::routes::app::connection::token::create_app_connection_token,
        crate::routes::app::connection::graph::get_connection_graph,
        crate::routes::app::connection::cases::list_process_cases,
        crate::routes::app::connection::cases::get_process_case,
        crate::routes::app::connection::notes::list_notes,
        crate::routes::app::connection::notes::create_note,
        crate::routes::app::connection::notes::update_note,
        crate::routes::app::connection::notes::delete_note,
        crate::routes::app::groups::crud::create_group,
        crate::routes::app::groups::crud::list_groups,
        crate::routes::app::groups::crud::get_group,
        crate::routes::app::groups::crud::update_group,
        crate::routes::app::groups::crud::delete_group,
        crate::routes::app::groups::members::add_member,
        crate::routes::app::groups::members::remove_member,
        crate::routes::app::groups::members::leave_group,
        crate::routes::app::groups::publication::change_group_visibility,
        crate::routes::app::groups::publication::get_group_publication,
        crate::routes::admin::publication::get_group_requests::get_group_requests,
        crate::routes::app::groups::requests::list_group_requests,
        crate::routes::app::groups::requests::accept_group_request,
        crate::routes::app::groups::requests::decline_group_request,
        crate::routes::store::list_public_groups,
        crate::routes::store::get_public_group,
        crate::routes::user::groups::get_user_groups,
        crate::routes::admin::connections::get_global_connection_graph,
        // API key routes
        crate::routes::app::api::get_api_keys::get_api_keys,
        crate::routes::app::api::create_api_key::create_api_key,
        crate::routes::app::api::delete_api_key::delete_api_key,
        // Analytics routes
        crate::routes::app::analytics::overview::get_analytics_overview,
        crate::routes::app::analytics::overview::get_analytics_stats,
        crate::routes::app::analytics::feedback::list_feedback,
        // Sales routes
        crate::routes::app::sales::overview::get_sales_overview,
        crate::routes::app::sales::overview::get_sales_stats,
        crate::routes::app::sales::purchases::list_purchases,
        crate::routes::app::sales::price::update_price,
        crate::routes::app::sales::discounts::list_discounts,
        crate::routes::app::sales::discounts::create_discount,
        crate::routes::app::sales::discounts::get_discount,
        crate::routes::app::sales::discounts::update_discount,
        crate::routes::app::sales::discounts::delete_discount,
        crate::routes::app::sales::discounts::toggle_discount,
        // Event routes
        crate::routes::app::events::get_events::get_events,
        crate::routes::app::events::get_event::get_event,
        crate::routes::app::events::upsert_event::upsert_event,
        crate::routes::app::events::delete_event::delete_event,
        crate::routes::app::events::get_event_versions::get_event_versions,
        crate::routes::app::events::get_event_timeline::get_event_timeline,
        crate::routes::app::events::get_event_runs::get_event_runs,
        crate::routes::app::events::restore_event::restore_event,
        crate::routes::app::events::validate_event::validate_event,
        crate::routes::app::events::setup_event::setup_event,
        crate::routes::app::events::prerun_event::prerun_event,
        crate::routes::app::events::prerun_event::prerun_page_event,
        crate::routes::app::events::invoke_event::invoke_event,
        crate::routes::app::events::invoke_event_async::invoke_event_async,
        crate::routes::app::events::canary::explain_canary,
        crate::routes::app::events::canary::canary_stats,
        crate::routes::app::events::canary::patch_canary,
        crate::routes::app::events::canary::put_event_variants,
        crate::routes::app::events::canary::promote_canary,
        crate::routes::app::events::canary::abort_canary,
        crate::routes::app::events::canary::list_event_setups,
        crate::routes::app::events::regression::get_event_corpus,
        crate::routes::app::events::regression::get_corpus_payload,
        crate::routes::app::events::regression::promote_regression_fixture,
        crate::routes::app::events::regression::delete_regression_fixture,
        crate::routes::app::events::regression::get_regression_suite,
        crate::routes::app::events::regression::put_regression_suite,
        crate::routes::app::events::regression::run_regression_suite,
        crate::routes::app::events::regression::list_regression_runs,
        crate::routes::app::events::regression::get_regression_run,
        crate::routes::app::events::registrations::list_registrations,
        crate::routes::app::events::alias::list_aliases,
        crate::routes::app::events::alias::get_alias,
        crate::routes::app::events::alias::upsert_alias,
        crate::routes::app::events::alias::delete_alias,
        crate::routes::app::events::upsert_event_feedback::upsert_event_feedback,
        crate::routes::alias::lookup_alias,
        // Comment routes
        crate::routes::app::comments::get_comments::get_comments,
        crate::routes::app::comments::upsert_comment::upsert_comment,
        crate::routes::app::comments::remove_comment::remove_comment,
        // Notifications routes
        crate::routes::app::notifications::create_notification,
        // Cache routes
        crate::routes::app::cache::read_cache_entry,
        crate::routes::app::cache::cache_entry_exists,
        crate::routes::app::cache::write_cache_entry,
        crate::routes::app::cache::delete_cache_entry,
        crate::routes::app::cache::delete_cache_namespace,
        // Data routes
        crate::routes::app::data::upload_files::upload_files,
        crate::routes::app::data::upload_files::upload_user_files,
        crate::routes::app::data::download_files::download_files,
        crate::routes::app::data::download_files::download_user_files,
        crate::routes::app::data::list_files::list_files,
        crate::routes::app::data::list_files::list_user_files,
        crate::routes::app::data::delete_files::delete_files,
        crate::routes::app::data::delete_files::delete_user_files,
        crate::routes::app::data::presign_data_access::presign_data_access,
        crate::routes::app::data::presign_data_access::presign_user_data_access,
        // Realtime board routes
        crate::routes::app::board::realtime::jwks,
        crate::routes::app::board::realtime::access,
        // Invoke presign
        crate::routes::app::invoke::presign::presign,
        crate::routes::app::invoke::context::execution_context,
        // Database routes
        crate::routes::app::db::list_tables::list_tables,
        crate::routes::app::db::db_list::list_items,
        crate::routes::app::db::create_table::create_table,
        crate::routes::app::db::db_add::add_to_table,
        crate::routes::app::db::db_delete::delete_from_table,
        crate::routes::app::db::db_update::update_table,
        crate::routes::app::db::db_query::query_table,
        crate::routes::app::db::saved_queries::list_saved_queries,
        crate::routes::app::db::saved_queries::get_saved_query,
        crate::routes::app::db::saved_queries::create_saved_query,
        crate::routes::app::db::saved_queries::update_saved_query,
        crate::routes::app::db::saved_queries::delete_saved_query,
        crate::routes::app::db::saved_queries::execute_query,
        crate::routes::app::db::db_count::db_count,
        crate::routes::app::db::get_db_schema::get_db_schema,
        crate::routes::app::db::get_indices::get_db_indices,
        crate::routes::app::db::add_column::add_column,
        crate::routes::app::db::alter_column::alter_column,
        crate::routes::app::db::drop_columns::drop_columns,
        crate::routes::app::db::build_index::build_index,
        crate::routes::app::db::drop_index::drop_index,
        crate::routes::app::db::drop_table::drop_table,
        crate::routes::app::db::optimize::optimize_table,
        crate::routes::app::db::presign_db_access::presign_db_access,
        crate::routes::app::db::presign_db_access::presign_project_db_access,
        crate::routes::app::graph::search::search_nodes,
        crate::routes::app::graph::list_imports::list_imports,
        crate::routes::app::graph::import_read::sample_import,
        crate::routes::app::graph::import_read::query_import,
        crate::routes::app::graph::list_overlays::list_overlays,
        crate::routes::app::graph::create_overlay::create_overlay,
        crate::routes::app::graph::get_overlay::get_overlay,
        crate::routes::app::graph::update_overlay::update_overlay,
        crate::routes::app::graph::delete_overlay::delete_overlay,
        crate::routes::app::graph::schema::graph_schema,
        crate::routes::app::graph::validate::validate_overlay,
        crate::routes::app::graph::cypher::run_cypher,
        crate::routes::app::graph::sql::run_sql,
        crate::routes::app::graph::neighbors::neighbors,
        crate::routes::app::graph::children::children,
        crate::routes::app::graph::subgraph::subgraph,
        crate::routes::app::graph::paths::find_paths,
        crate::routes::app::graph::analytics::graph_analytics,
        crate::routes::app::graph::sample::sample_nodes,
        crate::routes::app::graph::upsert_nodes::upsert_nodes,
        crate::routes::app::graph::upsert_edges::upsert_edges,
        crate::routes::app::graph::actions::invoke_ontology_action,
        crate::routes::app::graph::actions::prerun_ontology_action,
        // App package routes
        crate::routes::app::packages::list_packages,
        crate::routes::app::packages::add_package,
        crate::routes::app::packages::remove_package,
        crate::routes::app::packages::update_package,
        crate::routes::app::packages::get_patch_info,
        crate::routes::app::packages::check_updates,
        // Execution routes
        crate::routes::execution::progress::report_progress,
        crate::routes::execution::progress::push_events,
        crate::routes::execution::progress::poll_status,
        crate::routes::execution::progress::get_run_status,
        crate::routes::execution::cancel::cancel_run,
        crate::routes::execution::public_key::get_execution_jwks,
        // Channel routes
        crate::routes::channel::register_message,
        crate::routes::channel::poll_message,
        crate::routes::channel::remove_message,
        crate::routes::channel::drain_inbound,
        crate::routes::channel::channel_status,
        crate::routes::channel::close_channel,
        crate::routes::channel::push_channel,
        crate::routes::channel::grant_channel,
        // Registry routes
        crate::routes::registry::publish::publish,
        crate::routes::registry::search::search,
        crate::routes::registry::download::download,
        crate::routes::registry::widget_asset::get_widget_asset,
        // Bit routes
        crate::routes::bit::get_bit::get_bit,
        crate::routes::bit::get_with_dependencies::get_with_dependencies,
        crate::routes::bit::search_bits::search_bits,
        // Sink routes
        crate::routes::sink::trigger::trigger_http,
        crate::routes::sink::trigger::trigger_telegram,
        crate::routes::sink::trigger::trigger_discord,
        crate::routes::sink::trigger::trigger_service,
        crate::routes::sink::trigger::get_cron_sinks,
        crate::routes::sink::trigger::get_sink_configs,
        crate::routes::sink::management::list_sinks,
        crate::routes::sink::management::list_app_sinks,
        crate::routes::sink::management::get_sink,
        crate::routes::sink::management::update_sink,
        crate::routes::sink::management::toggle_sink,
        // Chat routes
        crate::routes::chat::completions::invoke_llm,
        crate::routes::chat::responses::invoke_responses,
        crate::routes::chat::usage::get_llm_usage,
        // Store routes
        crate::routes::store::get_store_db,
        // Solution routes
        crate::routes::solution::get_upload_url,
        crate::routes::solution::submit_solution,
        crate::routes::solution::track_solution,
        // Tmp routes
        crate::routes::tmp::get_temporary_upload,
        crate::routes::tmp::create_temporary_uploads,
        // Telemetry routes
        crate::routes::telemetry::ingest_events,
        crate::routes::telemetry::errors::ingest_errors,
        crate::routes::telemetry::sessions::ingest_sessions,
        crate::routes::telemetry::spans::ingest_spans,
        crate::routes::telemetry::performance::ingest_performance,
        crate::routes::telemetry::config::telemetry_config,
        crate::routes::admin::telemetry::telemetry_overview,
        crate::routes::admin::telemetry::telemetry_timeseries,
        crate::routes::admin::telemetry::list_telemetry_events,
        crate::routes::admin::telemetry::telemetry_engagement,
        crate::routes::admin::telemetry::telemetry_flowpilot,
        crate::routes::flowscript::report_flowscript_apply_failure,
        crate::routes::admin::telemetry::flowscript_failures::list_flowscript_failures,
        crate::routes::admin::telemetry::flowscript_failures::get_flowscript_failure,
        crate::routes::admin::telemetry::prompt_feedback::list_prompt_feedback,
        crate::routes::admin::telemetry::prompt_feedback::get_prompt_feedback,
        crate::routes::ai::global_chat::feedback::upsert_global_chat_feedback,
        crate::routes::admin::telemetry::issues::list_telemetry_issues,
        crate::routes::admin::telemetry::issues::get_telemetry_issue,
        crate::routes::admin::telemetry::issues::update_telemetry_issue,
        crate::routes::admin::telemetry::release_health::list_telemetry_releases,
        crate::routes::admin::telemetry::release_health::telemetry_release_health,
        crate::routes::admin::telemetry::sourcemaps::upload_telemetry_sourcemap,
        crate::routes::admin::telemetry::traces::list_telemetry_traces,
        crate::routes::admin::telemetry::traces::get_telemetry_trace,
        crate::routes::admin::telemetry::performance::telemetry_performance,
        crate::routes::admin::telemetry::span_stats::telemetry_span_stats,
        crate::routes::admin::telemetry::sweep::sweep_telemetry,
        crate::routes::admin::telemetry::rollup::rollup_telemetry,
        crate::routes::telemetry::llm::ingest_llm_calls,
        crate::routes::admin::telemetry::llm::telemetry_llm,
        crate::routes::admin::telemetry::alerts::list_telemetry_alert_rules,
        crate::routes::admin::telemetry::alerts::create_telemetry_alert_rule,
        crate::routes::admin::telemetry::alerts::update_telemetry_alert_rule,
        crate::routes::admin::telemetry::alerts::delete_telemetry_alert_rule,
        crate::routes::admin::telemetry::alerts::list_telemetry_alert_events,
        crate::routes::admin::telemetry::alerts::acknowledge_telemetry_alert_event,
        crate::routes::admin::telemetry::alerts::evaluate_telemetry_alerts,
        crate::routes::admin::telemetry::query::run_telemetry_query,
        crate::routes::admin::telemetry::saved_queries::list_telemetry_saved_queries,
        crate::routes::admin::telemetry::saved_queries::create_telemetry_saved_query,
        crate::routes::admin::telemetry::saved_queries::update_telemetry_saved_query,
        crate::routes::admin::telemetry::saved_queries::delete_telemetry_saved_query,
        crate::routes::admin::telemetry::dashboards::list_telemetry_dashboards,
        crate::routes::admin::telemetry::dashboards::create_telemetry_dashboard,
        crate::routes::admin::telemetry::dashboards::update_telemetry_dashboard,
        crate::routes::admin::telemetry::dashboards::delete_telemetry_dashboard,
        // Admin routes
        crate::routes::admin::solutions::list_solutions::list_solutions,
        crate::routes::admin::packages::get_stats::get_stats,
        crate::routes::admin::packages::ensure_wasm_artifacts::ensure_wasm_artifacts,
        crate::routes::admin::packages::get_packages::get_packages,
        crate::routes::admin::packages::get_package::get_package,
        crate::routes::admin::packages::delete_package::delete_package,
        crate::routes::admin::packages::review_package::review_package,
        crate::routes::admin::packages::update_package::update_package,
        crate::routes::registry::metadata::get_publication_reviews,
        crate::routes::admin::bit::delete_bit::delete_bit,
        crate::routes::admin::sinks::list_tokens::list_tokens,
        crate::routes::admin::profiles::delete_profile_template::delete_profile_template,
        crate::routes::admin::runs::sweep_runs,
        crate::routes::admin::cache::sweep_cache,
        crate::routes::admin::resources::get_resources,
        // Course routes (University)
        crate::routes::course::courses::list_courses,
        crate::routes::course::courses::get_course,
        crate::routes::course::courses::get_course_structure,
        crate::routes::course::courses::upsert_course,
        crate::routes::course::courses::push_course_media,
        crate::routes::course::courses::delete_course,
        crate::routes::course::assets::list_course_assets,
        crate::routes::course::assets::create_course_asset,
        crate::routes::course::assets::update_course_asset,
        crate::routes::course::assets::delete_course_asset,
        crate::routes::course::assets::optimize_course_asset,
        crate::routes::course::modules::upsert_module,
        crate::routes::course::modules::delete_module,
        crate::routes::course::lessons::get_lesson,
        crate::routes::course::lessons::upsert_lesson,
        crate::routes::course::lessons::delete_lesson,
        crate::routes::course::challenges::upsert_challenge,
        crate::routes::course::challenges::delete_challenge,
        crate::routes::course::app_links::list_app_links,
        crate::routes::course::app_links::upsert_app_link,
        crate::routes::course::app_links::delete_app_link,
        crate::routes::course::app_refs::upsert_app_ref,
        crate::routes::course::app_refs::delete_app_ref,
        crate::routes::course::shared_app::open_shared_app,
        crate::routes::course::translate::translate,
        crate::routes::course::enrollment::enroll,
        crate::routes::course::enrollment::get_my_enrollments,
        crate::routes::course::progress::mark_lesson_complete,
        crate::routes::course::progress::get_my_course_progress,
        crate::routes::course::attempts::submit_attempt,
        crate::routes::course::certificates::issue_certificate,
        crate::routes::course::certificates::list_my_certificates,
        crate::routes::course::certificates::verify_certificate,
        crate::routes::course::paths::list_learning_paths,
        crate::routes::course::paths::get_learning_path,
        crate::routes::course::paths::upsert_learning_path,
        crate::routes::course::paths::delete_learning_path,
        crate::routes::course::paths::upsert_learning_path_step,
        crate::routes::course::paths::delete_learning_path_step,
        crate::routes::course::leaderboard::get_leaderboard,
        crate::routes::course::leaderboard::get_my_opt_in,
        crate::routes::course::leaderboard::update_my_opt_in,
        crate::routes::course::weekly::get_current_weekly,
        crate::routes::course::weekly::rotate_weekly,
    ),
    components(schemas(
        // User schedule schemas
        crate::routes::user::schedules::ScheduleConfig,
        crate::routes::user::schedules::UserSchedule,
        crate::routes::user::schedules::UserSchedulesResponse,
        // Health schemas
        crate::routes::health::HealthResponse,
        crate::routes::health::DbHealthResponse,
        // Channel schemas
        crate::routes::channel::RegisterMessageBody,
        crate::routes::channel::RegisterMessageResponse,
        crate::routes::channel::PollMessageBody,
        crate::routes::channel::DrainInboundBody,
        crate::routes::channel::ChannelStatusBody,
        crate::routes::channel::PushResponse,
        crate::routes::channel::GrantSide,
        // Cache schemas
        crate::routes::app::cache::ReadCacheResponse,
        crate::routes::app::cache::ExistsCacheResponse,
        crate::routes::app::cache::WriteCacheRequest,
        crate::routes::app::cache::WriteCacheResponse,
        crate::routes::app::cache::DeleteCacheResponse,
        crate::routes::app::cache::DeleteNamespaceResponse,
        crate::routes::app::flowpilot_builds::WriteAppBuildRequest,
        crate::routes::admin::cache::SweepCacheResponse,
        // Backing service status schemas
        crate::routes::admin::resources::AdminResourcesResponse,
        crate::routes::admin::resources::ResourceStatus,
        crate::routes::admin::resources::ResourceMetric,
        crate::routes::admin::resources::ResourceKind,
        crate::routes::admin::resources::ResourceHealth,
        crate::routes::admin::resources::MetricUnit,
        crate::routes::admin::resources::MetricFreshness,
        crate::routes::admin::resources::DatabaseDetail,
        crate::routes::admin::resources::TableUsage,
        crate::routes::admin::resources::ConnectionStateCount,
        crate::routes::admin::resources::DatabaseCounters,
        crate::routes::admin::resources::DatabaseRates,
        // OAuth schemas
        crate::routes::oauth::TokenExchangeRequest,
        crate::routes::oauth::TokenRefreshRequest,
        crate::routes::oauth::TokenResponse,
        crate::routes::oauth::ErrorResponse,
        // Database schemas
        crate::routes::app::db::saved_queries::CreateSavedQueryPayload,
        crate::routes::app::db::saved_queries::UpdateSavedQueryPayload,
        crate::routes::app::db::saved_queries::ExecuteQueryPayload,
        crate::routes::app::graph::import_read::ImportQueryPayload,
        crate::routes::app::db::add_column::AddColumnPayload,
        crate::routes::app::db::alter_column::AlterColumnPayload,
        crate::routes::app::db::build_index::BuildIndexPayload,
        crate::routes::app::db::build_index::IndexType,
        crate::routes::app::db::db_delete::DeleteFromDBPayload,
        crate::routes::app::db::db_query::QueryTablePayload,
        crate::routes::app::db::db_query::VectorQueryPayload,
        crate::routes::app::db::drop_columns::DropColumnsPayload,
        crate::routes::app::db::get_indices::IndexConfigResponse,
        crate::routes::app::db::optimize::OptimizePayload,
        crate::routes::app::db::presign_db_access::PresignDbAccessRequest,
        crate::routes::app::db::presign_db_access::PresignDbAccessResponse,
        // App connection schemas
        crate::routes::app::connection::AppConnectionInfo,
        crate::routes::app::connection::get_connections::AppConnectionsResponse,
        crate::routes::app::connection::add_connection::AddConnectionRequest,
        crate::routes::app::connection::request_connection::RequestConnectionRequest,
        crate::routes::app::connection::manage_connection::AcceptConnectionRequest,
        crate::routes::app::connection::update_connection::UpdateConnectionRequest,
        crate::routes::app::connection::get_accessible::AccessibleApp,
        crate::routes::app::connection::token::CreateAppConnectionTokenRequest,
        crate::routes::app::connection::token::CreateAppConnectionTokenResponse,
        crate::routes::app::connection::graph::ProcessGraphResponse,
        crate::routes::app::connection::graph::ProcessGraphNode,
        crate::routes::app::connection::graph::ProcessGraphEdge,
        crate::routes::app::connection::graph::ProcessFlow,
        crate::routes::app::connection::graph::AppContentStats,
        crate::routes::app::connection::cases::ProcessCase,
        crate::routes::app::connection::cases::ProcessCasesResponse,
        crate::routes::app::connection::cases::ProcessCaseRun,
        crate::routes::app::connection::cases::ProcessCaseDetailResponse,
        crate::routes::app::connection::graph::ProcessNoteInfo,
        crate::routes::app::connection::notes::UpsertProcessNoteRequest,
        crate::routes::app::groups::GroupInfo,
        crate::routes::app::groups::GroupMemberInfo,
        crate::routes::app::groups::crud::CreateGroupRequest,
        crate::routes::app::groups::crud::UpdateGroupRequest,
        crate::routes::app::groups::members::AddMemberRequest,
        crate::routes::app::groups::requests::GroupMembershipRequest,
        crate::routes::app::groups::publication::ChangeGroupVisibilityRequest,
        crate::routes::app::groups::publication::ChangeGroupVisibilityResponse,
        crate::routes::app::groups::publication::GroupPublicationStatus,
        crate::routes::app::groups::publication::GroupPublicationRequestItem,
        crate::routes::app::groups::publication::GroupPublicationLogItem,
        crate::routes::app::groups::publication::MemberReadinessItem,
        crate::routes::admin::publication::get_group_requests::SuitePublicationRequestItem,
        crate::routes::admin::publication::get_group_requests::SuiteMemberItem,
        crate::routes::admin::publication::get_group_requests::ListSuitePublicationRequestsResponse,
        crate::routes::app::connection::remote_events::RemoteEvent,
        crate::routes::app::connection::remote_events::RemoteEventDetail,
        crate::routes::app::connection::remote_events::RemoteEventDetailQuery,
        crate::routes::app::connection::remote_events::RemoteRestRoute,
        crate::routes::app::connection::remote_events::RemoteRestFile,
        crate::routes::app::connection::remote_events::RemoteMcpTool,
        crate::routes::app::connection::remote_events::RemoteMcpResource,
        crate::routes::app::data::presign_data_access::PresignDataAccessRequest,
        crate::routes::app::data::presign_data_access::PresignDataAccessResponse,
        // App notifications
        crate::routes::app::notifications::CreateNotificationParams,
        crate::routes::app::notifications::CreateNotificationResponse,
        // Admin governance scores
        crate::routes::admin::governance::list_scores::AppScoreItem,
        crate::routes::admin::governance::list_scores::ListAppScoresResponse,
        crate::routes::admin::governance::get_app_scores::BoardScoreItem,
        crate::routes::admin::governance::get_app_scores::AppScoreDetailResponse,
        crate::routes::admin::governance::get_scores_summary::GovernanceScoresSummary,
        crate::routes::admin::governance::get_scores_summary::WorstAppItem,
        crate::routes::admin::governance::list_patterns::PatternItem,
        crate::routes::admin::governance::list_patterns::ListPatternsResponse,
        crate::routes::admin::governance::recompute::RecomputeScoresRequest,
        crate::routes::admin::governance::recompute::RecomputeScoresResponse,
        crate::routes::app::board::scoring::BoardScores,
        crate::routes::app::board::scoring::FlaggedPattern,
        crate::routes::app::board::summaries::BoardSummary,
        crate::routes::app::board::get_board_variables::BoardVariables,
        crate::routes::app::page::get_pages::PageInfo,
		crate::routes::app::page::bootstrap::BootstrapResponse,
        crate::routes::app::publication::get_publication::AppPublicationActor,
        crate::routes::app::publication::get_publication::AppPublicationLogItem,
        crate::routes::app::publication::get_publication::AppPublicationRequestItem,
        crate::routes::app::publication::upsert_publication::RequestPublicationBody,
        crate::routes::app::publication::upsert_publication::RequestPublicationResponse,
        crate::routes::admin::publication::get_requests::ListPublicationRequestsQuery,
        crate::routes::admin::publication::get_requests::ListPublicationRequestsResponse,
        crate::routes::admin::publication::get_requests::PublicationActor,
        crate::routes::admin::publication::get_requests::PublicationLogItem,
        crate::routes::admin::publication::get_requests::PublicationRequestItem,
        crate::routes::admin::publication::upsert_requests::ReviewPublicationBody,
        crate::routes::admin::publication::upsert_requests::ReviewPublicationResponse,
        // EU AI Act
        crate::routes::app::ai_act::QuestionnaireResponse,
        crate::routes::app::ai_act::ClassifyBody,
        crate::routes::app::ai_act::ClassifyResponse,
        crate::routes::app::ai_act::AssessmentResponse,
        crate::routes::app::ai_act::UpsertAssessmentBody,
        crate::routes::app::ai_act::SuggestBody,
        crate::routes::app::ai_act::SuggestResponse,
        crate::routes::admin::ai_act::InventoryItem,
        crate::routes::admin::ai_act::InventoryResponse,
        crate::routes::admin::ai_act::ModelObservationItem,
        crate::routes::admin::ai_act::InventoryDetailResponse,
        crate::routes::admin::ai_act::ReconcileResponse,
        crate::routes::admin::ai_act::RegistryItem,
        crate::routes::admin::ai_act::UpsertModelBody,
        crate::routes::admin::ai_act::AssistBody,
        // Widgets
        crate::routes::app::widget::get_widget::VersionQuery,
        crate::routes::app::widget::upsert_widget::WidgetUpsert,
        crate::routes::app::widget::create_widget_version::CreateWidgetVersion,
        // Templates
        crate::routes::app::template::get_template::VersionQuery,
        crate::routes::app::template::get_template_preview::TemplatePreview,
        crate::routes::app::internal::search_templates::TemplateSearchHit,
        crate::routes::app::template::upsert_template::TemplateUpsert,
        // Meta
        crate::routes::app::meta::MetaQuery,
        crate::routes::app::meta::MediaQuery,
        crate::routes::app::meta::MediaItem,
        crate::routes::app::meta::push_media::PushMediaResponse,
        // Team
        crate::routes::app::team::create_invite_link::CreateInviteLinkPayload,
        crate::routes::app::team::request_join::RequestJoinParams,
        crate::routes::app::team::invite_user::InviteUserParams,
        crate::routes::app::team::purchase::PurchaseParams,
        crate::routes::app::team::purchase::PurchaseResponse,
        // API keys
        crate::routes::app::api::ApiKeyInfo,
        crate::routes::app::api::ApiKeyInput,
        crate::routes::app::api::ApiKeyOut,
        // Analytics
        crate::compute_cost::ComputeLeg,
        crate::compute_cost::ComputeCostModel,
        crate::routes::app::analytics::overview::AnalyticsStatsQuery,
        crate::routes::app::analytics::overview::AnalyticsOverview,
        crate::routes::app::analytics::overview::DailyAnalyticsStat,
        crate::routes::app::analytics::overview::AnalyticsStats,
        crate::routes::app::analytics::feedback::FeedbackQuery,
        crate::routes::app::analytics::feedback::FeedbackItem,
        crate::routes::app::analytics::feedback::PaginatedFeedback,
        // Sales
        crate::routes::app::sales::overview::StatsQuery,
        crate::routes::app::sales::overview::SalesOverview,
        crate::routes::app::sales::overview::DailyStat,
        crate::routes::app::sales::overview::SalesStats,
        crate::routes::app::sales::price::UpdatePriceRequest,
        crate::routes::app::sales::price::PriceResponse,
        crate::routes::app::sales::discounts::ListDiscountsQuery,
        crate::routes::app::sales::discounts::DiscountResponse,
        crate::routes::app::sales::discounts::CreateDiscountRequest,
        crate::routes::app::sales::discounts::UpdateDiscountRequest,
        crate::routes::app::sales::purchases::PurchasesQuery,
        crate::routes::app::sales::purchases::PurchaseItem,
        crate::routes::app::sales::purchases::PurchasesResponse,
        // Events
        crate::routes::app::events::get_event::VersionQuery,
        crate::routes::app::events::get_event_timeline::EventTimelineResponse,
        crate::routes::app::events::get_event_timeline::EventTimelineEntry,
        crate::routes::app::events::get_event_runs::EventRunsResponse,
        crate::routes::app::events::restore_event::RestoreEventBody,
        crate::routes::app::events::restore_event::RestoreEventResponse,
        crate::routes::app::events::validate_event::VersionQuery,
        crate::routes::app::events::upsert_event::EventUpsertBody,
        crate::routes::app::events::setup_event::SetupEventRequest,
        crate::routes::app::events::setup_event::SetupEventResponse,
        crate::routes::app::events::prerun_event::PrerunEventQuery,
        crate::routes::app::events::prerun_event::PrerunPageEventRequest,
        crate::routes::app::events::page_trigger::PageTrigger,
        crate::routes::app::events::page_trigger::PageSpecialEvent,
        crate::routes::app::prerun_shared::RuntimeVariable,
        crate::routes::app::prerun_shared::OAuthRequirement,
        crate::routes::app::prerun_shared::PrerunPayload,
        crate::routes::app::events::prerun_event::PrerunEventResponse,
        crate::routes::app::board::prerun_board::PrerunBoardResponse,
        crate::routes::app::board::prerun_board::PrerunBoardQuery,
        crate::routes::app::board::element_demand::ElementDemandQuery,
        crate::routes::app::board::element_demand::ElementDemandResponse,
        crate::routes::app::events::invoke_event::InvokeEventQuery,
        crate::routes::app::events::invoke_event::InvokeEventRequest,
        crate::routes::app::events::invoke_event::InvokeEventResponse,
        crate::routes::app::events::canary::CanaryExplainResponse,
        crate::routes::app::events::canary::CanaryStatsQuery,
        crate::routes::app::events::canary::EventVariantStats,
        crate::routes::app::events::canary::EventVariantStatsResponse,
        crate::routes::app::events::canary::CanarySharePatch,
        crate::routes::app::events::canary::PutVariantsBody,
        crate::routes::app::events::canary::CanaryPromoteBody,
        crate::routes::app::events::canary::CanaryPromoteResponse,
        crate::routes::app::events::canary::CanaryAbortBody,
        crate::routes::app::events::canary::CanaryAbortResponse,
        crate::routes::app::events::canary::EventSetupInfo,
        crate::routes::app::events::canary::PromotionGateSummary,
        crate::routes::app::events::regression::CorpusEntry,
        crate::routes::app::events::regression::EventCorpusResponse,
        crate::routes::app::events::regression::CorpusPayloadResponse,
        crate::routes::app::events::regression::PromoteFixtureRequest,
        crate::routes::app::events::regression::FixtureSummary,
        crate::routes::app::events::regression::RegressionSuiteResponse,
        crate::routes::app::events::regression::PutRegressionSuiteRequest,
        crate::routes::app::events::regression::RunRegressionSuiteRequest,
        crate::routes::app::events::regression::RunRegressionSuiteAccepted,
        crate::routes::app::events::regression::SuiteRunSummary,
        crate::routes::app::events::regression::SuiteCaseResultView,
        crate::routes::app::events::regression::SuiteRunDetailResponse,
        crate::routes::app::graph::actions::OntologyObjectRef,
        crate::routes::app::graph::actions::InvokeOntologyActionRequest,
        crate::routes::app::graph::actions::OntologyActionPrerunResponse,
        crate::routes::app::graph::create_overlay::CreateOverlayPayload,
        crate::routes::app::graph::update_overlay::UpdateOverlayPayload,
        crate::routes::app::graph::cypher::CypherPayload,
        crate::routes::app::graph::sql::SqlPayload,
        crate::routes::app::graph::upsert_nodes::UpsertNodesPayload,
        crate::routes::app::graph::upsert_nodes::UpsertResult,
        crate::routes::app::graph::upsert_edges::UpsertEdgesPayload,
        crate::routes::app::graph::neighbors::NeighborsPayload,
        crate::routes::app::graph::children::ChildrenPayload,
        crate::routes::app::graph::subgraph::SubgraphPayload,
        crate::routes::app::graph::subgraph::SeedEntry,
        crate::routes::app::graph::paths::PathsPayload,
        crate::routes::app::graph::validate::ValidationResult,
        crate::routes::app::graph::validate::MappingValidation,
        crate::routes::app::events::invoke_event_async::InvokeEventAsyncRequest,
        crate::routes::app::events::invoke_event_async::InvokeEventAsyncResponse,
        crate::routes::app::events::registrations::ListRegistrationsQuery,
        crate::routes::app::events::registrations::AuthView,
        crate::routes::app::events::registrations::RegistrationView,
        crate::routes::app::events::registrations::ListRegistrationsResponse,
        crate::routes::app::events::alias::AliasView,
        crate::routes::app::events::alias::UpsertAliasRequest,
        crate::routes::alias::AliasLookupResponse,
        crate::routes::app::events::upsert_event_feedback::FeedbackBody,
        crate::routes::app::events::upsert_event_feedback::FeedbackResponse,
        // Comments
        crate::routes::app::comments::upsert_comment::CommentBody,
        crate::routes::app::comments::upsert_comment::CommentResponse,
        crate::routes::app::comments::get_comments::CommentsQuery,
        crate::routes::app::comments::get_comments::CommentItem,
        crate::routes::app::comments::get_comments::CommentsResponse,
        // App packages
        crate::routes::app::packages::AddPackageRequest,
        crate::routes::app::packages::UpdatePackageRequest,
        crate::routes::app::packages::AppPackageResponse,
        crate::routes::app::packages::PatchInfo,
        crate::routes::app::packages::PackageUpdateInfo,
        // Realtime
        crate::routes::app::board::realtime::RealtimeParams,
        crate::realtime_ice::RealtimeIceServer,
        // Data
        crate::routes::app::data::upload_files::UploadFilesPayload,
        crate::routes::app::data::download_files::DownloadFilesPayload,
        crate::routes::app::data::list_files::ListFilesPayload,
        crate::routes::app::data::delete_files::DeleteFilesPayload,
        // University
        crate::routes::user::lookup::UserLookupResponse,
        crate::routes::user::lookup::UserBatchLookupBody,
        crate::routes::user::contacts::UserContactsResponse,
        crate::routes::course::courses::CourseListItem,
        crate::routes::course::courses::CourseUpsertBody,
        crate::routes::course::courses::CourseDetail,
        crate::routes::course::courses::CourseStructure,
        crate::routes::course::courses::ModuleWithLessons,
        crate::routes::course::courses::LessonSummary,
        crate::routes::course::courses::ListCoursesQuery,
        crate::routes::course::courses::CourseMediaItem,
        crate::routes::course::courses::CourseMediaQuery,
        crate::routes::course::courses::PushCourseMediaResponse,
        crate::routes::course::assets::CourseAssetView,
        crate::routes::course::assets::CourseAssetKind,
        crate::routes::course::assets::CreateCourseAssetBody,
        crate::routes::course::assets::CreateCourseAssetResponse,
        crate::routes::course::assets::UpdateCourseAssetBody,
        crate::routes::course::assets::ListCourseAssetsQuery,
        crate::routes::course::assets::OptimizeCourseAssetResponse,
        crate::routes::course::modules::ModuleUpsertBody,
        crate::routes::course::lessons::LessonUpsertBody,
        crate::routes::course::lessons::LessonWithChildren,
        crate::routes::course::challenges::ChallengeUpsertBody,
        crate::routes::course::challenges::ChallengeView,
        crate::routes::course::app_links::AppLinkUpsertBody,
        crate::routes::course::app_refs::AppRefUpsertBody,
        crate::routes::course::app_refs::AppRefView,
        crate::routes::course::attempts::AttemptSubmission,
        crate::routes::course::attempts::AttemptResult,
        crate::routes::course::attempts::ChallengeAttemptView,
        crate::routes::course::progress::UserLessonProgressView,
        crate::routes::course::certificates::CertificateView,
        crate::routes::course::paths::LearningPathView,
        crate::routes::course::paths::LearningPathStepView,
        crate::routes::course::paths::LearningPathUpsertBody,
        crate::routes::course::paths::LearningPathStepUpsertBody,
        crate::routes::course::leaderboard::LeaderboardEntry,
        crate::routes::course::leaderboard::OptInBody,
        crate::routes::course::weekly::CurrentWeekly,
        crate::routes::course::shared_app::OpenSharedAppResponse,
        crate::routes::course::shared_app::OpenSharedAppQuery,
        crate::routes::course::translate::TranslateQuery,
        crate::routes::course::translate::TranslateResponse,
        // Telemetry
        crate::routes::telemetry::TelemetryIngestPayload,
        crate::routes::flowscript::ReportFlowScriptApplyFailureBody,
        crate::routes::flowscript::ReportFlowScriptApplyFailureResponse,
        crate::routes::admin::telemetry::flowscript_failures::ListFlowScriptFailuresResponse,
        crate::routes::admin::telemetry::flowscript_failures::FlowScriptFailureDetailResponse,
        crate::routes::admin::telemetry::flowscript_failures::FlowScriptFailureRecord,
        crate::routes::admin::telemetry::flowscript_failures::FlowScriptFailureSummary,
        crate::routes::admin::telemetry::flowscript_failures::FlowScriptFailureFacet,
        crate::routes::telemetry::TelemetryEventPayload,
        crate::routes::telemetry::TelemetryIngestResponse,
        crate::routes::telemetry::errors::TelemetryErrorIngestPayload,
        crate::routes::telemetry::errors::TelemetryErrorPayload,
        crate::routes::telemetry::errors::TelemetryStackFramePayload,
        crate::routes::telemetry::errors::TelemetryBreadcrumbPayload,
        crate::routes::telemetry::errors::TelemetryErrorIngestResponse,
        crate::routes::telemetry::sessions::TelemetrySessionIngestPayload,
        crate::routes::telemetry::sessions::TelemetrySessionPayload,
        crate::routes::telemetry::sessions::TelemetrySessionIngestResponse,
        crate::routes::telemetry::spans::TelemetrySpanIngestPayload,
        crate::routes::telemetry::spans::TelemetrySpanPayload,
        crate::routes::telemetry::spans::TelemetrySpanIngestResponse,
        crate::routes::telemetry::performance::TelemetryPerfIngestPayload,
        crate::routes::telemetry::performance::TelemetryPerfMetricPayload,
        crate::routes::telemetry::performance::TelemetryPerfIngestResponse,
        crate::routes::telemetry::config::TelemetryConfigResponse,
        crate::routes::telemetry::config::TelemetrySamplingConfig,
        crate::routes::admin::telemetry::TelemetryOverviewResponse,
        crate::routes::admin::telemetry::TopEventBucket,
        crate::routes::admin::telemetry::SourceBucket,
        crate::routes::admin::telemetry::PlatformBucket,
        crate::routes::admin::telemetry::VersionBucket,
        crate::routes::admin::telemetry::TelemetryTimeseriesResponse,
        crate::routes::admin::telemetry::TelemetryTimeseriesPoint,
        crate::routes::admin::telemetry::CountryBucket,
        crate::routes::admin::telemetry::TelemetryEventRecord,
        crate::routes::admin::telemetry::ListTelemetryEventsResponse,
        crate::routes::admin::telemetry::TelemetryEngagementResponse,
        crate::routes::admin::telemetry::DauPoint,
        crate::routes::admin::telemetry::RetentionCohort,
        crate::routes::admin::telemetry::DropOffPath,
        crate::routes::admin::telemetry::TelemetryFlowPilotResponse,
        crate::routes::admin::telemetry::FlowPilotTotals,
        crate::routes::admin::telemetry::FlowPilotTrendPoint,
        crate::routes::admin::telemetry::FlowPilotFailureGroup,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackRecord,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackFacetCount,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackTrendPoint,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackSummary,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackFilters,
        crate::routes::admin::telemetry::prompt_feedback::ListPromptFeedbackResponse,
        crate::routes::admin::telemetry::prompt_feedback::PromptFeedbackDetailResponse,
        crate::routes::ai::global_chat::feedback::FlowPilotFeedbackBody,
        crate::routes::ai::global_chat::feedback::FlowPilotFeedbackResponse,
        crate::routes::admin::telemetry::issues::TelemetryIssueRecord,
        crate::routes::admin::telemetry::issues::ListTelemetryIssuesResponse,
        crate::routes::admin::telemetry::issues::TelemetryIssueEvent,
        crate::routes::admin::telemetry::issues::TelemetryIssueDetailResponse,
        crate::routes::admin::telemetry::issues::IssueTimeseriesPoint,
        crate::routes::admin::telemetry::issues::IssueReleaseBucket,
        crate::routes::admin::telemetry::issues::UpdateTelemetryIssuePayload,
        crate::routes::admin::telemetry::symbolicate::StackFrame,
        crate::routes::admin::telemetry::release_health::TelemetryReleaseRow,
        crate::routes::admin::telemetry::release_health::ListTelemetryReleasesResponse,
        crate::routes::admin::telemetry::release_health::ReleaseHealthTrendPoint,
        crate::routes::admin::telemetry::release_health::TelemetryReleaseHealthResponse,
        crate::routes::admin::telemetry::sourcemaps::UploadSourceMapPayload,
        crate::routes::admin::telemetry::sourcemaps::UploadSourceMapResponse,
        crate::routes::admin::telemetry::traces::TelemetryTraceRow,
        crate::routes::admin::telemetry::traces::ListTelemetryTracesResponse,
        crate::routes::admin::telemetry::traces::TelemetryTraceSpan,
        crate::routes::admin::telemetry::traces::TelemetryTraceDetailResponse,
        crate::routes::admin::telemetry::performance::PerfMetricSummary,
        crate::routes::admin::telemetry::performance::PerfTrendPoint,
        crate::routes::admin::telemetry::performance::PerfPathRow,
        crate::routes::admin::telemetry::performance::TelemetryPerformanceResponse,
        crate::routes::admin::telemetry::span_stats::SpanOperationStats,
        crate::routes::admin::telemetry::span_stats::TelemetrySpanStatsResponse,
        crate::routes::admin::telemetry::sweep::TelemetrySweepResponse,
        crate::routes::admin::telemetry::rollup::TelemetryRollupResponse,
        crate::routes::telemetry::llm::TelemetryLlmIngestPayload,
        crate::routes::telemetry::llm::TelemetryLlmCallPayload,
        crate::routes::telemetry::llm::TelemetryLlmIngestResponse,
        crate::routes::admin::telemetry::llm::LlmTotals,
        crate::routes::admin::telemetry::llm::LlmModelStats,
        crate::routes::admin::telemetry::llm::LlmProviderStats,
        crate::routes::admin::telemetry::llm::LlmOperationStats,
        crate::routes::admin::telemetry::llm::LlmErrorKindStats,
        crate::routes::admin::telemetry::llm::LlmTrendPoint,
        crate::routes::admin::telemetry::llm::TelemetryLlmResponse,
        crate::routes::admin::telemetry::alerts::TelemetryAlertRuleRecord,
        crate::routes::admin::telemetry::alerts::ListTelemetryAlertRulesResponse,
        crate::routes::admin::telemetry::alerts::TelemetryAlertEventRecord,
        crate::routes::admin::telemetry::alerts::ListTelemetryAlertEventsResponse,
        crate::routes::admin::telemetry::alerts::DeleteTelemetryAlertRuleResponse,
        crate::routes::admin::telemetry::alerts::EvaluateTelemetryAlertsResponse,
        crate::routes::admin::telemetry::alerts::CreateTelemetryAlertRulePayload,
        crate::routes::admin::telemetry::alerts::UpdateTelemetryAlertRulePayload,
        crate::routes::admin::telemetry::query::TelemetryQueryDefinition,
        crate::routes::admin::telemetry::query::TelemetryQueryMetric,
        crate::routes::admin::telemetry::query::TelemetryQueryFilter,
        crate::routes::admin::telemetry::query::TelemetryQueryResponse,
        crate::routes::admin::telemetry::saved_queries::TelemetrySavedQueryRecord,
        crate::routes::admin::telemetry::saved_queries::ListTelemetrySavedQueriesResponse,
        crate::routes::admin::telemetry::saved_queries::CreateTelemetrySavedQueryPayload,
        crate::routes::admin::telemetry::saved_queries::UpdateTelemetrySavedQueryPayload,
        crate::routes::admin::telemetry::dashboards::TelemetryDashboardRecord,
        crate::routes::admin::telemetry::dashboards::ListTelemetryDashboardsResponse,
        crate::routes::admin::telemetry::dashboards::CreateTelemetryDashboardPayload,
        crate::routes::admin::telemetry::dashboards::UpdateTelemetryDashboardPayload,
        crate::utils::fork::ForkIdMap,
        crate::utils::fork::ForkPolicy,
        crate::utils::fork::ForkDatabaseMode,
        crate::utils::fork::db_schema::ForkTableSchema,
        crate::utils::fork::preview::ForkCategorySize,
        crate::utils::fork::preview::ForkSizeBreakdown,
        crate::routes::app::internal::change_appearance::AppearanceResponse,
        crate::routes::app::internal::change_forking::ForkSettingsResponse,
        crate::routes::app::fork::preview::ForkPreviewTarget,
        crate::utils::fork::job::ForkJobView,
        // Deletion schemas
        crate::deletion::AcceptedDeletion,
        crate::deletion::QueueReport,
        crate::routes::admin::deletions::DeletionJobView,
        crate::routes::admin::deletions::DeletionJobDetail,
        crate::routes::admin::deletions::DeletionStepView,
        crate::routes::admin::deletions::ListDeletionJobsResponse,
    ))
)]
pub struct ApiDoc;

#[cfg(test)]
mod tests {
    use super::ApiDoc;
    use flow_like_types::Value;
    use utoipa::OpenApi;

    fn collect_refs(value: &Value, out: &mut Vec<String>) {
        match value {
            Value::Object(map) => {
                for (key, entry) in map {
                    if key == "$ref"
                        && let Some(reference) = entry.as_str()
                    {
                        out.push(reference.to_string());
                    }
                    collect_refs(entry, out);
                }
            }
            Value::Array(items) => {
                for item in items {
                    collect_refs(item, out);
                }
            }
            _ => {}
        }
    }

    /// A response body or request body referencing a type that was never added to
    /// `components(schemas(...))` produces a dangling `$ref`, which breaks every
    /// generated SDK. This catches the omission at test time instead of at codegen.
    #[test]
    fn every_schema_reference_is_registered() {
        let spec: Value = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let schemas = spec
            .get("components")
            .and_then(|c| c.get("schemas"))
            .and_then(|s| s.as_object())
            .expect("spec exposes component schemas");

        let mut refs = Vec::new();
        collect_refs(&spec, &mut refs);

        let dangling: Vec<&String> = refs
            .iter()
            .filter(|reference| {
                reference
                    .strip_prefix("#/components/schemas/")
                    .is_some_and(|name| !schemas.contains_key(name))
            })
            .collect();

        assert!(
            dangling.is_empty(),
            "unregistered schema references: {:?}",
            dangling
        );
    }

    #[test]
    fn page_prerun_documents_get_and_governed_post_contracts() {
        let spec: Value = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let prerun = spec
            .pointer("/paths/~1apps~1{app_id}~1events~1{event_id}~1prerun")
            .and_then(Value::as_object)
            .expect("Page prerun path is documented");

        assert!(prerun.contains_key("get"), "Page prerun GET is missing");
        let post = prerun
            .get("post")
            .expect("governed Page prerun POST is missing");
        assert_eq!(
            post.pointer("/requestBody/content/application~1json/schema/$ref")
                .and_then(Value::as_str),
            Some("#/components/schemas/PrerunPageEventRequest")
        );
        assert_eq!(
            spec.pointer(
                "/components/schemas/PrerunPageEventRequest/properties/page_trigger/$ref",
            )
            .and_then(Value::as_str),
            Some("#/components/schemas/PageTrigger")
        );
    }

    #[test]
    fn telemetry_paths_are_documented() {
        let spec: Value = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let paths = spec
            .get("paths")
            .and_then(|p| p.as_object())
            .expect("spec exposes paths");

        for path in [
            "/telemetry/events",
            "/telemetry/errors",
            "/telemetry/sessions",
            "/telemetry/spans",
            "/telemetry/performance",
            "/telemetry/config",
            "/admin/telemetry/prompt-feedback",
            "/admin/telemetry/prompt-feedback/{feedback_id}",
            "/admin/telemetry/issues",
            "/admin/telemetry/issues/{issue_id}",
            "/admin/telemetry/releases",
            "/admin/telemetry/release-health",
            "/admin/telemetry/sourcemaps",
            "/admin/telemetry/traces",
            "/admin/telemetry/traces/{trace_id}",
            "/admin/telemetry/performance",
            "/admin/telemetry/span-stats",
            "/admin/telemetry/sweep",
            "/admin/telemetry/rollup",
            "/telemetry/llm",
            "/admin/telemetry/llm",
            "/admin/telemetry/alerts",
            "/admin/telemetry/alerts/events",
            "/admin/telemetry/alerts/evaluate",
            "/admin/telemetry/alerts/{rule_id}",
            "/admin/telemetry/alerts/{event_id}/ack",
            "/admin/telemetry/query",
            "/admin/telemetry/saved-queries",
            "/admin/telemetry/saved-queries/{query_id}",
            "/admin/telemetry/dashboards",
            "/admin/telemetry/dashboards/{dashboard_id}",
        ] {
            assert!(paths.contains_key(path), "missing OpenAPI path '{}'", path);
        }
    }

    /// Nine `202` bodies tell callers to follow the job on these endpoints; an
    /// endpoint missing here is missing from every generated SDK.
    #[test]
    fn deletion_and_fork_job_paths_are_documented() {
        let spec: Value = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let paths = spec
            .get("paths")
            .and_then(|p| p.as_object())
            .expect("spec exposes paths");

        for (path, method) in [
            ("/admin/deletions", "get"),
            ("/admin/deletions/run", "post"),
            ("/admin/deletions/{job_id}", "get"),
            ("/admin/deletions/{job_id}/retry", "post"),
            ("/apps/fork/jobs/{job_id}", "get"),
        ] {
            let entry = paths
                .get(path)
                .and_then(Value::as_object)
                .unwrap_or_else(|| panic!("missing OpenAPI path '{path}'"));
            assert!(
                entry.contains_key(method),
                "OpenAPI path '{path}' has no '{method}' operation"
            );
        }
    }
}
