name: "benchmarks"

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  benchmark-application:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install additional packages
        run: |
          sudo apt-get install -y \
            libgtk-3-dev \
            libclang-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            pkg-config \
            protobuf-compiler \
            webkit2gtk-4.1

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install bun
        run: "npm install -g bun"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.os == 'macos' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install frontend dependencies
        run: bun install # change this to npm, pnpm or bun depending on which one you use.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check llamafile
        run: |
          if [ ! -f "./src-tauri/bin/llamafiler" ]; then
            echo "::error::Llamafile not found! Ensure it is downloaded correctly."
            exit 1
          fi

      - name: Run Rust tests
        run: cargo bench

      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion