name: "Code Quality"

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  code-quality:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install bun
        run: "npm install -g bun"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.os == 'macos' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install frontend dependencies
        run: bun install # change this to npm, pnpm or bun depending on which one you use.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install clippy
        run: rustup component add clippy
      
      - name: Run Clippy
        run: cargo clippy --message-format=json -- -D warnings > clippy-report.json

      - name: Upload Clippy Report
        uses: actions/upload-artifact@v4
        with:
          name: clippy-report
          path: clippy-report.json

      - name: Run ESLint
        run: bun run lint -- --format json > eslint-report.json

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json