name: SonarQube Scan

on:
  push:
    branches:
      - dev


jobs:
  sonarqube:
    name: Build and analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}